In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "acoes_retornos.csv",
    #index_col="date",
    parse_dates=["date"],
)

df["date"] = pd.to_datetime(df["date"])

df_wide = df.pivot(
    index="date",
    columns="ticker",
    values="retorno"
)

df_wide = df_wide.sort_index()
df_wide

ticker,AALR3,ABCB4,ABEV3,ACES4,AEDU3,AERI3,AESB3,AFLT3,AGEI3,AGRO3,...,WEST3,WHRL3,WHRL4,WIZC3,WIZS3,WLMM3,WLMM4,XPBR31,YDUQ3,ZAMP3
date,,,,,,,,,,,,,,,,,,,,,
2008-01-02,NaN,-0.029536,-0.004070,-0.019289,NaN,NaN,NaN,NaN,NaN,-0.006000,...,NaN,-0.075000,0.024390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-03,NaN,-0.025217,0.021251,-0.015528,NaN,NaN,NaN,NaN,NaN,0.006036,...,NaN,0.000000,-0.007937,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-04,NaN,-0.032114,-0.022409,0.004206,NaN,NaN,NaN,NaN,NaN,0.000000,...,NaN,-0.027027,-0.050667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-07,NaN,-0.027650,0.001637,-0.012565,NaN,NaN,NaN,NaN,NaN,0.035000,...,NaN,0.083333,-0.028090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-08,NaN,0.033175,-0.007356,0.016967,NaN,NaN,NaN,NaN,NaN,-0.024155,...,NaN,NaN,0.011561,NaN,NaN,NaN,-0.018208,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-14,0.008772,-0.001992,0.016005,NaN,NaN,0.004587,0.0,0.016282,NaN,-0.024533,...,-0.045902,-0.002857,-0.005571,0.006394,NaN,NaN,0.011882,0.000887,0.001009,NaN
2026-09-15,-0.017391,-0.014371,-0.008822,NaN,NaN,0.004566,0.0,-0.022697,NaN,-0.004374,...,0.079038,-0.005731,0.016807,0.012706,NaN,NaN,-0.001236,-0.012993,0.023185,NaN
2026-09-16,0.026549,-0.001215,-0.006357,NaN,NaN,0.027273,0.0,NaN,NaN,0.006041,...,-0.012739,0.031700,0.002755,-0.002509,NaN,NaN,-0.028465,0.020844,-0.004926,NaN
2026-09-17,-0.002874,0.012571,-0.005118,NaN,NaN,0.000000,0.0,NaN,NaN,0.000000,...,0.077419,-0.022346,-0.002747,-0.006289,NaN,NaN,0.006369,0.011626,0.030693,NaN
2026-09-18,0.037464,-0.006808,-0.010932,NaN,NaN,0.000000,0.0,NaN,NaN,-0.013100,...,-0.050898,0.000000,0.005510,0.017722,NaN,NaN,-0.017722,-0.010526,0.018252,NaN

In [13]:
prices = df_wide
import numpy as np
momentum_1m = prices.pct_change(21)
momentum_3m = prices.pct_change(63)
momentum_6m = prices.pct_change(126)
momentum_12m = prices.pct_change(252)

/var/folders/pt/8dl78km97fnbygj9fh3mkpmh0000gn/T/ipykernel_36028/3444394211.py:3: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  momentum_1m = prices.pct_change(21)
/var/folders/pt/8dl78km97fnbygj9fh3mkpmh0000gn/T/ipykernel_36028/3444394211.py:4: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  momentum_3m = prices.pct_change(63)
/var/folders/pt/8dl78km97fnbygj9fh3mkpmh0000gn/T/ipykernel_36028/3444394211.py:5: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  momentum_6m = prices.pct_change(126)
/var/folders/pt/8dl78km97fnbygj9fh3mkpmh0000gn/T/ipykernel_36028/3444394211.py:6: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  momentum_12m = prices.pct_change(252)

In [14]:
momentum_1m

ticker,AALR3,ABCB4,ABEV3,ACES4,AEDU3,AERI3,AESB3,AFLT3,AGEI3,AGRO3,...,WEST3,WHRL3,WHRL4,WIZC3,WIZS3,WLMM3,WLMM4,XPBR31,YDUQ3,ZAMP3
date,,,,,,,,,,,,,,,,,,,,,
2008-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-14,-1.591228,-1.409453,2.395372,0.0,0.0,-0.859109,NaN,inf,0.0,3.447893,...,-1.548824,-1.510000,-2.086351,-0.040921,0.0,-1.0,-3.568089,-0.974640,-0.973187,NaN
2026-09-15,0.443478,2.627944,-0.225768,0.0,0.0,0.013699,NaN,-2.369381,0.0,-1.463899,...,-1.841188,-0.771410,-4.294118,-1.872127,0.0,-1.0,-0.696097,-2.201379,-1.447480,NaN
2026-09-16,-1.621997,-0.083435,0.172123,0.0,0.0,0.520455,NaN,-inf,0.0,-4.664653,...,-1.286624,4.547550,0.074380,-1.233375,0.0,NaN,-9.131601,-2.256363,-inf,NaN
2026-09-17,-1.902299,-1.835599,-2.251440,0.0,0.0,-1.000000,NaN,-0.120793,0.0,-1.000000,...,-3.183226,0.310987,-0.948849,-0.527044,0.0,NaN,inf,0.485901,21.467327,NaN
2026-09-18,-3.360231,1.525831,-4.220707,0.0,0.0,-1.000000,NaN,-1.508553,0.0,-1.999454,...,-2.538257,-1.000000,-0.830119,0.643671,0.0,-1.0,-2.016034,-1.325015,0.672310,NaN

In [15]:
# dado historico de volume da B3
# 2008 a 2026

import pandas as pd
from pathlib import Path


def ler_cotahist(path):

    names = [
        "tipo_registro",
        "data",
        "cod_bdi",
        "ticker",
        "tipo_mercado",
        "nome_empresa",
        "especificacao",
        "prazo_termo",
        "moeda",
        "preco_abertura",
        "preco_maximo",
        "preco_minimo",
        "preco_medio",
        "preco_ultimo",
        "preco_oferta_compra",
        "preco_oferta_venda",
        "numero_negocios",
        "quantidade_negociada",
        "volume_financeiro",
        "preco_exercicio",
        "indicador_correcao",
        "data_vencimento",
        "fator_cotacao",
        "pontos_exercicio",
        "isin",
        "numero_distribuicao"
    ]

    widths = [
        2, 8, 2, 12, 3, 12, 10, 3, 4,
        13, 13, 13, 13, 13, 13, 13,
        5, 18, 18, 13, 1, 8, 7, 13, 12, 3
    ]

    df = pd.read_fwf(
        path,
        widths=widths,
        names=names,
        dtype=str,
        header=None
    )

    # Apenas registros de cotação
    df = df[df["tipo_registro"] == "01"].copy()

    # Limpeza
    for col in ["ticker", "nome_empresa", "especificacao", "moeda", "isin"]:
        df[col] = df[col].fillna("").str.strip()

    # Data
    df["data"] = pd.to_datetime(
        df["data"],
        format="%Y%m%d",
        errors="coerce"
    )

    # Preços
    preco_cols = [
        "preco_abertura",
        "preco_maximo",
        "preco_minimo",
        "preco_medio",
        "preco_ultimo",
        "preco_oferta_compra",
        "preco_oferta_venda"
    ]

    for col in preco_cols:
        df[col] = (
            pd.to_numeric(df[col], errors="coerce") / 100
        )

    # Número de negócios
    df["numero_negocios"] = pd.to_numeric(
        df["numero_negocios"],
        errors="coerce"
    )

    # Quantidade de ações negociadas
    df["quantidade_negociada"] = pd.to_numeric(
        df["quantidade_negociada"],
        errors="coerce"
    )

    # Volume financeiro em R$
    df["volume_financeiro"] = (
        pd.to_numeric(
            df["volume_financeiro"],
            errors="coerce"
        ) / 100
    )

    # Mercado à vista
    df = df[df["tipo_mercado"] == "010"].copy()

    # Remove registros inválidos
    df = df[
        df["ticker"].ne("") &
        df["data"].notna() &
        df["preco_ultimo"].notna()
    ].copy()

    return df

In [16]:
df = ler_cotahist("COTAHIST_A2008.TXT")

df = df.sort_values(["ticker", "data"])

g = df.groupby("ticker")

In [19]:
df

,tipo_registro,data,cod_bdi,ticker,tipo_mercado,nome_empresa,especificacao,prazo_termo,moeda,preco_abertura,...,numero_negocios,quantidade_negociada,volume_financeiro,preco_exercicio,indicador_correcao,data_vencimento,fator_cotacao,pontos_exercicio,isin,numero_distribuicao
1,01,2008-01-02,02,ABCB4,010,ABC BRASIL,PN EJ N2,NaN,R$,12.00,...,42,87000,1003110.0,0000000000000,0,99991231,0000001,0000000000000,BRABCBACNPR4,101
1311,01,2008-01-03,02,ABCB4,010,ABC BRASIL,PN EJ N2,NaN,R$,11.41,...,10,2200,25054.0,0000000000000,0,99991231,0000001,0000000000000,BRABCBACNPR4,101
2460,01,2008-01-04,02,ABCB4,010,ABC BRASIL,PN EJ N2,NaN,R$,11.45,...,23,86700,938846.0,0000000000000,0,99991231,0000001,0000000000000,BRABCBACNPR4,101
3736,01,2008-01-07,02,ABCB4,010,ABC BRASIL,PN EJ N2,NaN,R$,10.80,...,18,50900,534068.0,0000000000000,0,99991231,0000001,0000000000000,BRABCBACNPR4,101
4888,01,2008-01-08,02,ABCB4,010,ABC BRASIL,PN N2,NaN,R$,10.76,...,67,247400,2614215.0,0000000000000,0,99991231,0000001,0000000000000,BRABCBACNPR4,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280950,01,2008-12-22,02,WSON11,010,WILSON SONS,DR3,NaN,R$,10.85,...,1,100,1085.0,0000000000000,0,99991231,0000001,0000000000000,BRWSONBDR009,101
281770,01,2008-12-23,02,WSON11,010,WILSON SONS,DR3,NaN,R$,10.85,...,13,4000,43657.0,0000000000000,0,99991231,0000001,0000000000000,BRWSONBDR009,101
282608,01,2008-12-26,02,WSON11,010,WILSON SONS,DR3,NaN,R$,11.00,...,5,7600,83600.0,0000000000000,0,99991231,0000001,0000000000000,BRWSONBDR009,101
283454,01,2008-12-29,02,WSON11,010,WILSON SONS,DR3,NaN,R$,10.95,...,2,200,2191.0,0000000000000,0,99991231,0000001,0000000000000,BRWSONBDR009,101
284234,01,2008-12-30,02,WSON11,010,WILSON SONS,DR3,NaN,R$,10.95,...,1,100,1095.0,0000000000000,0,99991231,0000001,0000000000000,BRWSONBDR009,101

In [21]:
import pandas as pd
from pathlib import Path


# ============================================================
# 1. CONFIGURAÇÃO
# ============================================================

PASTA_B3 = Path("./")

# Layout do COTAHIST
COLSPECS = [
    (0, 2),      # tipo_registro
    (2, 10),     # data
    (10, 12),    # cod_bdi
    (12, 24),    # ticker
    (24, 27),    # tipo_mercado
    (27, 39),    # nome_empresa
    (39, 49),    # especificacao
    (49, 52),    # prazo_termo
    (52, 56),    # moeda
    (56, 69),    # preco_abertura
    (69, 82),    # preco_maximo
    (82, 95),    # preco_minimo
    (95, 108),   # preco_medio
    (108, 121),  # preco_ultimo
    (121, 134),  # preco_oferta_compra
    (134, 147),  # preco_oferta_venda
    (147, 152),  # numero_negocios
    (152, 170),  # quantidade_negociada
    (170, 188),  # volume_financeiro
    (188, 201),  # preco_exercicio
    (201, 202),  # indicador_correcao
    (202, 210),  # data_vencimento
    (210, 217),  # fator_cotacao
    (217, 230),  # pontos_exercicio
    (230, 242),  # isin
    (242, 245),  # numero_distribuicao
]

NOMES = [
    "tipo_registro",
    "data",
    "cod_bdi",
    "ticker",
    "tipo_mercado",
    "nome_empresa",
    "especificacao",
    "prazo_termo",
    "moeda",
    "preco_abertura",
    "preco_maximo",
    "preco_minimo",
    "preco_medio",
    "preco_ultimo",
    "preco_oferta_compra",
    "preco_oferta_venda",
    "numero_negocios",
    "quantidade_negociada",
    "volume_financeiro",
    "preco_exercicio",
    "indicador_correcao",
    "data_vencimento",
    "fator_cotacao",
    "pontos_exercicio",
    "isin",
    "numero_distribuicao",
]


# ============================================================
# 2. FUNÇÃO PARA LER UM ARQUIVO
# ============================================================

def ler_cotahist(arquivo):

    df = pd.read_fwf(
        arquivo,
        colspecs=COLSPECS,
        names=NOMES,
        encoding="latin1",
        dtype=str
    )

    # --------------------------------------------------------
    # Mantém somente registros de negociação
    # --------------------------------------------------------
    df = df[df["tipo_registro"] == "01"].copy()

    # --------------------------------------------------------
    # Data
    # --------------------------------------------------------
    df["data"] = pd.to_datetime(
        df["data"],
        format="%Y%m%d",
        errors="coerce"
    )

    # --------------------------------------------------------
    # Ticker
    # --------------------------------------------------------
    df["ticker"] = df["ticker"].str.strip()

    # --------------------------------------------------------
    # Campos numéricos
    # --------------------------------------------------------

    colunas_numericas = [
        "preco_abertura",
        "preco_maximo",
        "preco_minimo",
        "preco_medio",
        "preco_ultimo",
        "preco_oferta_compra",
        "preco_oferta_venda",
        "numero_negocios",
        "quantidade_negociada",
        "volume_financeiro",
        "preco_exercicio",
        "fator_cotacao",
        "pontos_exercicio"
    ]

    for coluna in colunas_numericas:
        df[coluna] = pd.to_numeric(
            df[coluna],
            errors="coerce"
        )

    # --------------------------------------------------------
    # Ajustes dos campos monetários
    # --------------------------------------------------------

    colunas_preco = [
        "preco_abertura",
        "preco_maximo",
        "preco_minimo",
        "preco_medio",
        "preco_ultimo",
        "preco_oferta_compra",
        "preco_oferta_venda",
        "preco_exercicio"
    ]

    for coluna in colunas_preco:
        df[coluna] = df[coluna] / 100

    # Volume
    df["volume_financeiro"] = df["volume_financeiro"] / 100

    return df


# ============================================================
# 3. ENCONTRAR TODOS OS ARQUIVOS
# ============================================================

arquivos = sorted(
    PASTA_B3.glob("COTAHIST_A*.TXT")
)

print(f"Arquivos encontrados: {len(arquivos)}")

for arquivo in arquivos:
    print(arquivo.name)


# ============================================================
# 4. LER TODOS OS ANOS
# ============================================================

lista_dfs = []

for arquivo in arquivos:

    print(f"Lendo: {arquivo.name}")

    try:

        df_ano = ler_cotahist(arquivo)

        # Guarda o ano de origem
        df_ano["ano_arquivo"] = arquivo.stem[-4:]

        lista_dfs.append(df_ano)

        print(
            f"   {len(df_ano):,} registros"
        )

    except Exception as e:

        print(
            f"ERRO em {arquivo.name}: {e}"
        )


# ============================================================
# 5. JUNTAR TODOS OS ANOS
# ============================================================

df_b3 = pd.concat(
    lista_dfs,
    ignore_index=True
)


# ============================================================
# 6. ORDENAR
# ============================================================

df_b3 = df_b3.sort_values(
    ["data", "ticker"]
).reset_index(drop=True)


# ============================================================
# 7. RESULTADO
# ============================================================

print("\n==============================")
print("DATAFRAME FINAL")
print("==============================")

print(f"Linhas: {len(df_b3):,}")
print(f"Colunas: {len(df_b3.columns)}")
print(
    f"Período: "
    f"{df_b3['data'].min()} "
    f"até "
    f"{df_b3['data'].max()}"
)

print(
    f"Tickers únicos: "
    f"{df_b3['ticker'].nunique():,}"
)


# ============================================================
# 8. SALVAR
# ============================================================

df_b3.to_parquet(
    "b3_cotahist_2008_2026.parquet",
    index=False
)

print("\nArquivo salvo:")
print("b3_cotahist_2008_2026.parquet")

Arquivos encontrados: 19
COTAHIST_A2008.TXT
COTAHIST_A2009.TXT
COTAHIST_A2010.TXT
COTAHIST_A2011.TXT
COTAHIST_A2012.TXT
COTAHIST_A2013.TXT
COTAHIST_A2014.TXT
COTAHIST_A2015.TXT
COTAHIST_A2016.TXT
COTAHIST_A2017.TXT
COTAHIST_A2018.TXT
COTAHIST_A2019.TXT
COTAHIST_A2020.TXT
COTAHIST_A2021.TXT
COTAHIST_A2022.TXT
COTAHIST_A2023.TXT
COTAHIST_A2024.TXT
COTAHIST_A2025.TXT
COTAHIST_A2026.TXT
Lendo: COTAHIST_A2008.TXT
   284,235 registros
Lendo: COTAHIST_A2009.TXT
   265,046 registros
Lendo: COTAHIST_A2010.TXT
   287,480 registros
Lendo: COTAHIST_A2011.TXT
   298,370 registros
Lendo: COTAHIST_A2012.TXT
   330,633 registros
Lendo: COTAHIST_A2013.TXT
   378,917 registros
Lendo: COTAHIST_A2014.TXT
   392,228 registros
Lendo: COTAHIST_A2015.TXT
   414,177 registros
Lendo: COTAHIST_A2016.TXT
   466,734 registros
Lendo: COTAHIST_A2017.TXT
   489,115 registros
Lendo: COTAHIST_A2018.TXT
   580,155 registros
Lendo: COTAHIST_A2019.TXT
   779,229 registros
Lendo: COTAHIST_A2020.TXT
   1,251,646 registros
Lendo: COTAHIST_A2021.TXT
   1,831,862 registros
Lendo: COTAHIST_A2022.TXT
   2,117,440 registros
Lendo: COTAHIST_A2023.TXT
   2,257,424 registros
Lendo: COTAHIST_A2024.TXT
   2,635,561 registros
Lendo: COTAHIST_A2025.TXT
   3,174,698 registros
Lendo: COTAHIST_A2026.TXT
   2,919,760 registros

==============================
DATAFRAME FINAL
==============================
Linhas: 21,154,710
Colunas: 27
Período: 2008-01-02 00:00:00 até 2026-09-23 00:00:00
Tickers únicos: 899,056

Arquivo salvo:
b3_cotahist_2008_2026.parquet

In [22]:
df_b3

,tipo_registro,data,cod_bdi,ticker,tipo_mercado,nome_empresa,especificacao,prazo_termo,moeda,preco_abertura,...,quantidade_negociada,volume_financeiro,preco_exercicio,indicador_correcao,data_vencimento,fator_cotacao,pontos_exercicio,isin,numero_distribuicao,ano_arquivo
0,01,2008-01-02,02,ABCB4,010,ABC BRASIL,PN EJ N2,NaN,R$,12.00,...,87000,1003110.00,0.0,0,99991231,1,0,BRABCBACNPR4,101,2008
1,01,2008-01-02,96,ABCB4F,020,ABC BRASIL,PN EJ N2,NaN,R$,12.00,...,10,120.00,0.0,0,99991231,1,0,BRABCBACNPR4,101,2008
2,01,2008-01-02,02,ABNB3,010,ABNOTE,ON ED NM,NaN,R$,16.85,...,37900,620126.00,0.0,0,99991231,1,0,BRABNBACNOR4,106,2008
3,01,2008-01-02,96,ABNB3F,020,ABNOTE,ON ED NM,NaN,R$,16.80,...,42,694.75,0.0,0,99991231,1,0,BRABNBACNOR4,106,2008
4,01,2008-01-02,62,ABNB3T,030,ABNOTE,ON ED NM,090,R$,16.77,...,300,5033.28,0.0,0,99991231,1,0,BRABNBACNOR4,106,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21154705,01,2026-09-23,34,Z2LL34,010,ZILLOW GROUP,DRN,NaN,R$,12.87,...,60,772.20,0.0,0,99991231,1,0,BRZ2LLBDR006,100,2026
21154706,01,2026-09-23,34,Z2SC34,010,ZSCALER INC,DRN,NaN,R$,36.57,...,82327,3037806.22,0.0,0,99991231,1,0,BRZ2SCBDR000,100,2026
21154707,01,2026-09-23,12,ZAGH11,010,FII ZAGH,CI,NaN,R$,8.58,...,1155,9919.29,0.0,0,99991231,1,0,BRZAGHCTF007,134,2026
21154708,01,2026-09-23,12,ZAVC11,010,FII ZAVIT C,CI,NaN,R$,9.19,...,633,5807.12,0.0,0,99991231,1,0,BRZAVCCTF007,130,2026
21154709,01,2026-09-23,12,ZAVI11,010,FII ZAVIT R,CI,NaN,R$,9.74,...,1510,14644.24,0.0,0,99991231,1,0,BRZAVICTF004,149,2026

In [23]:
df_b3.columns

Index(['tipo_registro', 'data', 'cod_bdi', 'ticker', 'tipo_mercado',
       'nome_empresa', 'especificacao', 'prazo_termo', 'moeda',
       'preco_abertura', 'preco_maximo', 'preco_minimo', 'preco_medio',
       'preco_ultimo', 'preco_oferta_compra', 'preco_oferta_venda',
       'numero_negocios', 'quantidade_negociada', 'volume_financeiro',
       'preco_exercicio', 'indicador_correcao', 'data_vencimento',
       'fator_cotacao', 'pontos_exercicio', 'isin', 'numero_distribuicao',
       'ano_arquivo'],
      dtype='object')

In [27]:
import pandas as pd

df_fca = pd.read_csv(
    "fre_cia_aberta_2010/fre_cia_aberta_capital_social_classe_acao_2010.csv",
    sep=";",
    encoding="latin1"
)

print(df_fca.columns.tolist())
print(df_fca.head())

['CNPJ_Companhia', 'Data_Referencia', 'Versao', 'ID_Documento', 'Nome_Companhia', 'ID_Capital_Social', 'Tipo_Classe_Acao_Preferencial', 'Quantidade_Acoes']
       CNPJ_Companhia Data_Referencia  Versao  ID_Documento  \
0  00.001.180/0001-26      2010-01-01      11          8288
1  00.001.180/0001-26      2010-01-01      11          8288
2  00.001.180/0001-26      2010-01-01      11          8288
3  00.001.180/0001-26      2010-01-01      11          8288
4  00.001.180/0001-26      2010-01-01      11          8288

                         Nome_Companhia  ID_Capital_Social  \
0  CENTRAIS ELET BRAS S.A. - ELETROBRAS              32933
1  CENTRAIS ELET BRAS S.A. - ELETROBRAS              32933
2  CENTRAIS ELET BRAS S.A. - ELETROBRAS              32934
3  CENTRAIS ELET BRAS S.A. - ELETROBRAS              32934
4  CENTRAIS ELET BRAS S.A. - ELETROBRAS              32935

  Tipo_Classe_Acao_Preferencial  Quantidade_Acoes
0         Preferencial Classe A            146920
1         Preferencial Classe B         265436883
2         Preferencial Classe A            146920
3         Preferencial Classe B         265436883
4         Preferencial Classe A            146920

In [29]:
print(df_fca.head(20).to_string())

        CNPJ_Companhia Data_Referencia  Versao  ID_Documento                          Nome_Companhia  ID_Capital_Social Tipo_Classe_Acao_Preferencial  Quantidade_Acoes
0   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32933         Preferencial Classe A            146920
1   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32933         Preferencial Classe B         265436883
2   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32934         Preferencial Classe A            146920
3   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32934         Preferencial Classe B         265436883
4   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32935         Preferencial Classe A            146920
5   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32935         Preferencial Classe B         265436883
6   00.070.698/0001-11      2010-01-01       8         11390  COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB              39882         Preferencial Classe A           1313002
7   00.070.698/0001-11      2010-01-01       8         11390  COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB              39882         Preferencial Classe B           3294024
8   00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32905         Preferencial Classe A            141058
9   00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32905         Preferencial Classe B                 2
10  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32906         Preferencial Classe A            141058
11  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32906         Preferencial Classe B                 2
12  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32907         Preferencial Classe A            141058
13  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32907         Preferencial Classe B                 2
14  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32908         Preferencial Classe A            141058
15  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32908         Preferencial Classe B                 2
16  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32909         Preferencial Classe A            141058
17  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32909         Preferencial Classe B                 2
18  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32910         Preferencial Classe B                 2
19  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32910         Preferencial Classe A            141058

In [30]:
print(df_fca["Tipo_Classe_Acao_Preferencial"].value_counts(dropna=False))

Tipo_Classe_Acao_Preferencial
Preferencial Classe A    203
Preferencial Classe B    131
Preferencial Classe C     23
Preferencial Classe D      6
Preferencial Classe E      5
Preferencial Classe U      2
Preferencial Classe R      1
Preferencial Classe F      1
Name: count, dtype: int64

In [31]:
print(
    df_fca[
        ["ID_Capital_Social",
         "Tipo_Classe_Acao_Preferencial",
         "Quantidade_Acoes"]
    ]
    .drop_duplicates()
    .head(50)
    .to_string(index=False)
)

 ID_Capital_Social Tipo_Classe_Acao_Preferencial  Quantidade_Acoes
             32933         Preferencial Classe A            146920
             32933         Preferencial Classe B         265436883
             32934         Preferencial Classe A            146920
             32934         Preferencial Classe B         265436883
             32935         Preferencial Classe A            146920
             32935         Preferencial Classe B         265436883
             39882         Preferencial Classe A           1313002
             39882         Preferencial Classe B           3294024
             32905         Preferencial Classe A            141058
             32905         Preferencial Classe B                 2
             32906         Preferencial Classe A            141058
             32906         Preferencial Classe B                 2
             32907         Preferencial Classe A            141058
             32907         Preferencial Classe B                 2
             32908         Preferencial Classe A            141058
             32908         Preferencial Classe B                 2
             32909         Preferencial Classe A            141058
             32909         Preferencial Classe B                 2
             32910         Preferencial Classe B                 2
             32910         Preferencial Classe A            141058
             32911         Preferencial Classe A            141058
             32911         Preferencial Classe B                 2
             32912         Preferencial Classe A            141058
             32912         Preferencial Classe B                 2
             28993         Preferencial Classe A      210029997060
             29277         Preferencial Classe A          16288514
             29277         Preferencial Classe B           5156240
             29277         Preferencial Classe C         107199382
             29277         Preferencial Classe R         255559826
             32901         Preferencial Classe A               730
             32901         Preferencial Classe B          28385274
             32901         Preferencial Classe C           7181502
             32902         Preferencial Classe A               730
             32902         Preferencial Classe B          28385274
             32902         Preferencial Classe C           7772020
             32903         Preferencial Classe A               730
             32903         Preferencial Classe B          28385274
             32903         Preferencial Classe C           7772020
                47         Preferencial Classe A         358809593
             33324         Preferencial Classe A             37680
             33325         Preferencial Classe A             37680
             33326         Preferencial Classe A             37680
             36190         Preferencial Classe B            255594
             36191         Preferencial Classe B            255594
             36192         Preferencial Classe B            255594
             31236         Preferencial Classe B             92333
             31237         Preferencial Classe B             92333
             31238         Preferencial Classe B             92333
             38314         Preferencial Classe A           7180658
             29490         Preferencial Classe A          82076174

In [33]:
df_social = pd.read_csv(
    "fre_cia_aberta_2010/fre_cia_aberta_capital_social_2010.csv",
    sep=";",
    encoding="latin1"
)

print(df_social.columns.tolist())
print(df_social.head(20).to_string())

['CNPJ_Companhia', 'Data_Referencia', 'Versao', 'ID_Documento', 'Nome_Companhia', 'ID_Capital_Social', 'Tipo_Capital', 'Data_Autorizacao_Aprovacao', 'Valor_Capital', 'Prazo_Integralizacao', 'Quantidade_Acoes_Ordinarias', 'Quantidade_Acoes_Preferenciais', 'Quantidade_Total_Acoes']
        CNPJ_Companhia Data_Referencia  Versao  ID_Documento                          Nome_Companhia  ID_Capital_Social           Tipo_Capital Data_Autorizacao_Aprovacao  Valor_Capital            Prazo_Integralizacao  Quantidade_Acoes_Ordinarias  Quantidade_Acoes_Preferenciais  Quantidade_Total_Acoes
0   00.000.000/0001-91      2010-01-01      11          9670                         BCO BRASIL S.A.              36654        Capital Emitido                 2010-04-13   3.307800e+10  Capital integralizado no total                   2860729247                               0              2860729247
1   00.000.000/0001-91      2010-01-01      11          9670                         BCO BRASIL S.A.              36655      Capital Subscrito                 2010-04-13   3.307800e+10                             NaN                   2860729247                               0              2860729247
2   00.000.000/0001-91      2010-01-01      11          9670                         BCO BRASIL S.A.              36656  Capital Integralizado                 2010-04-13   3.307800e+10                             NaN                   2860729247                               0              2860729247
3   00.000.208/0001-00      2010-01-01       3          7379              BRB BANCO DE BRASILIA S.A.              31813  Capital Integralizado                 2010-09-24   3.000000e+08                             NaN                     28014650                         8290000                36304650
4   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32933        Capital Emitido                 2011-03-16   3.130533e+10                             NaN                   1087050297                       265583803              1352634100
5   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32934      Capital Subscrito                 2011-03-16   3.130533e+10                  Não aplicável.                   1087050297                       265583803              1352634100
6   00.001.180/0001-26      2010-01-01      11          8288    CENTRAIS ELET BRAS S.A. - ELETROBRAS              32935  Capital Integralizado                 2011-03-16   3.130533e+10                             NaN                   1087050297                       265583803              1352634100
7   00.027.742/0001-00      2010-01-01       1          1941                   CBCC PARTICIPAÇÕES SA               1396  Capital Integralizado                 2001-04-09   1.230000e+07                             NaN                      5156592                               0                 5156592
8   00.070.698/0001-11      2010-01-01       8         11390  COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB              39882  Capital Integralizado                 2005-02-15   3.420562e+08                             NaN                      4576432                         4607026                 9183458
9   00.070.698/0001-11      2010-01-01       8         11390  COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB              39883     Capital Autorizado                 2005-02-15   3.687245e+08                             NaN                            0                               0                       0
10  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32905        Capital Emitido                 2010-08-16   6.981708e+08                      16/08/2010                      3901228                          141060                 4042288
11  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32906      Capital Subscrito                 2010-08-16   6.981708e+08                      16/08/2010                      3901228                          141060                 4042288
12  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32907  Capital Integralizado                 2010-08-16   6.569784e+08                             NaN                      3662731                          141060                 3803791
13  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32908     Capital Autorizado                 2010-08-16   6.981708e+08                             NaN                      3901228                          141060                 4042288
14  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32909        Capital Emitido                 2010-06-29   6.569784e+08                      29/06/2010                      3662731                          141060                 3803791
15  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32910      Capital Subscrito                 2010-06-29   6.569784e+08                      29/06/2010                      3662731                          141060                 3803791
16  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32911  Capital Integralizado                 2010-06-29   6.569784e+08                             NaN                      3662731                          141060                 3803791
17  00.095.147/0001-02      2010-01-01       3          8116                          VBC ENERGIA SA              32912     Capital Autorizado                 2010-06-29   6.569784e+08                      29/06/2010                      3662731                          141060                 3803791
18  00.108.786/0001-65      2010-01-01       7          4757        NET SERVIÇOS DE COMUNICAÇÃO S.A.              25164  Capital Integralizado                 2009-12-31   5.599320e+09                             NaN                    114459685                       228402413               342862098
19  00.108.786/0001-65      2010-01-01       7          4757        NET SERVIÇOS DE COMUNICAÇÃO S.A.              25165        Capital Emitido                 2009-02-10   5.612243e+09                             NaN                    114459685                       228503916               342963601

In [34]:
df_social["Data_Referencia"] = pd.to_datetime(
    df_social["Data_Referencia"]
)

df_social.head()

,CNPJ_Companhia,Data_Referencia,Versao,ID_Documento,Nome_Companhia,ID_Capital_Social,Tipo_Capital,Data_Autorizacao_Aprovacao,Valor_Capital,Prazo_Integralizacao,Quantidade_Acoes_Ordinarias,Quantidade_Acoes_Preferenciais,Quantidade_Total_Acoes
0,00.000.000/0001-91,2010-01-01,11,9670,BCO BRASIL S.A.,36654,Capital Emitido,2010-04-13,3.307800e+10,Capital integralizado no total,2860729247,0,2860729247
1,00.000.000/0001-91,2010-01-01,11,9670,BCO BRASIL S.A.,36655,Capital Subscrito,2010-04-13,3.307800e+10,NaN,2860729247,0,2860729247
2,00.000.000/0001-91,2010-01-01,11,9670,BCO BRASIL S.A.,36656,Capital Integralizado,2010-04-13,3.307800e+10,NaN,2860729247,0,2860729247
3,00.000.208/0001-00,2010-01-01,3,7379,BRB BANCO DE BRASILIA S.A.,31813,Capital Integralizado,2010-09-24,3.000000e+08,NaN,28014650,8290000,36304650
4,00.001.180/0001-26,2010-01-01,11,8288,CENTRAIS ELET BRAS S.A. - ELETROBRAS,32933,Capital Emitido,2011-03-16,3.130533e+10,NaN,1087050297,265583803,1352634100

In [36]:

print(df_social[
    [
        "Nome_Companhia",
        "Tipo_Capital",
        "Data_Referencia",
        "Quantidade_Acoes_Ordinarias",
        "Quantidade_Acoes_Preferenciais",
        "Quantidade_Total_Acoes"
    ]
].head(20).to_string(index=False))

                        Nome_Companhia          Tipo_Capital Data_Referencia  Quantidade_Acoes_Ordinarias  Quantidade_Acoes_Preferenciais  Quantidade_Total_Acoes
                       BCO BRASIL S.A.       Capital Emitido      2010-01-01                   2860729247                               0              2860729247
                       BCO BRASIL S.A.     Capital Subscrito      2010-01-01                   2860729247                               0              2860729247
                       BCO BRASIL S.A. Capital Integralizado      2010-01-01                   2860729247                               0              2860729247
            BRB BANCO DE BRASILIA S.A. Capital Integralizado      2010-01-01                     28014650                         8290000                36304650
  CENTRAIS ELET BRAS S.A. - ELETROBRAS       Capital Emitido      2010-01-01                   1087050297                       265583803              1352634100
  CENTRAIS ELET BRAS S.A. - ELETROBRAS     Capital Subscrito      2010-01-01                   1087050297                       265583803              1352634100
  CENTRAIS ELET BRAS S.A. - ELETROBRAS Capital Integralizado      2010-01-01                   1087050297                       265583803              1352634100
                 CBCC PARTICIPAÇÕES SA Capital Integralizado      2010-01-01                      5156592                               0                 5156592
COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB Capital Integralizado      2010-01-01                      4576432                         4607026                 9183458
COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB    Capital Autorizado      2010-01-01                            0                               0                       0
                        VBC ENERGIA SA       Capital Emitido      2010-01-01                      3901228                          141060                 4042288
                        VBC ENERGIA SA     Capital Subscrito      2010-01-01                      3901228                          141060                 4042288
                        VBC ENERGIA SA Capital Integralizado      2010-01-01                      3662731                          141060                 3803791
                        VBC ENERGIA SA    Capital Autorizado      2010-01-01                      3901228                          141060                 4042288
                        VBC ENERGIA SA       Capital Emitido      2010-01-01                      3662731                          141060                 3803791
                        VBC ENERGIA SA     Capital Subscrito      2010-01-01                      3662731                          141060                 3803791
                        VBC ENERGIA SA Capital Integralizado      2010-01-01                      3662731                          141060                 3803791
                        VBC ENERGIA SA    Capital Autorizado      2010-01-01                      3662731                          141060                 3803791
      NET SERVIÇOS DE COMUNICAÇÃO S.A. Capital Integralizado      2010-01-01                    114459685                       228402413               342862098
      NET SERVIÇOS DE COMUNICAÇÃO S.A.       Capital Emitido      2010-01-01                    114459685                       228503916               342963601

In [40]:
import pandas as pd
import os
import glob

# ============================================================
# 1. CONFIGURAÇÃO
# ============================================================

anos = range(2010, 2027)

arquivos = []

# ============================================================
# 2. ENCONTRAR SOMENTE OS ARQUIVOS DE CAPITAL SOCIAL
# ============================================================

for ano in anos:

    pasta = f"fre_cia_aberta_{ano}"

    padrao = os.path.join(
        pasta,
        f"fre_cia_aberta_capital_social_{ano}.csv"
    )

    encontrados = glob.glob(padrao)

    arquivos.extend(encontrados)

print(f"Total de arquivos encontrados: {len(arquivos)}")

for arquivo in arquivos:
    print(arquivo)


# ============================================================
# 3. FUNÇÃO PARA LER CSV COM DIFERENTES ENCODINGS
# ============================================================

def ler_csv_robusto(arquivo):

    encodings = [
        "utf-8",
        "latin1",
        "cp1252"
    ]

    separadores = [
        ";",
        ","
    ]

    ultimo_erro = None

    for encoding in encodings:

        for sep in separadores:

            try:

                df = pd.read_csv(
                    arquivo,
                    sep=sep,
                    encoding=encoding,
                    low_memory=False,
                    on_bad_lines="skip"
                )

                # Evita aceitar uma leitura claramente errada
                # (ex.: CSV separado por ; lido como uma única coluna)
                if len(df.columns) > 1:

                    print(
                        f"OK: {arquivo} | "
                        f"encoding={encoding} | "
                        f"sep='{sep}' | "
                        f"linhas={len(df)} | "
                        f"colunas={len(df.columns)}"
                    )

                    return df

            except Exception as e:

                ultimo_erro = e

    raise ValueError(
        f"Não foi possível ler o arquivo: {arquivo}\n"
        f"Último erro: {ultimo_erro}"
    )


# ============================================================
# 4. LER TODOS OS ARQUIVOS
# ============================================================

dfs = []

for arquivo in arquivos:

    try:

        df_temp = ler_csv_robusto(arquivo)

        # Guarda o ano de origem
        ano = os.path.basename(arquivo)[-8:-4]

        df_temp["ano_arquivo"] = int(ano)

        # Guarda o arquivo de origem
        df_temp["arquivo_origem"] = os.path.basename(arquivo)

        dfs.append(df_temp)

    except Exception as e:

        print(f"ERRO: {arquivo}")
        print(e)


# ============================================================
# 5. JUNTAR TODOS OS DATAFRAMES
# ============================================================

if dfs:

    df_capital_social = pd.concat(
        dfs,
        ignore_index=True,
        sort=False
    )

else:

    df_capital_social = pd.DataFrame()


# ============================================================
# 6. LIMPAR NOMES DAS COLUNAS
# ============================================================

df_capital_social.columns = (
    df_capital_social.columns
    .str.strip()
    .str.replace("\ufeff", "", regex=False)
)


# ============================================================
# 7. REMOVER ESPAÇOS DAS COLUNAS DE TEXTO
# ============================================================

for coluna in df_capital_social.select_dtypes(
    include="object"
).columns:

    df_capital_social[coluna] = (
        df_capital_social[coluna]
        .str.strip()
    )


# ============================================================
# 8. INFORMAÇÕES FINAIS
# ============================================================

print("\n===================================")
print("DATAFRAME FINAL")
print("===================================")

print("Shape:", df_capital_social.shape)

print("\nColunas:")
print(df_capital_social.columns.tolist())

print("\nPrimeiras linhas:")
display(df_capital_social.head())

print("\nQuantidade por ano:")
print(
    df_capital_social["ano_arquivo"]
    .value_counts()
    .sort_index()
)

Total de arquivos encontrados: 17
fre_cia_aberta_2010/fre_cia_aberta_capital_social_2010.csv
fre_cia_aberta_2011/fre_cia_aberta_capital_social_2011.csv
fre_cia_aberta_2012/fre_cia_aberta_capital_social_2012.csv
fre_cia_aberta_2013/fre_cia_aberta_capital_social_2013.csv
fre_cia_aberta_2014/fre_cia_aberta_capital_social_2014.csv
fre_cia_aberta_2015/fre_cia_aberta_capital_social_2015.csv
fre_cia_aberta_2016/fre_cia_aberta_capital_social_2016.csv
fre_cia_aberta_2017/fre_cia_aberta_capital_social_2017.csv
fre_cia_aberta_2018/fre_cia_aberta_capital_social_2018.csv
fre_cia_aberta_2019/fre_cia_aberta_capital_social_2019.csv
fre_cia_aberta_2020/fre_cia_aberta_capital_social_2020.csv
fre_cia_aberta_2021/fre_cia_aberta_capital_social_2021.csv
fre_cia_aberta_2022/fre_cia_aberta_capital_social_2022.csv
fre_cia_aberta_2023/fre_cia_aberta_capital_social_2023.csv
fre_cia_aberta_2024/fre_cia_aberta_capital_social_2024.csv
fre_cia_aberta_2025/fre_cia_aberta_capital_social_2025.csv
fre_cia_aberta_2026/fre_cia_aberta_capital_social_2026.csv
OK: fre_cia_aberta_2010/fre_cia_aberta_capital_social_2010.csv | encoding=latin1 | sep=';' | linhas=1746 | colunas=13
OK: fre_cia_aberta_2011/fre_cia_aberta_capital_social_2011.csv | encoding=latin1 | sep=';' | linhas=2091 | colunas=13
OK: fre_cia_aberta_2012/fre_cia_aberta_capital_social_2012.csv | encoding=latin1 | sep=';' | linhas=2422 | colunas=13
OK: fre_cia_aberta_2013/fre_cia_aberta_capital_social_2013.csv | encoding=latin1 | sep=';' | linhas=2616 | colunas=13
OK: fre_cia_aberta_2014/fre_cia_aberta_capital_social_2014.csv | encoding=latin1 | sep=';' | linhas=2561 | colunas=13
OK: fre_cia_aberta_2015/fre_cia_aberta_capital_social_2015.csv | encoding=latin1 | sep=';' | linhas=2450 | colunas=13
OK: fre_cia_aberta_2016/fre_cia_aberta_capital_social_2016.csv | encoding=latin1 | sep=';' | linhas=2699 | colunas=13
OK: fre_cia_aberta_2017/fre_cia_aberta_capital_social_2017.csv | encoding=latin1 | sep=';' | linhas=2872 | colunas=13
OK: fre_cia_aberta_2018/fre_cia_aberta_capital_social_2018.csv | encoding=latin1 | sep=';' | linhas=2995 | colunas=13
OK: fre_cia_aberta_2019/fre_cia_aberta_capital_social_2019.csv | encoding=latin1 | sep=';' | linhas=2988 | colunas=13
OK: fre_cia_aberta_2020/fre_cia_aberta_capital_social_2020.csv | encoding=latin1 | sep=';' | linhas=3222 | colunas=13
OK: fre_cia_aberta_2021/fre_cia_aberta_capital_social_2021.csv | encoding=latin1 | sep=';' | linhas=3606 | colunas=13
OK: fre_cia_aberta_2022/fre_cia_aberta_capital_social_2022.csv | encoding=latin1 | sep=';' | linhas=3775 | colunas=13
OK: fre_cia_aberta_2023/fre_cia_aberta_capital_social_2023.csv | encoding=latin1 | sep=';' | linhas=2492 | colunas=13
OK: fre_cia_aberta_2024/fre_cia_aberta_capital_social_2024.csv | encoding=latin1 | sep=';' | linhas=2496 | colunas=13
OK: fre_cia_aberta_2025/fre_cia_aberta_capital_social_2025.csv | encoding=latin1 | sep=';' | linhas=2402 | colunas=13
OK: fre_cia_aberta_2026/fre_cia_aberta_capital_social_2026.csv | encoding=latin1 | sep=';' | linhas=2225 | colunas=13

===================================
DATAFRAME FINAL
===================================
Shape: (45658, 15)

Colunas:
['CNPJ_Companhia', 'Data_Referencia', 'Versao', 'ID_Documento', 'Nome_Companhia', 'ID_Capital_Social', 'Tipo_Capital', 'Data_Autorizacao_Aprovacao', 'Valor_Capital', 'Prazo_Integralizacao', 'Quantidade_Acoes_Ordinarias', 'Quantidade_Acoes_Preferenciais', 'Quantidade_Total_Acoes', 'ano_arquivo', 'arquivo_origem']

Primeiras linhas:

,CNPJ_Companhia,Data_Referencia,Versao,ID_Documento,Nome_Companhia,ID_Capital_Social,Tipo_Capital,Data_Autorizacao_Aprovacao,Valor_Capital,Prazo_Integralizacao,Quantidade_Acoes_Ordinarias,Quantidade_Acoes_Preferenciais,Quantidade_Total_Acoes,ano_arquivo,arquivo_origem
0,00.000.000/0001-91,2010-01-01,11,9670,BCO BRASIL S.A.,36654,Capital Emitido,2010-04-13,3.307800e+10,Capital integralizado no total,2860729247,0,2860729247,2010,fre_cia_aberta_capital_social_2010.csv
1,00.000.000/0001-91,2010-01-01,11,9670,BCO BRASIL S.A.,36655,Capital Subscrito,2010-04-13,3.307800e+10,NaN,2860729247,0,2860729247,2010,fre_cia_aberta_capital_social_2010.csv
2,00.000.000/0001-91,2010-01-01,11,9670,BCO BRASIL S.A.,36656,Capital Integralizado,2010-04-13,3.307800e+10,NaN,2860729247,0,2860729247,2010,fre_cia_aberta_capital_social_2010.csv
3,00.000.208/0001-00,2010-01-01,3,7379,BRB BANCO DE BRASILIA S.A.,31813,Capital Integralizado,2010-09-24,3.000000e+08,NaN,28014650,8290000,36304650,2010,fre_cia_aberta_capital_social_2010.csv
4,00.001.180/0001-26,2010-01-01,11,8288,CENTRAIS ELET BRAS S.A. - ELETROBRAS,32933,Capital Emitido,2011-03-16,3.130533e+10,NaN,1087050297,265583803,1352634100,2010,fre_cia_aberta_capital_social_2010.csv

Quantidade por ano:
ano_arquivo
2010    1746
2011    2091
2012    2422
2013    2616
2014    2561
2015    2450
2016    2699
2017    2872
2018    2995
2019    2988
2020    3222
2021    3606
2022    3775
2023    2492
2024    2496
2025    2402
2026    2225
Name: count, dtype: int64

In [43]:
 import pandas as pd
import numpy as np
import requests
import io
import re
import unicodedata


# ============================================================
# 1. BAIXAR CADASTRO DA CVM
# ============================================================

url_cvm = (
    "https://dados.cvm.gov.br/"
    "dados/cia_aberta/CAD/DADOS/cad_cia_aberta.csv"
)

response = requests.get(url_cvm)

response.raise_for_status()

cad_cvm = pd.read_csv(
    io.BytesIO(response.content),
    sep=";",
    encoding="latin1",
    dtype=str
)

print("Cadastro CVM:")
print(cad_cvm.shape)
print(cad_cvm.columns.tolist())


# ============================================================
# 2. NORMALIZAR CNPJ
# ============================================================

def normalizar_cnpj(x):

    if pd.isna(x):
        return np.nan

    x = str(x)

    # Remove tudo que não for número
    x = re.sub(r"\D", "", x)

    if len(x) == 0:
        return np.nan

    # CNPJ deve ter 14 dígitos
    return x.zfill(14)


# CVM
cad_cvm["CNPJ"] = (
    cad_cvm["CNPJ_CIA"]
    .apply(normalizar_cnpj)
)


# Capital social
cs = df_capital_social.copy()

cs["CNPJ"] = (
    cs["CNPJ_Companhia"]
    .apply(normalizar_cnpj)
)


# ============================================================
# 3. PREPARAR CADASTRO CVM
# ============================================================

cad_cvm = cad_cvm[
    [
        "CNPJ",
        "DENOM_SOCIAL",
        "DENOM_COMERC",
        "SIT"
    ]
].copy()

cad_cvm = cad_cvm.drop_duplicates(
    subset=["CNPJ"]
)


# ============================================================
# 4. CRUZAR CAPITAL SOCIAL COM CVM
# ============================================================

cs = cs.merge(
    cad_cvm,
    on="CNPJ",
    how="left",
    suffixes=("", "_CVM")
)


print("\nCapital social após merge com CVM:")

print(
    cs[
        [
            "CNPJ",
            "Nome_Companhia",
            "DENOM_SOCIAL"
        ]
    ].head()
)


# ============================================================
# 5. CONVERTER DATA
# ============================================================

cs["Data_Referencia"] = pd.to_datetime(
    cs["Data_Referencia"],
    errors="coerce"
)

cs["mes"] = (
    cs["Data_Referencia"]
    .dt.to_period("M")
)


# ============================================================
# 6. QUANTIDADE DE AÇÕES
# ============================================================

cs["Quantidade_Total_Acoes"] = pd.to_numeric(
    cs["Quantidade_Total_Acoes"],
    errors="coerce"
)

cs["Quantidade_Acoes_Ordinarias"] = pd.to_numeric(
    cs["Quantidade_Acoes_Ordinarias"],
    errors="coerce"
)

cs["Quantidade_Acoes_Preferenciais"] = pd.to_numeric(
    cs["Quantidade_Acoes_Preferenciais"],
    errors="coerce"
)

cs = cs.dropna(
    subset=[
        "CNPJ",
        "mes",
        "Quantidade_Total_Acoes"
    ]
)


# ============================================================
# 7. PEGAR A INFORMAÇÃO MAIS RECENTE DO CAPITAL
#    DENTRO DE CADA MÊS
# ============================================================

cs = cs.sort_values(
    [
        "CNPJ",
        "mes",
        "Data_Referencia"
    ]
)


capital_mensal = (
    cs
    .groupby(
        [
            "CNPJ",
            "mes"
        ],
        as_index=False
    )
    .last()
)


# ============================================================
# 8. PREPARAR DF_B3
# ============================================================

b3 = df_b3.copy()

b3["data"] = pd.to_datetime(
    b3["data"],
    errors="coerce"
)

b3["ticker"] = (
    b3["ticker"]
    .astype(str)
    .str.strip()
    .str.upper()
)

b3["preco_ultimo"] = pd.to_numeric(
    b3["preco_ultimo"],
    errors="coerce"
)

b3 = b3.dropna(
    subset=[
        "data",
        "ticker",
        "preco_ultimo"
    ]
)


# ============================================================
# 9. MÊS DA COTAÇÃO
# ============================================================

b3["mes"] = (
    b3["data"]
    .dt.to_period("M")
)


# ============================================================
# 10. PEGAR ÚLTIMO PREÇO DE CADA TICKER/MÊS
# ============================================================

b3_mensal = (
    b3
    .sort_values(
        [
            "ticker",
            "data"
        ]
    )
    .groupby(
        [
            "ticker",
            "mes"
        ],
        as_index=False
    )
    .last()
)


# ============================================================
# 11. NORMALIZAR NOMES
# ============================================================

def normalizar_nome(x):

    if pd.isna(x):
        return ""

    x = str(x).upper().strip()

    # Remove acentos
    x = unicodedata.normalize(
        "NFKD",
        x
    )

    x = (
        x
        .encode("ASCII", "ignore")
        .decode("ASCII")
    )

    # Remove pontuação
    x = re.sub(
        r"[^A-Z0-9\s]",
        " ",
        x
    )

    # Remove espaços duplicados
    x = re.sub(
        r"\s+",
        " ",
        x
    )

    return x.strip()


# ============================================================
# 12. NOME DA EMPRESA NO CAPITAL SOCIAL
# ============================================================

cs["empresa_norm"] = (
    cs["Nome_Companhia"]
    .apply(normalizar_nome)
)


# ============================================================
# 13. NOME DA EMPRESA NA B3
# ============================================================

b3_mensal["empresa_norm"] = (
    b3_mensal["nome_empresa"]
    .apply(normalizar_nome)
)


# ============================================================
# 14. CRIAR MAPA EMPRESA → TICKER
# ============================================================

mapa_empresa_ticker = (
    b3_mensal[
        [
            "empresa_norm",
            "ticker",
            "isin"
        ]
    ]
    .drop_duplicates()
)


# ============================================================
# 15. CRUZAR CAPITAL SOCIAL COM TICKER
# ============================================================

cs_ticker = cs.merge(
    mapa_empresa_ticker,
    on="empresa_norm",
    how="left"
)


# ============================================================
# 16. CRUZAR COM PREÇOS MENSAIS
# ============================================================

df_market_cap = cs_ticker.merge(
    b3_mensal[
        [
            "ticker",
            "mes",
            "data",
            "preco_ultimo",
            "isin"
        ]
    ],
    on=[
        "ticker",
        "mes"
    ],
    how="left",
    suffixes=("", "_b3")
)


# ============================================================
# 17. CALCULAR MARKET CAP
# ============================================================

df_market_cap["market_cap"] = (
    df_market_cap["preco_ultimo"]
    *
    df_market_cap["Quantidade_Total_Acoes"]
)


# ============================================================
# 18. SELECIONAR COLUNAS FINAIS
# ============================================================

df_market_cap = df_market_cap[
    [
        "mes",
        "data",
        "ticker",
        "isin",
        "CNPJ",
        "Nome_Companhia",
        "DENOM_SOCIAL",
        "Quantidade_Total_Acoes",
        "preco_ultimo",
        "market_cap"
    ]
]


# ============================================================
# 19. ORDENAR
# ============================================================

df_market_cap = (
    df_market_cap
    .sort_values(
        [
            "mes",
            "ticker"
        ]
    )
    .reset_index(drop=True)
)


# ============================================================
# 20. RESULTADO
# ============================================================

print("\n========================================")
print("RESULTADO")
print("========================================")

print(
    "Shape:",
    df_market_cap.shape
)

print(
    "\nColunas:",
    df_market_cap.columns.tolist()
)

display(
    df_market_cap.head(20)
)

Cadastro CVM:
(2678, 47)
['CNPJ_CIA', 'DENOM_SOCIAL', 'DENOM_COMERC', 'DT_REG', 'DT_CONST', 'DT_CANCEL', 'MOTIVO_CANCEL', 'SIT', 'DT_INI_SIT', 'CD_CVM', 'SETOR_ATIV', 'TP_MERC', 'CATEG_REG', 'DT_INI_CATEG', 'SIT_EMISSOR', 'DT_INI_SIT_EMISSOR', 'CONTROLE_ACIONARIO', 'TP_ENDER', 'LOGRADOURO', 'COMPL', 'BAIRRO', 'MUN', 'UF', 'PAIS', 'CEP', 'DDD_TEL', 'TEL', 'DDD_FAX', 'FAX', 'EMAIL', 'TP_RESP', 'RESP', 'DT_INI_RESP', 'LOGRADOURO_RESP', 'COMPL_RESP', 'BAIRRO_RESP', 'MUN_RESP', 'UF_RESP', 'PAIS_RESP', 'CEP_RESP', 'DDD_TEL_RESP', 'TEL_RESP', 'DDD_FAX_RESP', 'FAX_RESP', 'EMAIL_RESP', 'CNPJ_AUDITOR', 'AUDITOR']

Capital social após merge com CVM:
             CNPJ                        Nome_Companhia  \
0  00000000000191                       BCO BRASIL S.A.
1  00000000000191                       BCO BRASIL S.A.
2  00000000000191                       BCO BRASIL S.A.
3  00000208000100            BRB BANCO DE BRASILIA S.A.
4  00001180000126  CENTRAIS ELET BRAS S.A. - ELETROBRAS

               DENOM_SOCIAL
0      BANCO DO BRASIL S.A.
1      BANCO DO BRASIL S.A.
2      BANCO DO BRASIL S.A.
3  BRB BANCO DE BRASILIA SA
4         AXIA ENERGIA S.A.

========================================
RESULTADO
========================================
Shape: (48822, 10)

Colunas: ['mes', 'data', 'ticker', 'isin', 'CNPJ', 'Nome_Companhia', 'DENOM_SOCIAL', 'Quantidade_Total_Acoes', 'preco_ultimo', 'market_cap']

,mes,data,ticker,isin,CNPJ,Nome_Companhia,DENOM_SOCIAL,Quantidade_Total_Acoes,preco_ultimo,market_cap
0,2010-01,2010-01-29,HGTX3,BRHGTXACNOR9,78876950000171,CIA HERING,CIA HERING,162722079,30.80,5.011840e+09
1,2010-01,2010-01-29,HGTX3,BRHGTXACNOR9,78876950000171,CIA HERING,CIA HERING,350000000,30.80,1.078000e+10
2,2010-01,2010-01-29,HGTX3F,BRHGTXACNOR9,78876950000171,CIA HERING,CIA HERING,162722079,29.21,4.753112e+09
3,2010-01,2010-01-29,HGTX3F,BRHGTXACNOR9,78876950000171,CIA HERING,CIA HERING,350000000,29.21,1.022350e+10
4,2010-01,NaT,HGTX3S,BRHGTXACNOR9,78876950000171,CIA HERING,CIA HERING,162722079,NaN,NaN
5,2010-01,NaT,HGTX3S,BRHGTXACNOR9,78876950000171,CIA HERING,CIA HERING,350000000,NaN,NaN
6,2010-01,2010-01-21,HGTX3T,BRHGTXACNOR9,78876950000171,CIA HERING,CIA HERING,162722079,33.45,5.443054e+09
7,2010-01,2010-01-21,HGTX3T,BRHGTXACNOR9,78876950000171,CIA HERING,CIA HERING,350000000,33.45,1.170750e+10
8,2010-01,NaT,IGTI11,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
9,2010-01,NaT,IGTI11,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
10,2010-01,NaT,IGTI11,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
11,2010-01,NaT,IGTI11,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,1460000000,NaN,NaN
12,2010-01,NaT,IGTI11F,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
13,2010-01,NaT,IGTI11F,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
14,2010-01,NaT,IGTI11F,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
15,2010-01,NaT,IGTI11F,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,1460000000,NaN,NaN
16,2010-01,NaT,IGTI11Q,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
17,2010-01,NaT,IGTI11Q,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
18,2010-01,NaT,IGTI11Q,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,963938751,NaN,NaN
19,2010-01,NaT,IGTI11Q,BRIGTICDAM16,60543816000193,IGUATEMI S.A.,IGUATEMI S.A.,1460000000,NaN,NaN

In [45]:
import pandas as pd
import numpy as np
import requests
import io
import re
import unicodedata

# ============================================================
# CONFIGURAÇÕES
# ============================================================

ANO_INICIAL = 2010
ANO_FINAL = 2026


# ============================================================
# 1. BAIXAR CADASTRO OFICIAL DA CVM
# ============================================================

url_cvm = (
    "https://dados.cvm.gov.br/dados/"
    "CIA_ABERTA/CAD/DADOS/cad_cia_aberta.csv"
)

response = requests.get(url_cvm, timeout=60)
response.raise_for_status()

cad_cvm = pd.read_csv(
    io.BytesIO(response.content),
    sep=";",
    encoding="latin1",
    dtype=str
)

print("Cadastro CVM carregado:", cad_cvm.shape)


# ============================================================
# 2. NORMALIZAR CNPJ
# ============================================================

def normalizar_cnpj(x):

    if pd.isna(x):
        return np.nan

    x = str(x)

    # remove . / -
    x = re.sub(r"\D", "", x)

    if len(x) == 14:
        return x

    return x.zfill(14)


cad_cvm["CNPJ"] = cad_cvm["CNPJ_CIA"].apply(normalizar_cnpj)

df_capital_social["CNPJ"] = (
    df_capital_social["CNPJ_Companhia"]
    .apply(normalizar_cnpj)
)


# ============================================================
# 3. NORMALIZAR DATAS
# ============================================================

df_capital_social["Data_Referencia"] = pd.to_datetime(
    df_capital_social["Data_Referencia"],
    errors="coerce"
)

df_capital_social["mes"] = (
    df_capital_social["Data_Referencia"]
    .dt.to_period("M")
)


# ============================================================
# 4. CONVERTER QUANTIDADES DE AÇÕES
# ============================================================

colunas_acoes = [
    "Quantidade_Acoes_Ordinarias",
    "Quantidade_Acoes_Preferenciais",
    "Quantidade_Total_Acoes"
]

for col in colunas_acoes:

    df_capital_social[col] = pd.to_numeric(
        df_capital_social[col],
        errors="coerce"
    )


# ============================================================
# 5. LIMPAR CAPITAL SOCIAL
# ============================================================

cs = df_capital_social[
    [
        "CNPJ",
        "Data_Referencia",
        "mes",
        "Nome_Companhia",
        "Tipo_Capital",
        "Quantidade_Acoes_Ordinarias",
        "Quantidade_Acoes_Preferenciais",
        "Quantidade_Total_Acoes"
    ]
].copy()

cs = cs.dropna(
    subset=[
        "CNPJ",
        "Data_Referencia"
    ]
)


# ============================================================
# 6. PEGAR O REGISTRO MAIS RECENTE DE CADA MÊS
# ============================================================

cs = cs.sort_values(
    [
        "CNPJ",
        "mes",
        "Data_Referencia"
    ]
)

cs = (
    cs
    .groupby(
        ["CNPJ", "mes"],
        as_index=False
    )
    .last()
)


# ============================================================
# 7. ADICIONAR NOME DA EMPRESA DA CVM
# ============================================================

cad_cvm_reduzido = cad_cvm[
    [
        "CNPJ",
        "DENOM_SOCIAL",
        "DENOM_COMERC"
    ]
].drop_duplicates(
    subset=["CNPJ"]
)

cs = cs.merge(
    cad_cvm_reduzido,
    on="CNPJ",
    how="left"
)


# ============================================================
# 8. FUNÇÃO PARA NORMALIZAR NOMES
# ============================================================

def normalizar_nome(nome):

    if pd.isna(nome):
        return ""

    nome = str(nome).upper()

    # remove acentos
    nome = unicodedata.normalize(
        "NFKD",
        nome
    )

    nome = "".join(
        c for c in nome
        if not unicodedata.combining(c)
    )

    # remove pontuação
    nome = re.sub(
        r"[^A-Z0-9 ]",
        " ",
        nome
    )

    # espaços múltiplos
    nome = re.sub(
        r"\s+",
        " ",
        nome
    )

    return nome.strip()


# ============================================================
# 9. PREPARAR B3
# ============================================================

b3 = df_b3.copy()

b3["data"] = pd.to_datetime(
    b3["data"],
    errors="coerce"
)

b3["mes"] = (
    b3["data"]
    .dt.to_period("M")
)

b3["preco_ultimo"] = pd.to_numeric(
    b3["preco_ultimo"],
    errors="coerce"
)

b3["quantidade_negociada"] = pd.to_numeric(
    b3["quantidade_negociada"],
    errors="coerce"
)

b3["volume_financeiro"] = pd.to_numeric(
    b3["volume_financeiro"],
    errors="coerce"
)

b3["ticker"] = (
    b3["ticker"]
    .astype(str)
    .str.upper()
    .str.strip()
)

b3["nome_empresa_norm"] = (
    b3["nome_empresa"]
    .apply(normalizar_nome)
)


# ============================================================
# 10. IDENTIFICAR ON / PN NA B3
# ============================================================

b3["especificacao_norm"] = (
    b3["especificacao"]
    .fillna("")
    .astype(str)
    .str.upper()
    .str.strip()
)


def identificar_tipo_acao(x):

    x = str(x)

    # PN antes de ON para evitar problemas
    if "PN" in x:
        return "PN"

    if "ON" in x:
        return "ON"

    return np.nan


b3["tipo_acao"] = (
    b3["especificacao_norm"]
    .apply(identificar_tipo_acao)
)


# ============================================================
# 11. FILTRAR SOMENTE ON / PN
# ============================================================

b3_acoes = b3[
    b3["tipo_acao"].isin(["ON", "PN"])
].copy()


# ============================================================
# 12. PEGAR ÚLTIMA COTAÇÃO DO MÊS
# ============================================================

b3_acoes = b3_acoes.sort_values(
    [
        "ticker",
        "data"
    ]
)

b3_mensal = (
    b3_acoes
    .groupby(
        ["ticker", "mes"],
        as_index=False
    )
    .last()
)


# ============================================================
# 13. CRIAR MAPA EMPRESA → TICKER
# ============================================================

mapa_b3 = (
    b3_mensal[
        [
            "ticker",
            "nome_empresa_norm",
            "tipo_acao",
            "isin"
        ]
    ]
    .copy()
)

# IMPORTANTE:
# deixar o nome da empresa com o mesmo nome usado no mapa CVM
mapa_b3 = mapa_b3.rename(
    columns={
        "nome_empresa_norm": "nome_b3"
    }
)

mapa_b3 = mapa_b3[
    mapa_b3["nome_b3"].notna()
    &
    (mapa_b3["nome_b3"] != "")
].drop_duplicates()


# ============================================================
# 14. NORMALIZAR NOMES NO CAPITAL SOCIAL
# ============================================================

cs["nome_empresa_norm"] = (
    cs["Nome_Companhia"]
    .apply(normalizar_nome)
)

cs["denom_social_norm"] = (
    cs["DENOM_SOCIAL"]
    .apply(normalizar_nome)
)

cs["denom_comerc_norm"] = (
    cs["DENOM_COMERC"]
    .apply(normalizar_nome)
)


# ============================================================
# 15. CRIAR MAPA CVM → NOME DA EMPRESA
# ============================================================

mapa_nome = pd.concat(
    [
        cs[
            [
                "CNPJ",
                "nome_empresa_norm"
            ]
        ].rename(
            columns={
                "nome_empresa_norm": "nome_b3"
            }
        ),

        cs[
            [
                "CNPJ",
                "denom_social_norm"
            ]
        ].rename(
            columns={
                "denom_social_norm": "nome_b3"
            }
        ),

        cs[
            [
                "CNPJ",
                "denom_comerc_norm"
            ]
        ].rename(
            columns={
                "denom_comerc_norm": "nome_b3"
            }
        )
    ],
    ignore_index=True
)

mapa_nome = mapa_nome[
    mapa_nome["nome_b3"].notna()
    &
    (mapa_nome["nome_b3"] != "")
].drop_duplicates()


# ============================================================
# 16. CRUZAR EMPRESA CVM COM TICKER B3
# ============================================================

mapa_ticker = mapa_nome.merge(
    mapa_b3,
    on="nome_b3",
    how="inner"
)

mapa_ticker = mapa_ticker[
    [
        "CNPJ",
        "ticker",
        "tipo_acao",
        "isin"
    ]
].drop_duplicates()


print("Empresas CVM:", mapa_nome["CNPJ"].nunique())
print("Tickers B3:", mapa_b3["ticker"].nunique())
print("Mapeamentos encontrados:", mapa_ticker.shape[0])


# ============================================================
# 17. CRUZAR CAPITAL SOCIAL COM TICKER
# ============================================================

cs_ticker = cs.merge(
    mapa_ticker,
    on="CNPJ",
    how="inner"
)


# ============================================================
# 18. SELECIONAR QUANTIDADE DE AÇÕES
#     DE ACORDO COM ON / PN
# ============================================================

cs_ticker["Quantidade_Acoes"] = np.where(
    cs_ticker["tipo_acao"] == "ON",
    cs_ticker["Quantidade_Acoes_Ordinarias"],
    np.where(
        cs_ticker["tipo_acao"] == "PN",
        cs_ticker["Quantidade_Acoes_Preferenciais"],
        np.nan
    )
)


# ============================================================
# 19. REMOVER QUANTIDADES INVÁLIDAS
# ============================================================

cs_ticker = cs_ticker[
    cs_ticker["Quantidade_Acoes"] > 0
].copy()


# ============================================================
# 20. CRUZAR COM PREÇO B3
# ============================================================

precos = b3_mensal[
    [
        "ticker",
        "mes",
        "data",
        "preco_ultimo",
        "isin",
        "numero_negocios",
        "quantidade_negociada",
        "volume_financeiro"
    ]
].copy()


df_market_cap = cs_ticker.merge(
    precos,
    on=[
        "ticker",
        "mes"
    ],
    how="inner",
    suffixes=(
        "_capital",
        "_b3"
    )
)


# ============================================================
# 21. CALCULAR MARKET CAP
# ============================================================

df_market_cap["market_cap"] = (
    df_market_cap["preco_ultimo"]
    *
    df_market_cap["Quantidade_Acoes"]
)


# ============================================================
# 22. LIMPAR RESULTADO
# ============================================================

df_market_cap = df_market_cap[
    [
        "mes",
        "data",
        "ticker",
        "tipo_acao",
        "isin_b3",
        "CNPJ",
        "Nome_Companhia",
        "DENOM_SOCIAL",
        "Quantidade_Acoes",
        "Quantidade_Acoes_Ordinarias",
        "Quantidade_Acoes_Preferenciais",
        "Quantidade_Total_Acoes",
        "preco_ultimo",
        "market_cap",
        "numero_negocios",
        "quantidade_negociada",
        "volume_financeiro"
    ]
].copy()


# ============================================================
# 23. ORGANIZAR
# ============================================================

df_market_cap = df_market_cap.sort_values(
    [
        "mes",
        "ticker"
    ]
).reset_index(drop=True)


# ============================================================
# 24. GARANTIR PERÍODO DO BACKTEST
# ============================================================

df_market_cap = df_market_cap[
    (
        df_market_cap["mes"]
        >= pd.Period(
            f"{ANO_INICIAL}-01",
            freq="M"
        )
    )
    &
    (
        df_market_cap["mes"]
        <= pd.Period(
            f"{ANO_FINAL}-12",
            freq="M"
        )
    )
].copy()


# ============================================================
# 25. RESULTADO
# ============================================================

print(
    "Shape final:",
    df_market_cap.shape
)

print(
    "\nPeríodo:",
    df_market_cap["mes"].min(),
    "até",
    df_market_cap["mes"].max()
)

print(
    "\nTickers:",
    df_market_cap["ticker"].nunique()
)

print(
    "\nExemplo:"
)

print(
    df_market_cap.head(20)
)

Cadastro CVM carregado: (2678, 47)
Empresas CVM: 1230
Tickers B3: 806006
Mapeamentos encontrados: 13817
Shape final: (8687, 17)

Período: 2010-01 até 2025-12

Tickers: 3071

Exemplo:
        mes       data  ticker tipo_acao       isin_b3            CNPJ  \
0   2010-01 2010-01-29   AELP3        ON  BRAELPACNOR2  01917705000130
1   2010-01 2010-01-29  AELP3F        ON  BRAELPACNOR2  01917705000130
2   2010-01 2010-01-28  AELP3T        ON  BRAELPACNOR2  01917705000130
3   2010-01 2010-01-28   ALPA3        ON  BRALPAACNOR0  61079117000105
4   2010-01 2010-01-27  ALPA3F        ON  BRALPAACNOR0  61079117000105
5   2010-01 2010-01-29   ALPA4        PN  BRALPAACNPR7  61079117000105
6   2010-01 2010-01-29  ALPA4F        PN  BRALPAACNPR7  61079117000105
7   2010-01 2010-01-26  ALPA4T        PN  BRALPAACNPR7  61079117000105
8   2010-01 2010-01-29   ALSC3        ON  BRALSCACNOR0  06082980000103
9   2010-01 2010-01-29  ALSC3F        ON  BRALSCACNOR0  06082980000103
10  2010-01 2010-01-29   AMBV3        ON  BRAMBVACNOR4  02808708000107
11  2010-01 2010-01-29  AMBV3F        ON  BRAMBVACNOR4  02808708000107
12  2010-01 2010-01-11  AMBV3T        ON  BRAMBVACNOR4  02808708000107
13  2010-01 2010-01-29   AMBV4        PN  BRAMBVACNPR1  02808708000107
14  2010-01 2010-01-29  AMBV4F        PN  BRAMBVACNPR1  02808708000107
15  2010-01 2010-01-29  AMBV4T        PN  BRAMBVACNPR1  02808708000107
16  2010-01 2010-01-15   AMCE3        ON  BRAMCEACNOR8  01685903000116
17  2010-01 2010-01-22  AMCE3F        ON  BRAMCEACNOR8  01685903000116
18  2010-01 2010-01-27   BALM3        ON  BRBALMACNOR5  61374161000130
19  2010-01 2010-01-18  BALM3F        ON  BRBALMACNOR5  61374161000130

                             Nome_Companhia  \
0                             AES ELPA S.A.
1                             AES ELPA S.A.
2                             AES ELPA S.A.
3                           ALPARGATAS S.A.
4                           ALPARGATAS S.A.
5                           ALPARGATAS S.A.
6                           ALPARGATAS S.A.
7                           ALPARGATAS S.A.
8            ALIANSCE SHOPPING CENTERS S.A.
9            ALIANSCE SHOPPING CENTERS S.A.
10  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV
11  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV
12  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV
13  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV
14  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV
15  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV
16                              AMERICEL SA
17                              AMERICEL SA
18                              BAUMER S.A.
19                              BAUMER S.A.

                               DENOM_SOCIAL  Quantidade_Acoes  \
0                               AES ELPA SA      9.506105e+07
1                               AES ELPA SA      9.506105e+07
2                               AES ELPA SA      9.506105e+07
3                             ALPARGATAS SA      1.815241e+08
4                             ALPARGATAS SA      1.815241e+08
5                             ALPARGATAS SA      1.719318e+08
6                             ALPARGATAS SA      1.719318e+08
7                             ALPARGATAS SA      1.719318e+08
8             ALIANSCE SHOPPING CENTERS S/A      1.374672e+08
9             ALIANSCE SHOPPING CENTERS S/A      1.374672e+08
10  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV      1.743889e+09
11  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV      1.743889e+09
12  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV      1.743889e+09
13  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV      1.360921e+09
14  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV      1.360921e+09
15  COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV      1.360921e+09
16                              AMERICEL SA      2.105400e+10
17                              AMERICEL SA      2.105400e+10
18                                BAUMER SA      4.900000e+05
19                                BAUMER SA      4.900000e+05

    Quantidade_Acoes_Ordinarias  Quantidade_Acoes_Preferenciais  \
0                      95061053                               0
1                      95061053                               0
2                      95061053                               0
3                     181524080                       171931800
4                     181524080                       171931800
5                     181524080                       171931800
6                     181524080                       171931800
7                     181524080                       171931800
8                     137467170                               0
9                     137467170                               0
10                   1743888690                      1360920737
11                   1743888690                      1360920737
12                   1743888690                      1360920737
13                   1743888690                      1360920737
14                   1743888690                      1360920737
15                   1743888690                      1360920737
16                  21054003010                       310071038
17                  21054003010                       310071038
18                       490000                          490000
19                       490000                          490000

    Quantidade_Total_Acoes  preco_ultimo    market_cap  numero_negocios  \
0                 95061053         46.50  4.420339e+09                1
1                 95061053         45.98  4.370907e+09                1
2                 95061053         46.96  4.464067e+09                4
3                353455880        130.99  2.377784e+10                3
4                353455880        125.00  2.269051e+10                1
5                353455880        121.60  2.090691e+10               26
6                353455880        121.50  2.088971e+10                1
7                353455880        122.31  2.102898e+10                2
8                137467170          8.77  1.205587e+09             1262
9                137467170          8.71  1.197339e+09              772
10              3104809427        150.00  2.615833e+11              212
11              3104809427        149.50  2.607114e+11               15
12              3104809427        157.08  2.739300e+11                2
13              3104809427        173.00  2.354393e+11             1398
14              3104809427        176.00  2.395220e+11               72
15              3104809427        175.68  2.390866e+11                6
16             21364074048         14.01  2.949666e+11                2
17             21364074048         14.00  2.947560e+11                1
18                  980000         39.97  1.958530e+07                1
19                  980000         40.00  1.960000e+07                1

    quantidade_negociada  volume_financeiro
0                    300           13950.00
1                     20             919.60
2                  20000          939075.16
3                   4200          550458.00
4                      2             250.00
5                  11100         1346131.00
6                      2             243.00
7                    100           12230.04
8                2924200        25689719.00
9                  21248          185016.79
10                 59100         8920276.00
11                   295           44819.64
12                   200           31415.40
13                301000        52641156.00
14                  1462          256807.42
15                  1000          175934.49
16                   200            2901.00
17                    54             756.00
18                   100            3997.00
19                     1              40.00

In [47]:
import pandas as pd
import numpy as np
import re
import unicodedata


# ============================================================
# CONFIGURAÇÕES
# ============================================================

ANO_INICIAL = 2010
ANO_FINAL = 2026


# ============================================================
# 1. FUNÇÃO DE NORMALIZAÇÃO DE NOME
# ============================================================

def normalizar_nome(x):

    if pd.isna(x):
        return ""

    x = str(x).upper().strip()

    x = unicodedata.normalize("NFKD", x)

    x = "".join(
        c for c in x
        if not unicodedata.combining(c)
    )

    x = re.sub(
        r"[^A-Z0-9 ]",
        " ",
        x
    )

    x = re.sub(
        r"\s+",
        " ",
        x
    )

    return x.strip()


# ============================================================
# 2. PREPARAR CAPITAL SOCIAL
# ============================================================

cs = df_capital_social.copy()


# CNPJ
cs["CNPJ"] = (
    cs["CNPJ_Companhia"]
    .astype(str)
    .str.replace(r"\D", "", regex=True)
    .str.zfill(14)
)


# Data
cs["Data_Referencia"] = pd.to_datetime(
    cs["Data_Referencia"],
    errors="coerce"
)

cs["mes"] = (
    cs["Data_Referencia"]
    .dt.to_period("M")
)


# Quantidades
colunas_acoes = [
    "Quantidade_Acoes_Ordinarias",
    "Quantidade_Acoes_Preferenciais",
    "Quantidade_Total_Acoes"
]

for col in colunas_acoes:

    cs[col] = pd.to_numeric(
        cs[col],
        errors="coerce"
    )


# Remover registros inválidos
cs = cs.dropna(
    subset=[
        "CNPJ",
        "Data_Referencia",
        "mes"
    ]
)


# ============================================================
# 3. PEGAR ÚLTIMO REGISTRO DE CAPITAL DE CADA MÊS
# ============================================================

cs = cs.sort_values(
    [
        "CNPJ",
        "mes",
        "Data_Referencia"
    ]
)

cs = (
    cs
    .groupby(
        ["CNPJ", "mes"],
        as_index=False
    )
    .last()
)


# ============================================================
# 4. PREPARAR B3
# ============================================================

b3 = df_b3.copy()


b3["data"] = pd.to_datetime(
    b3["data"],
    errors="coerce"
)

b3["mes"] = (
    b3["data"]
    .dt.to_period("M")
)


b3["ticker"] = (
    b3["ticker"]
    .astype(str)
    .str.upper()
    .str.strip()
)


b3["preco_ultimo"] = pd.to_numeric(
    b3["preco_ultimo"],
    errors="coerce"
)

b3["volume_financeiro"] = pd.to_numeric(
    b3["volume_financeiro"],
    errors="coerce"
)

b3["numero_negocios"] = pd.to_numeric(
    b3["numero_negocios"],
    errors="coerce"
)

b3["quantidade_negociada"] = pd.to_numeric(
    b3["quantidade_negociada"],
    errors="coerce"
)


# ============================================================
# 5. FILTRAR MERCADO À VISTA
# ============================================================

b3["tipo_mercado"] = (
    b3["tipo_mercado"]
    .astype(str)
    .str.strip()
)


b3 = b3[
    b3["tipo_mercado"] == "010"
].copy()


# ============================================================
# 6. FILTRAR SOMENTE AÇÕES
# ============================================================

# 3 = ON
# 4 = PN
# 5-8 = classes de PN

b3 = b3[
    b3["ticker"].str.contains(
        r"[345678]$",
        regex=True,
        na=False
    )
].copy()


# ============================================================
# 7. IDENTIFICAR ON / PN
# ============================================================

def identificar_tipo_acao(ticker):

    ultimo = str(ticker)[-1]

    if ultimo == "3":
        return "ON"

    if ultimo in ["4", "5", "6", "7", "8"]:
        return "PN"

    return np.nan


b3["tipo_acao"] = (
    b3["ticker"]
    .apply(identificar_tipo_acao)
)


# ============================================================
# 8. REMOVER PREÇOS INVÁLIDOS
# ============================================================

b3 = b3[
    b3["preco_ultimo"].notna()
    &
    (b3["preco_ultimo"] > 0)
].copy()


# ============================================================
# 9. PREÇO DE FIM DE MÊS
# ============================================================

b3 = b3.sort_values(
    [
        "ticker",
        "data"
    ]
)


preco_mensal = (
    b3
    .groupby(
        ["ticker", "mes"],
        as_index=False
    )
    .last()
)


preco_mensal = preco_mensal[
    [
        "ticker",
        "mes",
        "data",
        "preco_ultimo",
        "isin",
        "tipo_acao"
    ]
].copy()


# ============================================================
# 10. LIQUIDEZ MENSAL
# ============================================================

liquidez_mensal = (
    b3
    .groupby(
        ["ticker", "mes"],
        as_index=False
    )
    .agg(

        volume_financeiro=(
            "volume_financeiro",
            "sum"
        ),

        volume_financeiro_medio=(
            "volume_financeiro",
            "mean"
        ),

        numero_negocios=(
            "numero_negocios",
            "sum"
        ),

        quantidade_negociada=(
            "quantidade_negociada",
            "sum"
        ),

        dias_negociados=(
            "data",
            "nunique"
        )
    )
)


# ============================================================
# 11. CRUZAR PREÇO + LIQUIDEZ
# ============================================================

universo = preco_mensal.merge(
    liquidez_mensal,
    on=[
        "ticker",
        "mes"
    ],
    how="left"
)


# ============================================================
# 12. PREPARAR NOMES PARA O MATCH CVM × B3
# ============================================================

cs["nome_companhia_norm"] = (
    cs["Nome_Companhia"]
    .apply(normalizar_nome)
)


# Cadastro CVM
cadastro_nomes = cs[
    [
        "CNPJ",
        "nome_companhia_norm"
    ]
].copy()


cadastro_nomes = cadastro_nomes.rename(
    columns={
        "nome_companhia_norm": "nome_b3"
    }
)


# ============================================================
# 13. NOMES DA B3
# ============================================================

b3["nome_empresa_norm"] = (
    b3["nome_empresa"]
    .apply(normalizar_nome)
)


mapa_b3 = b3[
    [
        "ticker",
        "nome_empresa_norm",
        "tipo_acao",
        "isin"
    ]
].copy()


mapa_b3 = mapa_b3.rename(
    columns={
        "nome_empresa_norm": "nome_b3"
    }
)


mapa_b3 = mapa_b3[
    mapa_b3["nome_b3"] != ""
].drop_duplicates()


# ============================================================
# 14. MAPEAR CNPJ → TICKER
# ============================================================

mapa_ticker = cadastro_nomes.merge(
    mapa_b3,
    on="nome_b3",
    how="inner"
)


mapa_ticker = mapa_ticker[
    [
        "CNPJ",
        "ticker",
        "tipo_acao",
        "isin"
    ]
].drop_duplicates()


# ============================================================
# 15. CRUZAR CAPITAL SOCIAL COM TICKER
# ============================================================

capital_ticker = cs.merge(
    mapa_ticker,
    on="CNPJ",
    how="inner",
    suffixes=(
        "_capital",
        "_b3"
    )
)


# ============================================================
# 16. ESCOLHER QUANTIDADE DA ESPÉCIE
# ============================================================

capital_ticker["Quantidade_Acoes"] = np.where(

    capital_ticker["tipo_acao"] == "ON",

    capital_ticker[
        "Quantidade_Acoes_Ordinarias"
    ],

    np.where(

        capital_ticker["tipo_acao"] == "PN",

        capital_ticker[
            "Quantidade_Acoes_Preferenciais"
        ],

        np.nan
    )
)


# ============================================================
# 17. REMOVER QUANTIDADES INVÁLIDAS
# ============================================================

capital_ticker = capital_ticker[
    capital_ticker["Quantidade_Acoes"].notna()
    &
    (
        capital_ticker["Quantidade_Acoes"] > 0
    )
].copy()


# ============================================================
# 18. EVITAR DUPLICIDADE CNPJ/TICKER/MÊS
# ============================================================

capital_ticker = (
    capital_ticker
    .sort_values(
        [
            "CNPJ",
            "ticker",
            "mes",
            "Data_Referencia"
        ]
    )
    .drop_duplicates(
        subset=[
            "CNPJ",
            "ticker",
            "mes"
        ],
        keep="last"
    )
)


# ============================================================
# 19. CRUZAR COM PREÇO
# ============================================================

df_universo = capital_ticker.merge(
    universo,
    on=[
        "ticker",
        "mes"
    ],
    how="inner",
    suffixes=(
        "_capital",
        ""
    )
)


# ============================================================
# 20. MARKET CAP
# ============================================================

df_universo["market_cap"] = (
    df_universo["Quantidade_Acoes"]
    *
    df_universo["preco_ultimo"]
)


# ============================================================
# 21. ORGANIZAR POR TICKER/MÊS
# ============================================================

df_universo = df_universo.sort_values(
    [
        "ticker",
        "mes"
    ]
).reset_index(drop=True)


# ============================================================
# 22. PREÇO 12 MESES ATRÁS
# ============================================================

df_universo["preco_12m_atras"] = (
    df_universo
    .groupby("ticker")["preco_ultimo"]
    .shift(12)
)


# ============================================================
# 23. RETORNO 12 MESES
# ============================================================

df_universo["retorno_12m"] = (
    df_universo["preco_ultimo"]
    /
    df_universo["preco_12m_atras"]
    - 1
)


# ============================================================
# 24. MOMENTUM RANK
# ============================================================

df_universo["momentum_rank"] = (
    df_universo
    .groupby("mes")["retorno_12m"]
    .rank(
        ascending=False,
        method="first"
    )
)


# ============================================================
# 25. MOMENTUM PERCENTILE
# ============================================================

df_universo["momentum_percentile"] = (
    df_universo
    .groupby("mes")["retorno_12m"]
    .rank(
        ascending=True,
        pct=True
    )
)


# ============================================================
# 26. RANK MARKET CAP
# ============================================================

df_universo["market_cap_rank"] = (
    df_universo
    .groupby("mes")["market_cap"]
    .rank(
        ascending=False,
        method="first"
    )
)


# ============================================================
# 27. RANK LIQUIDEZ
# ============================================================

df_universo["liquidez_rank"] = (
    df_universo
    .groupby("mes")["volume_financeiro_medio"]
    .rank(
        ascending=False,
        method="first"
    )
)


# ============================================================
# 28. FILTRAR PERÍODO
# ============================================================

df_universo = df_universo[
    (
        df_universo["mes"]
        >= pd.Period(
            f"{ANO_INICIAL}-01",
            freq="M"
        )
    )
    &
    (
        df_universo["mes"]
        <= pd.Period(
            f"{ANO_FINAL}-12",
            freq="M"
        )
    )
].copy()


# ============================================================
# 29. EXIGIR 12 MESES DE HISTÓRICO
# ============================================================

df_universo = df_universo[
    df_universo["retorno_12m"].notna()
].copy()


# ============================================================
# 30. SELECIONAR COLUNAS FINAIS
# ============================================================

colunas_finais = [
    "mes",
    "data",
    "ticker",
    "tipo_acao",
    "isin",

    "CNPJ",
    "Nome_Companhia",

    "Quantidade_Acoes",
    "Quantidade_Acoes_Ordinarias",
    "Quantidade_Acoes_Preferenciais",
    "Quantidade_Total_Acoes",

    "preco_ultimo",
    "preco_12m_atras",

    "market_cap",

    "volume_financeiro",
    "volume_financeiro_medio",

    "numero_negocios",
    "quantidade_negociada",
    "dias_negociados",

    "retorno_12m",

    "momentum_rank",
    "momentum_percentile",

    "market_cap_rank",
    "liquidez_rank"
]


# só manter as que realmente existem
colunas_finais = [
    c for c in colunas_finais
    if c in df_universo.columns
]


df_universo = df_universo[
    colunas_finais
].copy()


# ============================================================
# 31. ORDENAR
# ============================================================

df_universo = df_universo.sort_values(
    [
        "mes",
        "momentum_rank"
    ]
).reset_index(drop=True)


# ============================================================
# 32. DIAGNÓSTICO
# ============================================================

print("=" * 60)
print("DF UNIVERSO")
print("=" * 60)

print(
    "Shape:",
    df_universo.shape
)

print(
    "Período:",
    df_universo["mes"].min(),
    "até",
    df_universo["mes"].max()
)

print(
    "Tickers únicos:",
    df_universo["ticker"].nunique()
)

print(
    "Empresas únicas:",
    df_universo["CNPJ"].nunique()
)

print("\nTipos de ação:")
print(
    df_universo["tipo_acao"]
    .value_counts()
)

print("\nExemplo:")
print(
    df_universo.head(20)
)

============================================================
DF UNIVERSO
============================================================
Shape: (8, 24)
Período: 2022-01 até 2025-12
Tickers únicos: 2
Empresas únicas: 1

Tipos de ação:
tipo_acao
PN    4
ON    4
Name: count, dtype: int64

Exemplo:
       mes       data ticker tipo_acao          isin            CNPJ  \
0  2022-01 2022-01-31  KLBN4        PN  BRKLBNACNPR9  89637490000145
1  2022-01 2022-01-31  KLBN3        ON  BRKLBNACNOR2  89637490000145
2  2023-12 2023-12-28  KLBN4        PN  BRKLBNACNPR9  89637490000145
3  2023-12 2023-12-28  KLBN3        ON  BRKLBNACNOR2  89637490000145
4  2024-12 2024-12-30  KLBN3        ON  BRKLBNACNOR2  89637490000145
5  2024-12 2024-12-30  KLBN4        PN  BRKLBNACNPR9  89637490000145
6  2025-12 2025-12-30  KLBN3        ON  BRKLBNACNOR2  89637490000145
7  2025-12 2025-12-30  KLBN4        PN  BRKLBNACNPR9  89637490000145

  Nome_Companhia  Quantidade_Acoes  Quantidade_Acoes_Ordinarias  \
0    KLABIN S.A.      3.536164e+09                   2081728595
1    KLABIN S.A.      2.081729e+09                   2081728595
2    KLABIN S.A.      3.889781e+09                   2289901455
3    KLABIN S.A.      2.289901e+09                   2289901455
4    KLABIN S.A.      2.289901e+09                   2289901455
5    KLABIN S.A.      3.889781e+09                   2289901455
6    KLABIN S.A.      3.200000e+09                   3200000000
7    KLABIN S.A.      3.200000e+09                   3200000000

   Quantidade_Acoes_Preferenciais  ...  volume_financeiro  \
0                      3536164161  ...         61077767.0
1                      3536164161  ...         11370865.0
2                      3889780576  ...        298955646.0
3                      3889780576  ...         66959843.0
4                      3889780576  ...         35358779.0
5                      3889780576  ...        108682132.0
6                      3200000000  ...        103974987.0
7                      3200000000  ...        319699223.0

   volume_financeiro_medio  numero_negocios  quantidade_negociada  \
0             2.908465e+06            16982              12670700
1             5.414698e+05             7674               1956600
2             1.573451e+07            77619              70250200
3             3.524202e+06            24883              15559300
4             1.860988e+06            16373               7392400
5             5.720112e+06            32625              23767000
6             5.198749e+06            31163              28060500
7             1.598496e+07            71321              86106000

   dias_negociados  retorno_12m  momentum_rank  momentum_percentile  \
0               21    -0.024590            1.0                  1.0
1               21    -0.041736            2.0                  0.5
2               19    -0.223592            1.0                  1.0
3               19    -0.263333            2.0                  0.5
4               19    -0.352021            1.0                  1.0
5               19    -0.433333            2.0                  0.5
6               20    -0.704880            1.0                  1.0
7               20    -0.724542            2.0                  0.5

   market_cap_rank  liquidez_rank
0              2.0            2.0
1              3.0            4.0
2              4.0            4.0
3              6.0            5.0
4              6.0            5.0
5              4.0            4.0
6              5.0            5.0
7              6.0            4.0

[8 rows x 24 columns]

In [48]:
print("B3 original:", df_b3.shape)

print("\nTipos de mercado:")
print(df_b3["tipo_mercado"].value_counts().head(20))

print("\nTickers:")
print(df_b3["ticker"].nunique())

print("\nCapital social:")
print(df_capital_social.shape)

print("\nEmpresas CVM:")
print(df_capital_social["CNPJ_Companhia"].nunique())

B3 original: (21154710, 27)

Tipos de mercado:
tipo_mercado
070    7810857
080    7079186
010    3270777
020    1523209
030    1122973
012     179031
013     164926
021       2459
017       1292
Name: count, dtype: int64

Tickers:
899056

Capital social:
(45658, 17)

Empresas CVM:
1230

In [49]:
b3 = df_b3.copy()

b3["data"] = pd.to_datetime(b3["data"], errors="coerce")

b3["ticker"] = (
    b3["ticker"]
    .astype(str)
    .str.strip()
    .str.upper()
)

b3["tipo_mercado"] = (
    b3["tipo_mercado"]
    .astype(str)
    .str.strip()
)

# Mercado à vista
b3 = b3[
    b3["tipo_mercado"] == "010"
].copy()

# Apenas ações ON/PN
b3 = b3[
    b3["ticker"].str.match(r".*[345678]$", na=False)
].copy()

print(b3.shape)
print(b3["ticker"].nunique())

(2171710, 27)
1995

In [50]:
def normalizar_nome(s):
    import unicodedata
    import re

    s = str(s).upper()

    s = unicodedata.normalize(
        "NFKD", s
    ).encode(
        "ASCII", "ignore"
    ).decode("ASCII")

    s = re.sub(r"[^A-Z0-9]", "", s)

    return s


b3["nome_norm"] = (
    b3["nome_empresa"]
    .apply(normalizar_nome)
)

cs = df_capital_social.copy()

cs["nome_norm"] = (
    cs["Nome_Companhia"]
    .apply(normalizar_nome)
)

nomes_b3 = set(b3["nome_norm"].dropna())
nomes_cvm = set(cs["nome_norm"].dropna())

intersecao = nomes_b3 & nomes_cvm

print("Nomes B3:", len(nomes_b3))
print("Nomes CVM:", len(nomes_cvm))
print("Nomes coincidentes:", len(intersecao))

Nomes B3: 1686
Nomes CVM: 1250
Nomes coincidentes: 14

In [51]:
print(df_fca.shape)

print(df_fca.columns.tolist())

print(
    df_fca.head().to_string()
)

(132830, 331)
['CNPJ_CIA', 'DT_REFER', 'VERSAO', 'DENOM_CIA', 'CD_CVM', 'CATEG_DOC', 'ID_DOC', 'DT_RECEB', 'LINK_DOC', 'CNPJ_Companhia', 'Data_Referencia', 'Versao', 'ID_Documento', 'Nome_Companhia', 'Orgao_Administracao', 'Nome', 'CPF', 'Profissao', 'Cargo_Eletivo_Ocupado', 'Complemento_Cargo_Eletivo_Ocupado', 'Data_Eleicao', 'Data_Posse', 'Data_Inicio_Primeiro_Mandato', 'Prazo_Mandato', 'Eleito_Controlador', 'Outro_Cargo_Funcao', 'Experiencia_Profissional', 'Data_Nascimento', 'Numero_Mandatos_Consecutivos', 'Percentual_Participacao_Reunioes', 'Descricao_Bem_Ativo', 'Pais', 'UF', 'Municipio', 'Tipo_Propriedade', 'Tipo_Ativo', 'Descricao_Ativo', 'Duracao', 'Evento_Perda_Direito', 'Consequencia_Perda_Direito', 'ID_Auditor', 'Auditor', 'CPF_Auditor', 'CNPJ_Auditor', 'Codigo_CVM_Auditor', 'Tipo_Origem_Auditor', 'Data_Inicio_Contratacao', 'Data_Fim_Contratacao', 'Data_Inicio_Prestacao_Servico', 'Servico_Contratado', 'Remuneracao_Auditor', 'Justificativa_Substituicao', 'Razao_Apresentada', 'Data_Inicio_Responsavel_Tecnico', 'Data_Fim_Responsavel_Tecnico', 'Responsavel_Tecnico', 'CPF_Responsavel_Tecnico', 'Logradouro', 'Complemento', 'Bairro', 'Cidade', 'Sigla_UF', 'CEP', 'DDI_Telefone', 'DDD_Telefone', 'Telefone', 'Fax', 'Email', 'ID_Capital_Social', 'Tipo_Capital', 'Data_Autorizacao_Aprovacao', 'Valor_Capital', 'Prazo_Integralizacao', 'Quantidade_Acoes_Ordinarias', 'Quantidade_Acoes_Preferenciais', 'Quantidade_Total_Acoes', 'ID_Capital_Social_Aumento', 'Data_Deliberacao', 'Orgao_Deliberacao_Aumento', 'Data_Emissao', 'Valor_Total_Emissao', 'Tipo_Subscricao', 'Subscricao_Capital_Anterior', 'Fator_Cotacao', 'Preco_Emissao', 'Criterio_Determinacao_Preco_Emissao', 'Forma_Integralizacao', 'Tipo_Classe_Acao_Preferencial', 'Quantidade_Acoes', 'ID_Capital_Social_Desdobramento', 'Data_Aprovacao', 'Tipo_Evento', 'Quantidade_Acoes_Ordinarias_Antes_Aprovacao', 'Quantidade_Acoes_Preferenciais_Antes_Aprovacao', 'Quantidade_Total_Acoes_Antes_Aprovacao', 'Quantidade_Acoes_Ordinarias_Depois_Aprovacao', 'Quantidade_Acoes_Preferenciais_Depois_Aprovacao', 'Quantidade_Total_Acoes_Depois_Aprovacao', 'Quantidade_Acoes_Antes_Aprovacao', 'Quantidade_Acoes_Depois_Aprovacao', 'ID_Capital_Social_Reducao', 'Data_Reducao', 'Valor_Total_Reducao', 'Reducao_Capital_Anterior', 'Valor_Restituido_Por_Acao', 'Forma_Restituicao', 'Razao_Reducao', 'Titulo_Conversivel_Acao', 'Condicoes_Conversao', 'Especie_Acao', 'Classe_Acao_Preferencial', 'Percentual_Tag_Along', 'Direito_Dividendo', 'Direito_Voto', 'Conversibilidade', 'Descricao_Voto_Restrito', 'Condicao_Conversibilidade_Efeito_Capital_Social', 'Direito_Reembolso_Capital', 'Restricao_Circulacao', 'Caracteristicas_Reembolso_Capital', 'Descricao_Restricao_Circulacao', 'Resgatavel', 'Hipotese_Resgate_Formula_Calculo', 'Condicao_Alteracao_Direitos', 'Outras_Caracteristicas_Relevantes', 'Quantidade_Acionistas_PF', 'Quantidade_Acionistas_PJ', 'Quantidade_Acionistas_Investidores_Institucionais', 'Quantidade_Acoes_Ordinarias_Circulacao', 'Percentual_Acoes_Ordinarias_Circulacao', 'Quantidade_Acoes_Preferenciais_Circulacao', 'Percentual_Acoes_Preferenciais_Circulacao', 'Quantidade_Total_Acoes_Circulacao', 'Percentual_Total_Acoes_Circulacao', 'Data_Ultima_Assembleia', 'Sigla_Classe_Acoes_Preferenciais', 'Classe_Acoes_Preferenciais', 'Data_Inicio_Exercicio_Social', 'Data_Fim_Exercicio_Social', 'Lucro_Liquido_Ajustado', 'Taxa_Retorno_Patrimonio_Liquido_Emissor', 'Lucro_Liquido_Retido', 'Dividendo_Distribuido_Lucro_Liquido_Ajustado', 'Dividendo_Distribuido_Total', 'Data_Aprovacao_Retencao', 'Classe_Acao', 'Dividendo_Distribuido', 'Montante', 'Data_Pagamento_Dividendo', 'Passivo', 'Indice_Endividamento', 'Tipo_Indice', 'Descricao_Outro_Indice', 'Data_Operacao', 'Descricao_Operacao', 'Evento_Societario', 'Data_Constituicao_Emissor', 'Forma_Constituicao_Emissor', 'Sigla_Pais_Constituicao_Emissor', 'Pais_Constituicao_Emissor', 'Prazo_Duracao_Emissor', 'Data_Registro_Emissor', 'Requisicao_Registro_Emissor', 'Codigo_Conta', 'Descricao_Conta', 'Valor', 'Informacao_Financeira', 'Tipo_Moeda', 'Escala_Moeda', 'Tipo_Comite', 'Descricao_Outros_Comites', 'Cargo_Ocupado', 'Descricao_Outro_Cargo_Ocupado', 'Tipo_Obrigacao', 'Tipo_Garantia', 'Descricao_Outras_Garantias', 'Divida_Inferior_1_Ano', 'Divida_1a3Anos', 'Divida_3a5Anos', 'Divida_Superior_5Anos', 'Divida_Total', 'Observacao', 'Valor_Mobiliario', 'Identificacao_Valor_Mobiliario', 'Data_Vencimento', 'Quantidade', 'Quantidade_Pessoa_Fisica', 'Quantidade_Pessoa_Juridica', 'Quantidade_Investidor_Institucional', 'Saldo_Devedor', 'Caracteristicas_Valores_Mobiliarios_Divida', 'ID_Sociedade', 'Razao_Social', 'CNPJ', 'Tipo_Sociedade', 'Descricao_Atividades', 'Pais_Sede', 'UF_Sede', 'Municipio_Sede', 'Participacao_Emissor', 'Possui_Registro_CVM', 'Codigo_CVM', 'Razao_Aquisicao_Manutencao', 'Data_Valor_Mercado', 'Data_Valor_Contabil', 'Valor_Mercado', 'Valor_Contabil', 'Data_Encerramento', 'Variacao_Percentual_Valor_Contabil', 'Variacao_Percentual_Valor_Mercado', 'Valor_Montante_Dividendos_Recebidos', 'ID_Plano_Recompra', 'Data_Inicio_Recompra', 'Data_Fim_Recompra', 'Valor_Reserva_Disponivel_Recompra', 'Outras_Caracteristicas_Importantes', 'Quantidade_Adquirida', 'Escala_Cotacao', 'Quantidade_Prevista', 'Valor_Preco_Medio', 'Percentual_Previsto', 'Percentual_Adquirido', 'ID_Politica', 'Orgao_Aprovacao', 'Principais_Caracteristicas', 'Vedacao_Procedimentos_Fiscalizacao', 'Cargo_Pessoa_Vinculada', 'ID_Acionista', 'Acionista', 'Tipo_Pessoa_Acionista', 'CPF_CNPJ_Acionista', 'ID_Acionista_Relacionado', 'Acionista_Relacionado', 'Tipo_Pessoa_Acionista_Relacionado', 'CPF_CNPJ_Acionista_Relacionado', 'Quantidade_Acao_Ordinaria_Circulacao', 'Percentual_Acao_Ordinaria_Circulacao', 'Quantidade_Acao_Preferencial_Circulacao', 'Percentual_Acao_Preferencial_Circulacao', 'Nacionalidade', 'Residente_Exterior', 'Representante_Legal', 'Tipo_Pessoa_Representante_Legal', 'CPF_CNPJ_Representante_legal', 'Data_Composicao_Capital_Social', 'Data_Ultima_Alteracao', 'Acionista_Controlador', 'Participante_Acordo_Acionistas', 'Percentual_Acoes', 'Nome_Administrador', 'CPF_Administrador', 'Nome_Emissor', 'CNPJ_Emissor', 'Cargo_Administrador', 'Nome_Pessoa_Relacionada', 'CPF_Pessoa_Relacionada', 'Nome_Emissor_Pessoa_Relacionada', 'CNPJ_Emissor_Pessoa_Relacionada', 'Cargo_Pessoa_Relacionada', 'Tipo_Parentesco', 'Tipo_Pessoa_Relacionada', 'Documento_Pessoa_Relacionada', 'Categoria_Pessoa_Relacionada', 'Tipo_Relacao', 'Numero_Membros', 'Numero_Membros_Remunerados', 'Valor_Maior_Remuneracao', 'Valor_Menor_Remuneracao', 'Valor_Medio_Remuneracao', 'Total_Remuneracao', 'Total_Remuneracao_Orgao', 'Salario', 'Beneficios_Diretos_Indiretos', 'Participacoes_Comites', 'Outros_Valores_Fixos', 'Descricao_Outros_Remuneracoes_Fixas', 'Bonus', 'Participacao_Resultados', 'Participacao_Reunioes', 'Outros_Valores_Variaveis', 'Comissoes', 'Descricao_Outros_Remuneracoes_Variaveis', 'Pos_emprego', 'Cessacao_Cargo', 'Baseada_Acoes', 'Nome_Responsavel', 'Cargo_Responsavel', 'Parte_Relacionada', 'Tipo_Pessoa', 'Documento_Parte_Relacionada', 'Relacao_Emissor', 'Data_Transacao', 'Objeto_Contrato', 'Montante_Envolvido', 'Saldo_Existente', 'Montante_Interesse_Parte_Relacionada', 'Garantia_Seguro', 'Duracao_Transacao', 'Emprestimo_Divida', 'Rescisao', 'Natureza_Razao_Operacao', 'Taxa_Juros', 'Posicao_Contratual_Emissor', 'Especificacao_Posicao_Contratual_Emissor', 'Descricao_Valor_Mobiliario', 'Quantidade_Inicial', 'Valor_Total_Inicial', 'Valor_Preco_Medio_Inicial', 'Valor_Total_Adquirido', 'Valor_Preco_Medio_Adquirido', 'Quantidade_Alienada', 'Valor_Total_Alienado', 'Valor_Preco_Medio_Alienado', 'Quantidade_Cancelada', 'Valor_Total_Cancelado', 'Valor_Preco_Medio_Cancelado', 'Quantidade_Final', 'Valor_Total_Final', 'Valor_Preco_Medio_Final', 'Percentual_Relacao_Valores_Mobiliarios_Circulacao', 'Quantidade_Valor_Mobiliario', 'Data_Aquisicao', 'Percentual_Circulacao', 'Data_Fim_Trimestre', 'Mercado_Valor_Mobiliario', 'Entidade_Administradora_Mercado', 'Descricao_Outro_Valor_Mobiliario', 'Valor_Volume_Negociado', 'Valor_Maior_Cotacao', 'Valor_Menor_Cotacao', 'Valor_Cotacao_Media']
             CNPJ_CIA    DT_REFER  VERSAO        DENOM_CIA  CD_CVM CATEG_DOC  ID_DOC    DT_RECEB                                                                                                             LINK_DOC CNPJ_Companhia Data_Referencia  Versao  ID_Documento Nome_Companhia Orgao_Administracao Nome  CPF Profissao Cargo_Eletivo_Ocupado Complemento_Cargo_Eletivo_Ocupado Data_Eleicao Data_Posse  Data_Inicio_Primeiro_Mandato Prazo_Mandato Eleito_Controlador Outro_Cargo_Funcao Experiencia_Profissional  Data_Nascimento  Numero_Mandatos_Consecutivos  Percentual_Participacao_Reunioes Descricao_Bem_Ativo Pais   UF Municipio Tipo_Propriedade Tipo_Ativo Descricao_Ativo Duracao Evento_Perda_Direito Consequencia_Perda_Direito  ID_Auditor Auditor  CPF_Auditor  CNPJ_Auditor  Codigo_CVM_Auditor Tipo_Origem_Auditor Data_Inicio_Contratacao Data_Fim_Contratacao  Data_Inicio_Prestacao_Servico Servico_Contratado Remuneracao_Auditor Justificativa_Substituicao Razao_Apresentada Data_Inicio_Responsavel_Tecnico Data_Fim_Responsavel_Tecnico Responsavel_Tecnico  CPF_Responsavel_Tecnico Logradouro Complemento Bairro Cidade Sigla_UF  CEP  DDI_Telefone  DDD_Telefone  Telefone  Fax Email  ID_Capital_Social Tipo_Capital Data_Autorizacao_Aprovacao  Valor_Capital Prazo_Integralizacao  Quantidade_Acoes_Ordinarias  Quantidade_Acoes_Preferenciais  Quantidade_Total_Acoes  ID_Capital_Social_Aumento Data_Deliberacao Orgao_Deliberacao_Aumento Data_Emissao  Valor_Total_Emissao Tipo_Subscricao  Subscricao_Capital_Anterior Fator_Cotacao  Preco_Emissao Criterio_Determinacao_Preco_Emissao Forma_Integralizacao Tipo_Classe_Acao_Preferencial  Quantidade_Acoes  ID_Capital_Social_Desdobramento Data_Aprovacao Tipo_Evento  Quantidade_Acoes_Ordinarias_Antes_Aprovacao  Quantidade_Acoes_Preferenciais_Antes_Aprovacao  Quantidade_Total_Acoes_Antes_Aprovacao  Quantidade_Acoes_Ordinarias_Depois_Aprovacao  Quantidade_Acoes_Preferenciais_Depois_Aprovacao  Quantidade_Total_Acoes_Depois_Aprovacao  Quantidade_Acoes_Antes_Aprovacao  Quantidade_Acoes_Depois_Aprovacao  ID_Capital_Social_Reducao Data_Reducao  Valor_Total_Reducao  Reducao_Capital_Anterior  Valor_Restituido_Por_Acao Forma_Restituicao Razao_Reducao Titulo_Conversivel_Acao Condicoes_Conversao Especie_Acao Classe_Acao_Preferencial  Percentual_Tag_Along Direito_Dividendo Direito_Voto Conversibilidade Descricao_Voto_Restrito Condicao_Conversibilidade_Efeito_Capital_Social Direito_Reembolso_Capital Restricao_Circulacao Caracteristicas_Reembolso_Capital Descricao_Restricao_Circulacao Resgatavel Hipotese_Resgate_Formula_Calculo Condicao_Alteracao_Direitos Outras_Caracteristicas_Relevantes  Quantidade_Acionistas_PF  Quantidade_Acionistas_PJ  Quantidade_Acionistas_Investidores_Institucionais  Quantidade_Acoes_Ordinarias_Circulacao  Percentual_Acoes_Ordinarias_Circulacao  Quantidade_Acoes_Preferenciais_Circulacao  Percentual_Acoes_Preferenciais_Circulacao  Quantidade_Total_Acoes_Circulacao  Percentual_Total_Acoes_Circulacao Data_Ultima_Assembleia Sigla_Classe_Acoes_Preferenciais Classe_Acoes_Preferenciais Data_Inicio_Exercicio_Social Data_Fim_Exercicio_Social  Lucro_Liquido_Ajustado  Taxa_Retorno_Patrimonio_Liquido_Emissor  Lucro_Liquido_Retido  Dividendo_Distribuido_Lucro_Liquido_Ajustado  Dividendo_Distribuido_Total Data_Aprovacao_Retencao Classe_Acao Dividendo_Distribuido  Montante Data_Pagamento_Dividendo  Passivo  Indice_Endividamento Tipo_Indice Descricao_Outro_Indice Data_Operacao Descricao_Operacao Evento_Societario Data_Constituicao_Emissor Forma_Constituicao_Emissor Sigla_Pais_Constituicao_Emissor Pais_Constituicao_Emissor Prazo_Duracao_Emissor Data_Registro_Emissor Requisicao_Registro_Emissor Codigo_Conta Descricao_Conta  Valor Informacao_Financeira Tipo_Moeda Escala_Moeda Tipo_Comite Descricao_Outros_Comites Cargo_Ocupado Descricao_Outro_Cargo_Ocupado  Tipo_Obrigacao Tipo_Garantia  Descricao_Outras_Garantias  Divida_Inferior_1_Ano  Divida_1a3Anos  Divida_3a5Anos  Divida_Superior_5Anos  Divida_Total Observacao Valor_Mobiliario Identificacao_Valor_Mobiliario Data_Vencimento  Quantidade  Quantidade_Pessoa_Fisica  Quantidade_Pessoa_Juridica  Quantidade_Investidor_Institucional  Saldo_Devedor Caracteristicas_Valores_Mobiliarios_Divida  ID_Sociedade Razao_Social  CNPJ Tipo_Sociedade Descricao_Atividades Pais_Sede UF_Sede Municipio_Sede  Participacao_Emissor Possui_Registro_CVM  Codigo_CVM Razao_Aquisicao_Manutencao Data_Valor_Mercado Data_Valor_Contabil  Valor_Mercado  Valor_Contabil Data_Encerramento  Variacao_Percentual_Valor_Contabil  Variacao_Percentual_Valor_Mercado  Valor_Montante_Dividendos_Recebidos  ID_Plano_Recompra Data_Inicio_Recompra Data_Fim_Recompra  Valor_Reserva_Disponivel_Recompra Outras_Caracteristicas_Importantes  Quantidade_Adquirida Escala_Cotacao  Quantidade_Prevista  Valor_Preco_Medio  Percentual_Previsto  Percentual_Adquirido  ID_Politica  Orgao_Aprovacao Principais_Caracteristicas Vedacao_Procedimentos_Fiscalizacao Cargo_Pessoa_Vinculada  ID_Acionista Acionista Tipo_Pessoa_Acionista CPF_CNPJ_Acionista  ID_Acionista_Relacionado Acionista_Relacionado Tipo_Pessoa_Acionista_Relacionado CPF_CNPJ_Acionista_Relacionado  Quantidade_Acao_Ordinaria_Circulacao  Percentual_Acao_Ordinaria_Circulacao  Quantidade_Acao_Preferencial_Circulacao  Percentual_Acao_Preferencial_Circulacao Nacionalidade Residente_Exterior  Representante_Legal  Tipo_Pessoa_Representante_Legal  CPF_CNPJ_Representante_legal  Data_Composicao_Capital_Social Data_Ultima_Alteracao Acionista_Controlador Participante_Acordo_Acionistas  Percentual_Acoes Nome_Administrador CPF_Administrador Nome_Emissor CNPJ_Emissor Cargo_Administrador Nome_Pessoa_Relacionada CPF_Pessoa_Relacionada Nome_Emissor_Pessoa_Relacionada CNPJ_Emissor_Pessoa_Relacionada Cargo_Pessoa_Relacionada Tipo_Parentesco Tipo_Pessoa_Relacionada Documento_Pessoa_Relacionada Categoria_Pessoa_Relacionada Tipo_Relacao  Numero_Membros  Numero_Membros_Remunerados  Valor_Maior_Remuneracao  Valor_Menor_Remuneracao  Valor_Medio_Remuneracao  Total_Remuneracao  Total_Remuneracao_Orgao  Salario  Beneficios_Diretos_Indiretos  Participacoes_Comites  Outros_Valores_Fixos Descricao_Outros_Remuneracoes_Fixas  Bonus  Participacao_Resultados  Participacao_Reunioes  Outros_Valores_Variaveis  Comissoes Descricao_Outros_Remuneracoes_Variaveis  Pos_emprego  Cessacao_Cargo  Baseada_Acoes Nome_Responsavel Cargo_Responsavel Parte_Relacionada  Tipo_Pessoa  Documento_Parte_Relacionada Relacao_Emissor Data_Transacao Objeto_Contrato  Montante_Envolvido Saldo_Existente Montante_Interesse_Parte_Relacionada Garantia_Seguro Duracao_Transacao Emprestimo_Divida Rescisao Natureza_Razao_Operacao  Taxa_Juros  Posicao_Contratual_Emissor  Especificacao_Posicao_Contratual_Emissor Descricao_Valor_Mobiliario  Quantidade_Inicial  Valor_Total_Inicial  Valor_Preco_Medio_Inicial  Valor_Total_Adquirido  Valor_Preco_Medio_Adquirido  Quantidade_Alienada  Valor_Total_Alienado  Valor_Preco_Medio_Alienado  Quantidade_Cancelada  Valor_Total_Cancelado  Valor_Preco_Medio_Cancelado  Quantidade_Final  Valor_Total_Final  Valor_Preco_Medio_Final  Percentual_Relacao_Valores_Mobiliarios_Circulacao  Quantidade_Valor_Mobiliario Data_Aquisicao  Percentual_Circulacao Data_Fim_Trimestre Mercado_Valor_Mobiliario Entidade_Administradora_Mercado Descricao_Outro_Valor_Mobiliario  Valor_Volume_Negociado  Valor_Maior_Cotacao  Valor_Menor_Cotacao  Valor_Cotacao_Media

In [52]:
print(
    df_fca[
        ["CNPJ_Companhia", "Nome_Companhia"]
    ].drop_duplicates().head(20)
)

          CNPJ_Companhia                             Nome_Companhia
0                    NaN                                        NaN
2783  00.000.000/0001-91                            BCO BRASIL S.A.
2784  00.000.208/0001-00                 BRB BANCO DE BRASILIA S.A.
2801  00.001.180/0001-26       CENTRAIS ELET BRAS S.A. - ELETROBRAS
2820  00.027.742/0001-00                      CBCC PARTICIPAÇÕES SA
2826  00.070.698/0001-11     COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB
2843  00.095.147/0001-02                             VBC ENERGIA SA
2850  00.108.786/0001-65           NET SERVIÇOS DE COMUNICAÇÃO S.A.
2866  00.115.890/0001-87                SHOPPING CENTER TACARUNA SA
2870  00.185.475/0001-08  PARCOM PARTICIPACOES S.A. - EM LIQUIDAÇÃO
2874  00.187.032/0001-48                          KLABIN SEGALL S/A
2878  00.192.769/0001-59    NEUMARKT TRADE AND FINANCIAL CENTER S/A
2882  00.249.786/0001-85               FORPART S.A. - EM LIQUIDAÇÃO
2886  00.272.185/0001-93                                  CIMS S.A.
2891  00.336.701/0001-04            TELEC BRASILEIRAS S.A. TELEBRAS
2912  00.359.742/0001-08                      FICTOR ALIMENTOS S.A.
2920  00.383.281/0001-09        BNDES PARTICIPACOES S.A. - BNDESPAR
2937  00.514.998/0001-42                               ELETRON S.A.
2942  00.545.378/0001-70                   SERRA AZUL WATER PARK SA
2950  00.644.907/0001-93                              INVESTCO S.A.

In [53]:
print(df_fca.columns.tolist())

['CNPJ_CIA', 'DT_REFER', 'VERSAO', 'DENOM_CIA', 'CD_CVM', 'CATEG_DOC', 'ID_DOC', 'DT_RECEB', 'LINK_DOC', 'CNPJ_Companhia', 'Data_Referencia', 'Versao', 'ID_Documento', 'Nome_Companhia', 'Orgao_Administracao', 'Nome', 'CPF', 'Profissao', 'Cargo_Eletivo_Ocupado', 'Complemento_Cargo_Eletivo_Ocupado', 'Data_Eleicao', 'Data_Posse', 'Data_Inicio_Primeiro_Mandato', 'Prazo_Mandato', 'Eleito_Controlador', 'Outro_Cargo_Funcao', 'Experiencia_Profissional', 'Data_Nascimento', 'Numero_Mandatos_Consecutivos', 'Percentual_Participacao_Reunioes', 'Descricao_Bem_Ativo', 'Pais', 'UF', 'Municipio', 'Tipo_Propriedade', 'Tipo_Ativo', 'Descricao_Ativo', 'Duracao', 'Evento_Perda_Direito', 'Consequencia_Perda_Direito', 'ID_Auditor', 'Auditor', 'CPF_Auditor', 'CNPJ_Auditor', 'Codigo_CVM_Auditor', 'Tipo_Origem_Auditor', 'Data_Inicio_Contratacao', 'Data_Fim_Contratacao', 'Data_Inicio_Prestacao_Servico', 'Servico_Contratado', 'Remuneracao_Auditor', 'Justificativa_Substituicao', 'Razao_Apresentada', 'Data_Inicio_Responsavel_Tecnico', 'Data_Fim_Responsavel_Tecnico', 'Responsavel_Tecnico', 'CPF_Responsavel_Tecnico', 'Logradouro', 'Complemento', 'Bairro', 'Cidade', 'Sigla_UF', 'CEP', 'DDI_Telefone', 'DDD_Telefone', 'Telefone', 'Fax', 'Email', 'ID_Capital_Social', 'Tipo_Capital', 'Data_Autorizacao_Aprovacao', 'Valor_Capital', 'Prazo_Integralizacao', 'Quantidade_Acoes_Ordinarias', 'Quantidade_Acoes_Preferenciais', 'Quantidade_Total_Acoes', 'ID_Capital_Social_Aumento', 'Data_Deliberacao', 'Orgao_Deliberacao_Aumento', 'Data_Emissao', 'Valor_Total_Emissao', 'Tipo_Subscricao', 'Subscricao_Capital_Anterior', 'Fator_Cotacao', 'Preco_Emissao', 'Criterio_Determinacao_Preco_Emissao', 'Forma_Integralizacao', 'Tipo_Classe_Acao_Preferencial', 'Quantidade_Acoes', 'ID_Capital_Social_Desdobramento', 'Data_Aprovacao', 'Tipo_Evento', 'Quantidade_Acoes_Ordinarias_Antes_Aprovacao', 'Quantidade_Acoes_Preferenciais_Antes_Aprovacao', 'Quantidade_Total_Acoes_Antes_Aprovacao', 'Quantidade_Acoes_Ordinarias_Depois_Aprovacao', 'Quantidade_Acoes_Preferenciais_Depois_Aprovacao', 'Quantidade_Total_Acoes_Depois_Aprovacao', 'Quantidade_Acoes_Antes_Aprovacao', 'Quantidade_Acoes_Depois_Aprovacao', 'ID_Capital_Social_Reducao', 'Data_Reducao', 'Valor_Total_Reducao', 'Reducao_Capital_Anterior', 'Valor_Restituido_Por_Acao', 'Forma_Restituicao', 'Razao_Reducao', 'Titulo_Conversivel_Acao', 'Condicoes_Conversao', 'Especie_Acao', 'Classe_Acao_Preferencial', 'Percentual_Tag_Along', 'Direito_Dividendo', 'Direito_Voto', 'Conversibilidade', 'Descricao_Voto_Restrito', 'Condicao_Conversibilidade_Efeito_Capital_Social', 'Direito_Reembolso_Capital', 'Restricao_Circulacao', 'Caracteristicas_Reembolso_Capital', 'Descricao_Restricao_Circulacao', 'Resgatavel', 'Hipotese_Resgate_Formula_Calculo', 'Condicao_Alteracao_Direitos', 'Outras_Caracteristicas_Relevantes', 'Quantidade_Acionistas_PF', 'Quantidade_Acionistas_PJ', 'Quantidade_Acionistas_Investidores_Institucionais', 'Quantidade_Acoes_Ordinarias_Circulacao', 'Percentual_Acoes_Ordinarias_Circulacao', 'Quantidade_Acoes_Preferenciais_Circulacao', 'Percentual_Acoes_Preferenciais_Circulacao', 'Quantidade_Total_Acoes_Circulacao', 'Percentual_Total_Acoes_Circulacao', 'Data_Ultima_Assembleia', 'Sigla_Classe_Acoes_Preferenciais', 'Classe_Acoes_Preferenciais', 'Data_Inicio_Exercicio_Social', 'Data_Fim_Exercicio_Social', 'Lucro_Liquido_Ajustado', 'Taxa_Retorno_Patrimonio_Liquido_Emissor', 'Lucro_Liquido_Retido', 'Dividendo_Distribuido_Lucro_Liquido_Ajustado', 'Dividendo_Distribuido_Total', 'Data_Aprovacao_Retencao', 'Classe_Acao', 'Dividendo_Distribuido', 'Montante', 'Data_Pagamento_Dividendo', 'Passivo', 'Indice_Endividamento', 'Tipo_Indice', 'Descricao_Outro_Indice', 'Data_Operacao', 'Descricao_Operacao', 'Evento_Societario', 'Data_Constituicao_Emissor', 'Forma_Constituicao_Emissor', 'Sigla_Pais_Constituicao_Emissor', 'Pais_Constituicao_Emissor', 'Prazo_Duracao_Emissor', 'Data_Registro_Emissor', 'Requisicao_Registro_Emissor', 'Codigo_Conta', 'Descricao_Conta', 'Valor', 'Informacao_Financeira', 'Tipo_Moeda', 'Escala_Moeda', 'Tipo_Comite', 'Descricao_Outros_Comites', 'Cargo_Ocupado', 'Descricao_Outro_Cargo_Ocupado', 'Tipo_Obrigacao', 'Tipo_Garantia', 'Descricao_Outras_Garantias', 'Divida_Inferior_1_Ano', 'Divida_1a3Anos', 'Divida_3a5Anos', 'Divida_Superior_5Anos', 'Divida_Total', 'Observacao', 'Valor_Mobiliario', 'Identificacao_Valor_Mobiliario', 'Data_Vencimento', 'Quantidade', 'Quantidade_Pessoa_Fisica', 'Quantidade_Pessoa_Juridica', 'Quantidade_Investidor_Institucional', 'Saldo_Devedor', 'Caracteristicas_Valores_Mobiliarios_Divida', 'ID_Sociedade', 'Razao_Social', 'CNPJ', 'Tipo_Sociedade', 'Descricao_Atividades', 'Pais_Sede', 'UF_Sede', 'Municipio_Sede', 'Participacao_Emissor', 'Possui_Registro_CVM', 'Codigo_CVM', 'Razao_Aquisicao_Manutencao', 'Data_Valor_Mercado', 'Data_Valor_Contabil', 'Valor_Mercado', 'Valor_Contabil', 'Data_Encerramento', 'Variacao_Percentual_Valor_Contabil', 'Variacao_Percentual_Valor_Mercado', 'Valor_Montante_Dividendos_Recebidos', 'ID_Plano_Recompra', 'Data_Inicio_Recompra', 'Data_Fim_Recompra', 'Valor_Reserva_Disponivel_Recompra', 'Outras_Caracteristicas_Importantes', 'Quantidade_Adquirida', 'Escala_Cotacao', 'Quantidade_Prevista', 'Valor_Preco_Medio', 'Percentual_Previsto', 'Percentual_Adquirido', 'ID_Politica', 'Orgao_Aprovacao', 'Principais_Caracteristicas', 'Vedacao_Procedimentos_Fiscalizacao', 'Cargo_Pessoa_Vinculada', 'ID_Acionista', 'Acionista', 'Tipo_Pessoa_Acionista', 'CPF_CNPJ_Acionista', 'ID_Acionista_Relacionado', 'Acionista_Relacionado', 'Tipo_Pessoa_Acionista_Relacionado', 'CPF_CNPJ_Acionista_Relacionado', 'Quantidade_Acao_Ordinaria_Circulacao', 'Percentual_Acao_Ordinaria_Circulacao', 'Quantidade_Acao_Preferencial_Circulacao', 'Percentual_Acao_Preferencial_Circulacao', 'Nacionalidade', 'Residente_Exterior', 'Representante_Legal', 'Tipo_Pessoa_Representante_Legal', 'CPF_CNPJ_Representante_legal', 'Data_Composicao_Capital_Social', 'Data_Ultima_Alteracao', 'Acionista_Controlador', 'Participante_Acordo_Acionistas', 'Percentual_Acoes', 'Nome_Administrador', 'CPF_Administrador', 'Nome_Emissor', 'CNPJ_Emissor', 'Cargo_Administrador', 'Nome_Pessoa_Relacionada', 'CPF_Pessoa_Relacionada', 'Nome_Emissor_Pessoa_Relacionada', 'CNPJ_Emissor_Pessoa_Relacionada', 'Cargo_Pessoa_Relacionada', 'Tipo_Parentesco', 'Tipo_Pessoa_Relacionada', 'Documento_Pessoa_Relacionada', 'Categoria_Pessoa_Relacionada', 'Tipo_Relacao', 'Numero_Membros', 'Numero_Membros_Remunerados', 'Valor_Maior_Remuneracao', 'Valor_Menor_Remuneracao', 'Valor_Medio_Remuneracao', 'Total_Remuneracao', 'Total_Remuneracao_Orgao', 'Salario', 'Beneficios_Diretos_Indiretos', 'Participacoes_Comites', 'Outros_Valores_Fixos', 'Descricao_Outros_Remuneracoes_Fixas', 'Bonus', 'Participacao_Resultados', 'Participacao_Reunioes', 'Outros_Valores_Variaveis', 'Comissoes', 'Descricao_Outros_Remuneracoes_Variaveis', 'Pos_emprego', 'Cessacao_Cargo', 'Baseada_Acoes', 'Nome_Responsavel', 'Cargo_Responsavel', 'Parte_Relacionada', 'Tipo_Pessoa', 'Documento_Parte_Relacionada', 'Relacao_Emissor', 'Data_Transacao', 'Objeto_Contrato', 'Montante_Envolvido', 'Saldo_Existente', 'Montante_Interesse_Parte_Relacionada', 'Garantia_Seguro', 'Duracao_Transacao', 'Emprestimo_Divida', 'Rescisao', 'Natureza_Razao_Operacao', 'Taxa_Juros', 'Posicao_Contratual_Emissor', 'Especificacao_Posicao_Contratual_Emissor', 'Descricao_Valor_Mobiliario', 'Quantidade_Inicial', 'Valor_Total_Inicial', 'Valor_Preco_Medio_Inicial', 'Valor_Total_Adquirido', 'Valor_Preco_Medio_Adquirido', 'Quantidade_Alienada', 'Valor_Total_Alienado', 'Valor_Preco_Medio_Alienado', 'Quantidade_Cancelada', 'Valor_Total_Cancelado', 'Valor_Preco_Medio_Cancelado', 'Quantidade_Final', 'Valor_Total_Final', 'Valor_Preco_Medio_Final', 'Percentual_Relacao_Valores_Mobiliarios_Circulacao', 'Quantidade_Valor_Mobiliario', 'Data_Aquisicao', 'Percentual_Circulacao', 'Data_Fim_Trimestre', 'Mercado_Valor_Mobiliario', 'Entidade_Administradora_Mercado', 'Descricao_Outro_Valor_Mobiliario', 'Valor_Volume_Negociado', 'Valor_Maior_Cotacao', 'Valor_Menor_Cotacao', 'Valor_Cotacao_Media']

In [54]:
# ============================================================
# PARTE DO FCA RELACIONADA A VALORES MOBILIÁRIOS
# ============================================================

fca_vm = df_fca[
    df_fca["Valor_Mobiliario"].notna()
].copy()

print("Shape:", fca_vm.shape)

print(
    fca_vm[
        [
            "CNPJ_Companhia",
            "Nome_Companhia",
            "Valor_Mobiliario",
            "Identificacao_Valor_Mobiliario"
        ]
    ]
    .drop_duplicates()
    .head(50)
    .to_string(index=False)
)

Shape: (7359, 331)
    CNPJ_Companhia                               Nome_Companhia        Valor_Mobiliario                                                                       Identificacao_Valor_Mobiliario
00.000.000/0001-91                              BCO BRASIL S.A.     Bônus de Subscrição                                                                        Bônus de Subscrição - Série C
00.001.180/0001-26         CENTRAIS ELET BRAS S.A. - ELETROBRAS          Nota Comercial         As Notas 2019 são títulos de dívidas emitidos e colocados junto a investidores qualificados.
00.001.180/0001-26         CENTRAIS ELET BRAS S.A. - ELETROBRAS          Nota Comercial         As Notas 2015 são títulos de dívidas emitidos e colocados junto a investidores qualificados.
00.095.147/0001-02                               VBC ENERGIA SA              Debêntures                                                                            3a. emissão de debêntures
00.095.147/0001-02                               VBC ENERGIA SA              Debêntures                                                                            6a. emissão de debêntures
00.095.147/0001-02                               VBC ENERGIA SA              Debêntures                                                                            8a. emissão de debêntures
00.108.786/0001-65             NET SERVIÇOS DE COMUNICAÇÃO S.A.              Debêntures                                                                                               10.000
00.115.890/0001-87                  SHOPPING CENTER TACARUNA SA              Debêntures                                                                                    Debentures 96/096
00.185.475/0001-08    PARCOM PARTICIPACOES S.A. - EM LIQUIDAÇÃO Debêntures Conversíveis                                                                    Debêntures Conversíveis em Ações.
00.192.769/0001-59      NEUMARKT TRADE AND FINANCIAL CENTER S/A              Debêntures                                                                                           Debentures
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                 CVM/SRE/DEB/2006/047
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                 CVM/SRE/DEB/2007/028
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                 CVM/SRE/DEB/2007/029
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                 CVM/SRE/DEB/2009/023
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                 CVM/SRE/DEB/2009/024
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                   SEP/GER/DEB-98/005
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                 CVM/SRE/DEB/2010/033
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                 CVM/SRE/DEB/2010/034
00.383.281/0001-09          BNDES PARTICIPACOES S.A. - BNDESPAR              Debêntures                                                                                 CVM/SRE/DEB/2010/035
00.644.907/0001-93                                INVESTCO S.A.              Debêntures                                                                               Simples Quirografárias
00.776.574/0001-56    AMERICANAS S.A. - EM RECUPERAÇÃO JUDICIAL              Debêntures                                            Debêntures simples não-conversíveis em ações - 1º emissão
00.776.574/0001-56    AMERICANAS S.A. - EM RECUPERAÇÃO JUDICIAL              Debêntures                                            Debêntures simples não conversíveis em ações - 2ª emissão
00.776.574/0001-56    AMERICANAS S.A. - EM RECUPERAÇÃO JUDICIAL              Debêntures Primeira emissão privada de debêntures simples, não conversíveis em ações da Companhia, da espécie s
00.861.626/0001-92                CONC RODOVIA PRES. DUTRA S.A.              Debêntures                                                                          Debêntures Simples 2ª Série
00.861.626/0001-92                CONC RODOVIA PRES. DUTRA S.A.              Debêntures                                                                          Debêntures Simples 1º Série
00.861.626/0001-92                CONC RODOVIA PRES. DUTRA S.A.              Debêntures                                                            2ª Emissão de Debêntures Simples 1ª Série
00.861.626/0001-92                CONC RODOVIA PRES. DUTRA S.A.              Debêntures                                                            2º Emissão de Debêntures Simples 2º Série
00.864.214/0001-06                                ENERGISA S.A.              Debêntures                                                                                           1ª emissão
00.864.214/0001-06                                ENERGISA S.A.              Debêntures                                                                                           3ª emissão
00.864.214/0001-06                                ENERGISA S.A.              Debêntures                                                                             4ª emissão de debêntures
00.897.864/0001-58                SANTA CATARINA PART INVEST SA Debêntures Conversíveis                                                                              DEBENTURES CONVERSIVEIS
00.924.432/0001-99                                 HOPI HARI SA              Debêntures                                                   Debêntures não conversíveis em ações de 1ª emissão
00.924.432/0001-99                                 HOPI HARI SA              Debêntures                                                   Debêntures não conversíveis em ações de 2ª emissão
00.924.432/0001-99                                 HOPI HARI SA              Debêntures                                                   Debêntures não conversíveis em ações de 3ª emissão
00.938.574/0001-05                    CONC RIO-TERESOPOLIS S.A.              Debêntures                                                                             Debêntures  conversiveis
00.979.969/0001-56                CAIXA ADM DIV PUB ESTADUAL SA              Debêntures                                                       Debenture com Garantia Subordinada, 11 Emissão
00.994.533/0001-36 COMERCIAL QUINTELLA COM EXP SA EM LIQUIDAÇÃO              Debêntures                                                                                   debêntures simples
01.258.944/0001-26                          RUMO MALHA SUL S.A.              Debêntures                                                                                           3ª Emissão
01.258.944/0001-26                          RUMO MALHA SUL S.A.              Debêntures                                                                                           4ª Emissão
01.355.994/0001-21                           ITA ENERGETICA S/A              Debêntures                                               1ª série CVM/SRE/DEB/2001/018 e CETIP 1ª Série: ITAE11
01.355.994/0001-21                           ITA ENERGETICA S/A              Debêntures                                             2ª série CVM/SRE/DEB/2001/019 - e CETIP 2ª Série: ITAE21
01.386.256/0001-41                       VOTORANTIM FINANÇAS SA              Debêntures                                                                                           Debêntures
01.386.256/0001-41                       VOTORANTIM FINANÇAS SA          Nota Comercial                                                                                    Nota Promissáoria
01.417.222/0001-77                           MRS LOGISTICA S.A.              Debêntures                    Debêntures Simples, Não Conversíveis em ações da 4ª Emissão da MRS Logística S.A.
01.425.787/0001-04                                 REDECARD S/A          Nota Comercial                                                                                             1ª Série
01.425.787/0001-04                                 REDECARD S/A          Nota Comercial                                                                                             2ª Série
01.425.787/0001-04                                 REDECARD S/A          Nota Comercial                                                                                8ª Emissão - 1ª Série
01.425.787/0001-04                                 REDECARD S/A          Nota Comercial                                                                                8ª Emissão - 2ª Série
01.425.787/0001-04                                 REDECARD S/A          Nota Comercial                                                                                8ª Emissão - 3ª Série
01.545.826/0001-07                                  GAFISA S.A.              Debêntures                                                                         Quinta Emissão de Debêntures

In [55]:
print(
    fca_vm["Valor_Mobiliario"]
    .value_counts(dropna=False)
    .head(30)
)

Valor_Mobiliario
Ações                                              6123
Certificados de Recebíveis Imobiliários             481
Debêntures                                          480
Nota Comercial                                       74
Certificados de Depósito de Valores Mobiliários      64
Bônus de Subscrição                                  45
Certificados de depósito de valores mobiliários      42
Debêntures Conversíveis                              27
Título de Investimento Coletivo                      11
Contrato de Investimento Coletivo                     7
Certificado de Recebíveis do Agronegócio              4
Valor Mobiliário Não Registrado                       1
Name: count, dtype: int64

In [56]:
print(
    fca_vm["Identificacao_Valor_Mobiliario"]
    .value_counts(dropna=False)
    .head(30)
)

Identificacao_Valor_Mobiliario
NaN                                     6333
Debêntures                                22
DEBENTURES SIMPLES PUBLICA                16
Nota Promissória                          11
Dívida Subordinada                         6
2ª emissão                                 6
1ª Emissão de Debêntures                   5
Debentures                                 5
3ª Emissão de Debêntures                   5
1ª Emissão                                 4
3ª emissão                                 4
Debêntures Conversíveis                    4
R$ 1.000,00                                4
3ª Emissão                                 3
Não se aplica                              3
4ª Emissão                                 3
1ª emissão                                 3
2ª Emissão de Debêntures                   3
Debêntures não conversíveis em ações       3
Debêntures Simples                         3
A definir                                  2
GERDAU 9º EMISSÃO                          2
Nota Promissória Comercial                 2
Bônus de subscrição série B                2
PERPETUAL BONDS                            2
Bonds                                      2
2ª Emissão de Debêntures Simples           2
GERDAU 11º EMISSÃO B                       2
GERDAU 11º EMISSÃO A                       2
4ª Emissão de Debêntures                   2
Name: count, dtype: int64

In [57]:
# Procurar todas as colunas relacionadas a ISIN
[col for col in df_fca.columns if "ISIN" in col.upper()]

[]

In [58]:
# Procurar colunas relacionadas a ticker / código de negociação
[
    col for col in df_fca.columns
    if any(x in col.upper() for x in [
        "TICKER",
        "NEGOCI",
        "CODIGO_NEG",
        "COD_NEG",
        "CODIGO",
        "SIGLA"
    ])
]

['Codigo_CVM_Auditor',
 'Sigla_UF',
 'Sigla_Classe_Acoes_Preferenciais',
 'Sigla_Pais_Constituicao_Emissor',
 'Codigo_Conta',
 'Codigo_CVM',
 'Valor_Volume_Negociado']

In [59]:
[col for col in df_capital_social.columns if "ISIN" in col.upper()]

[]

In [60]:
print("ISINs B3:")
print(
    df_b3["isin"]
    .dropna()
    .astype(str)
    .str.strip()
    .nunique()
)

print("\nExemplos:")
print(
    df_b3[
        ["ticker", "isin", "nome_empresa", "especificacao"]
    ]
    .drop_duplicates("ticker")
    .head(20)
    .to_string(index=False)
)

ISINs B3:
5445

Exemplos:
 ticker         isin nome_empresa especificacao
  ABCB4 BRABCBACNPR4   ABC BRASIL    PN  EJ  N2
 ABCB4F BRABCBACNPR4   ABC BRASIL    PN  EJ  N2
  ABNB3 BRABNBACNOR4       ABNOTE    ON  ED  NM
 ABNB3F BRABNBACNOR4       ABNOTE    ON  ED  NM
 ABNB3T BRABNBACNOR4       ABNOTE    ON  ED  NM
  ABYA3 BRABYAACNOR3       ABYARA    ON      NM
 ABYA3F BRABYAACNOR3       ABYARA    ON      NM
 ABYA3T BRABYAACNOR3       ABYARA    ON      NM
  ACES3 BRACESACNOR5   AM INOX BR        ON  EJ
 ACES3F BRACESACNOR5   AM INOX BR        ON  EJ
  ACES4 BRACESACNPR2   AM INOX BR        PN  EJ
 ACES4F BRACESACNPR2   AM INOX BR        PN  EJ
 ACES4T BRACESACNPR2   AM INOX BR        PN  EJ
  ACGU3 BRACGUACNOR6      GUARANI    ON      NM
 ACGU3F BRACGUACNOR6      GUARANI    ON      NM
 AEDU11 BRAEDUCDAM18   ANHANGUERA    UNT     N2
AEDU11F BRAEDUCDAM18   ANHANGUERA    UNT     N2
  AELP3 BRAELPACNOR2     AES ELPA        ON *EJ
 AGEN11 BRAGENBDR001      AGRENCO           DR3
AGEN11F BRAGENBDR001      AGRENCO           DR3

In [61]:
print(
    df_b3[
        df_b3["ticker"].isin(["KLBN3", "KLBN4"])
    ][
        ["ticker", "isin", "nome_empresa", "especificacao"]
    ]
    .drop_duplicates()
)

        ticker          isin nome_empresa especificacao
678      KLBN4  BRKLBNACNPR9   KLABIN S/A    PN      N1
1897     KLBN3  BRKLBNACNOR2   KLABIN S/A    ON      N1
69256    KLBN4  BRKLBNACNPR9   KLABIN S/A    PN  ED  N1
214416   KLBN3  BRKLBNACNOR2   KLABIN S/A    ON  ED  N1
1816715  KLBN4  BRKLBNACNPR9   KLABIN S/A    PN  ES  N1
1822662  KLBN3  BRKLBNACNOR2   KLABIN S/A    ON  ES  N1
1852235  KLBN4  BRKLBNACNPR9   KLABIN S/A    PN      N2
1859831  KLBN3  BRKLBNACNOR2   KLABIN S/A    ON      N2
1927232  KLBN4  BRKLBNACNPR9   KLABIN S/A    PN  ED  N2
1930232  KLBN3  BRKLBNACNOR2   KLABIN S/A    ON  EDB N2
1930233  KLBN4  BRKLBNACNPR9   KLABIN S/A    PN  EDB N2
1939332  KLBN3  BRKLBNACNOR2   KLABIN S/A    ON  EB  N2
1939334  KLBN4  BRKLBNACNPR9   KLABIN S/A    PN  EB  N2
1962028  KLBN4  BRKLBNACNPR9   KLABIN S/A    PN  ES  N2
1966365  KLBN3  BRKLBNACNOR2   KLABIN S/A    ON  ES  N2
2086716  KLBN3  BRKLBNACNOR2   KLABIN S/A    ON  ED  N2
4094519  KLBN3  BRKLBNACNOR2   KLABIN S/A    ON  EDJ N2
4094521  KLBN4  BRKLBNACNPR9   KLABIN S/A    PN  EDJ N2
4179034  KLBN3  BRKLBNACNOR2   KLABIN S/A    ON  EJ  N2
4179036  KLBN4  BRKLBNACNPR9   KLABIN S/A    PN  EJ  N2

In [63]:
df_instrumentos = (
    df_b3[
        [
            "ticker",
            "isin",
            "nome_empresa",
            "especificacao",
            "tipo_mercado",
            "data"
        ]
    ]
    .dropna(subset=["ticker", "isin"])
    .copy()
)

df_instrumentos["ticker"] = (
    df_instrumentos["ticker"]
    .astype(str)
    .str.strip()
    .str.upper()
)

df_instrumentos["isin"] = (
    df_instrumentos["isin"]
    .astype(str)
    .str.strip()
    .str.upper()
)

df_instrumentos["data"] = pd.to_datetime(
    df_instrumentos["data"],
    errors="coerce"
)

df_instrumentos = df_instrumentos[
    df_instrumentos["ticker"].str.contains(
        r"[345678]$",
        regex=True,
        na=False
    )
].copy()

df_instrumentos = (
    df_instrumentos
    .sort_values(["ticker", "data"])
    .drop_duplicates(
        ["ticker", "isin"],
        keep="last"
    )
)

print(df_instrumentos.shape)
print(df_instrumentos["ticker"].nunique())
print(df_instrumentos.head(20))

(318008, 6)
310777
          ticker          isin  nome_empresa especificacao tipo_mercado  \
21138963  A1AP34  BRA1APBDR001  ADVANCE AUTO           DRN          010
11024187  A1BB34  BRA1BBBDR009       ABB LTD           DRN          010
10004395  A1BM34  BRA1BMBDR006   ABIOMED INC           DRN          010
21106694  A1CR34  BRA1CRBDR003     AMCOR PLC           DRN          010
21123319  A1DC34  BRA1DCBDR003  AGREE REALTY           DRN          010
21138964  A1DI34  BRA1DIBDR000  ANALOG DEVIC           DRN          010
21138965  A1DM34  BRA1DMBDR002  ARCHER DANIE           DRN          010
19855660  A1EE34  BRA1EEBDR007   AMEREN CORP           DRN          010
21138966  A1EG34  BRA1EGBDR002     AEGON LTD           DRN          010
20923774  A1EN34  BRA1ENBDR008  ALLIANT ENER           DRN          010
21138967  A1EP34  BRA1EPBDR003  AMERICAN ELE           DRN          010
21138968  A1ES34  BRA1ESBDR007      AES CORP           DRN          010
20850892  A1FL34  BRA1FLBDR009     AFLAC INC           DRN          010
21106701  A1GI34  BRA1GIBDR003  AGILENT TECH           DRN          010
20994002  A1GN34  BRA1GNBDR003  ALLEGION PLC           DRN          010
20485729  A1GT34  BRA1GTBDR000      AGNT INC           DRN          010
21138969  A1IV34  BRA1IVBDR002  APARTMENT IN           DRN          010
20783373  A1JG34  BRA1JGBDR001  ARTHUR J GAL           DRN          010
21138970  A1KA34  BRA1KABDR002  AKAMAI TECHN           DRN          010
21138971  A1LB34  BRA1LBBDR008  ALBEMARLE CO           DRN          010

               data
21138963 2026-09-23
11024187 2023-05-17
10004395 2022-12-05
21106694 2026-09-21
21123319 2026-09-22
21138964 2026-09-23
21138965 2026-09-23
19855660 2026-06-03
21138966 2026-09-23
20923774 2026-09-04
21138967 2026-09-23
21138968 2026-09-23
20850892 2026-08-31
21106701 2026-09-21
20994002 2026-09-11
20485729 2026-07-31
21138969 2026-09-23
20783373 2026-08-25
21138970 2026-09-23
21138971 2026-09-23

In [67]:
df_instrumentos_acoes = df_instrumentos[
    (
        df_instrumentos["especificacao"]
        .astype(str)
        .str.upper()
        .str.startswith(("ON", "PN"))
    )
    &
    (
        df_instrumentos["ticker"]
        .astype(str)
        .str.fullmatch(r"[A-Z]{4}[3-8]", na=False)
    )
].copy()

In [68]:
print(df_instrumentos_acoes.shape)
print(df_instrumentos_acoes["ticker"].nunique())

print(
    df_instrumentos_acoes[
        ["ticker", "isin", "nome_empresa", "especificacao"]
    ].head(30)
)

(911, 6)
911
         ticker          isin  nome_empresa especificacao
21139000  AALR3  BRAALRACNOR6        ALLIAR    ON      NM
21139008  ABCB4  BRABCBACNPR4    ABC BRASIL    PN      N2
21139042  ABEV3  BRABEVACNOR1     AMBEV S/A        ON  EJ
794555    ABNB3  BRABNBACNOR4        ABNOTE    ON      NM
2462266   ABRE3  BRABREACNOR9   ABRIL EDUCA    ON      NM
583709    ABYA3  BRABYAACNOR3        ABYARA    ON      NM
90446     ACES3  BRACESACNOR5    AM INOX BR            ON
94243     ACES4  BRACESACNPR2    AM INOX BR            PN
725295    ACGU3  BRACGUACNOR6       GUARANI    ON      NM
6200933   ADHM3  BRADHMACNOR9   ADVANCED-DH            ON
19200522  ADMF3  BRADMFACNOR3      CIABRASF    ON      NM
2031750   AEDU3  BRAEDUACNOR9    ANHANGUERA    ON      NM
3996883   AELP3  BRAELPACNOR2      AES ELPA            ON
21139219  AERI3  BRAERIACNOR4         AERIS    ON      NM
14612930  AESB3  BRAESBACNOR7    AES BRASIL    ON      NM
21139223  AFLT3  BRAFLTACNOR1    AFLUENTE T            ON
3553408   AFLU3  BRAFLUACNOR9      AFLUENTE            ON
3555455   AFLU5  BRAFLUACNPA2      AFLUENTE           PNA
677844    AGEI3  BRAGEIACNOR7  AGRE EMP IMO    ON      NM
583722    AGIN3  BRAGINACNOR8   AGRA INCORP    ON      NM
21139227  AGRO3  BRAGROACNOR7    BRASILAGRO    ON      NM
21139233  AGXY3  BRAGXYACNOR4    AGROGALAXY    ON      NM
20941919  AHEB3  BRAHEBACNOR0       SPTURIS            ON
16572993  AHEB5  BRAHEBACNPA3       SPTURIS           PNA
16171751  AHEB6  BRAHEBACNPB1       SPTURIS           PNB
21139238  ALLD3  BRALLDACNOR3        ALLIED    ON      NM
2334011   ALLL3  BRALLLACNOR6  ALL AMER LAT    ON      NM
780700    ALLL4  BRALLLACNPR3  ALL AMER LAT    PN      N2
21139240  ALOS3  BRALOSACNOR5         ALLOS    ON  ED  NM
21139382  ALPA3  BRALPAACNOR0    ALPARGATAS    ON      N1

In [72]:
# ============================================================
# MAPEAMENTO B3 -> CVM -> CNPJ
# ============================================================

import pandas as pd
import numpy as np
import re
import unicodedata

from rapidfuzz import process, fuzz


# ============================================================
# 1. NORMALIZAÇÃO DOS NOMES
# ============================================================

def normalizar_nome(nome):

    if pd.isna(nome):
        return ""

    nome = str(nome).upper().strip()

    # Remove acentos
    nome = unicodedata.normalize("NFKD", nome)
    nome = "".join(
        c for c in nome
        if not unicodedata.combining(c)
    )

    # Padroniza &
    nome = nome.replace("&", " E ")

    # Remove pontuação
    nome = re.sub(r"[^A-Z0-9\s]", " ", nome)

    # Remove tipos societários
    tipos_societarios = (
        r"\b(?:SA|S A|S/A|SAA|LTDA|LTD|PLC|INC|CORP|"
        r"CORPORATION|HOLDING|HOLDINGS)\b"
    )

    nome = re.sub(
        tipos_societarios,
        " ",
        nome
    )

    # Remove espaços duplicados
    nome = re.sub(r"\s+", " ", nome).strip()

    return nome


# ============================================================
# 2. PREPARAR UNIVERSO B3
# ============================================================

b3 = df_instrumentos_acoes.copy()

b3["ticker"] = (
    b3["ticker"]
    .astype(str)
    .str.strip()
    .str.upper()
)

b3["isin"] = (
    b3["isin"]
    .astype(str)
    .str.strip()
    .str.upper()
)

b3["nome_norm"] = (
    b3["nome_empresa"]
    .apply(normalizar_nome)
)

# Apenas tickers padrão:
# 4 letras + número de 3 a 8
b3 = b3[
    b3["ticker"].str.fullmatch(
        r"[A-Z]{4}[3-8]",
        na=False
    )
].copy()

# Apenas ON e PN
b3 = b3[
    b3["especificacao"]
    .astype(str)
    .str.upper()
    .str.split()
    .str[0]
    .isin(["ON", "PN"])
].copy()

# Remove registros sem informações necessárias
b3 = b3.dropna(
    subset=[
        "ticker",
        "isin",
        "nome_norm"
    ]
).copy()

# Uma observação por ticker + ISIN
b3 = (
    b3
    .sort_values("data")
    .drop_duplicates(
        subset=["ticker", "isin"],
        keep="last"
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("UNIVERSO B3")
print("=" * 70)
print("Linhas:", len(b3))
print("Tickers:", b3["ticker"].nunique())
print("ISINs:", b3["isin"].nunique())


# ============================================================
# 3. PREPARAR CADASTRO CVM
# ============================================================

cvm = df_capital_social.copy()

cvm["CNPJ_Companhia"] = (
    cvm["CNPJ_Companhia"]
    .astype(str)
    .str.strip()
)

cvm["nome_norm"] = (
    cvm["Nome_Companhia"]
    .apply(normalizar_nome)
)

cvm = cvm.dropna(
    subset=[
        "CNPJ_Companhia",
        "nome_norm"
    ]
).copy()


# ============================================================
# 4. UMA LINHA POR EMPRESA DA CVM
# ============================================================

cvm_empresas = (
    cvm[
        [
            "CNPJ_Companhia",
            "Nome_Companhia",
            "nome_norm"
        ]
    ]
    .drop_duplicates(
        subset=["CNPJ_Companhia"]
    )
    .reset_index(drop=True)
)

print()
print("=" * 70)
print("CADASTRO CVM")
print("=" * 70)
print("Empresas:", len(cvm_empresas))
print(
    "CNPJs:",
    cvm_empresas["CNPJ_Companhia"].nunique()
)


# ============================================================
# 5. LISTA DE NOMES CVM
# ============================================================

nomes_cvm = (
    cvm_empresas["nome_norm"]
    .tolist()
)


# ============================================================
# 6. FUZZY MATCH
# ============================================================

resultados = []

for _, row in b3.iterrows():

    nome_b3 = row["nome_norm"]

    matches = process.extract(
        nome_b3,
        nomes_cvm,
        scorer=fuzz.token_set_ratio,
        limit=3
    )

    for nome_match, score, idx in matches:

        empresa_cvm = cvm_empresas.iloc[idx]

        resultados.append({
            "ticker": row["ticker"],
            "isin": row["isin"],
            "nome_b3": row["nome_empresa"],
            "nome_cvm": empresa_cvm["Nome_Companhia"],
            "CNPJ": empresa_cvm["CNPJ_Companhia"],
            "score": score
        })


df_matches = pd.DataFrame(resultados)


# ============================================================
# 7. CLASSIFICAR QUALIDADE
# ============================================================

df_matches["qualidade"] = np.select(
    [
        df_matches["score"] >= 95,
        df_matches["score"] >= 85,
        df_matches["score"] >= 75
    ],
    [
        "ALTO",
        "MEDIO",
        "BAIXO"
    ],
    default="REVISAR"
)


# ============================================================
# 8. MELHOR MATCH POR TICKER
# ============================================================

mapping_preliminar = (
    df_matches
    .sort_values(
        ["ticker", "score"],
        ascending=[True, False]
    )
    .drop_duplicates(
        subset=["ticker"]
    )
    .reset_index(drop=True)
)


# ============================================================
# 9. MATCHES ACEITOS
# ============================================================

mapping_validado = (
    mapping_preliminar[
        mapping_preliminar["score"] >= 85
    ]
    .copy()
    .reset_index(drop=True)
)


# ============================================================
# 10. MATCHES PARA REVISÃO
# ============================================================

mapping_revisar = (
    mapping_preliminar[
        mapping_preliminar["score"] < 85
    ]
    .copy()
    .reset_index(drop=True)
)


# ============================================================
# 11. ESTATÍSTICAS
# ============================================================

print()
print("=" * 70)
print("RESULTADO DO FUZZY MATCH")
print("=" * 70)

print(
    "Tickers B3:",
    len(mapping_preliminar)
)

print(
    "Score >= 95:",
    (mapping_preliminar["score"] >= 95).sum()
)

print(
    "Score 85-94:",
    (
        (mapping_preliminar["score"] >= 85)
        &
        (mapping_preliminar["score"] < 95)
    ).sum()
)

print(
    "Score 75-84:",
    (
        (mapping_preliminar["score"] >= 75)
        &
        (mapping_preliminar["score"] < 85)
    ).sum()
)

print(
    "Score < 75:",
    (mapping_preliminar["score"] < 75).sum()
)


# ============================================================
# 12. DISTRIBUIÇÃO DA QUALIDADE
# ============================================================

print()
print("QUALIDADE:")
print(
    mapping_preliminar["qualidade"]
    .value_counts()
)


# ============================================================
# 13. MELHORES MATCHES
# ============================================================

print()
print("=" * 70)
print("PRIMEIROS MATCHES")
print("=" * 70)

print(
    mapping_preliminar[
        [
            "ticker",
            "isin",
            "nome_b3",
            "nome_cvm",
            "CNPJ",
            "score",
            "qualidade"
        ]
    ]
    .sort_values(
        "score",
        ascending=False
    )
    .head(30)
    .to_string(index=False)
)


# ============================================================
# 14. MATCHES PROBLEMÁTICOS
# ============================================================

print()
print("=" * 70)
print("MATCHES PARA REVISÃO")
print("=" * 70)

print(
    mapping_revisar[
        [
            "ticker",
            "isin",
            "nome_b3",
            "nome_cvm",
            "CNPJ",
            "score",
            "qualidade"
        ]
    ]
    .sort_values(
        "score",
        ascending=True
    )
    .head(50)
    .to_string(index=False)
)


# ============================================================
# 15. TOP 3 CANDIDATOS DOS MATCHES DUVIDOSOS
# ============================================================

tickers_revisar = (
    mapping_revisar["ticker"]
    .tolist()
)

df_candidatos_revisao = (
    df_matches[
        df_matches["ticker"]
        .isin(tickers_revisar)
    ]
    .sort_values(
        ["ticker", "score"],
        ascending=[True, False]
    )
)

print()
print("=" * 70)
print("TOP 3 CANDIDATOS DOS MATCHES DUVIDOSOS")
print("=" * 70)

print(
    df_candidatos_revisao[
        [
            "ticker",
            "isin",
            "nome_b3",
            "nome_cvm",
            "CNPJ",
            "score"
        ]
    ]
    .head(100)
    .to_string(index=False)
)


# ============================================================
# 16. MAPPING FINAL
# ============================================================

mapping_validado = (
    mapping_validado[
        [
            "ticker",
            "isin",
            "nome_b3",
            "nome_cvm",
            "CNPJ",
            "score",
            "qualidade"
        ]
    ]
    .drop_duplicates(
        subset=["ticker"]
    )
    .reset_index(drop=True)
)


# ============================================================
# 17. RESUMO
# ============================================================

print()
print("=" * 70)
print("RESUMO FINAL")
print("=" * 70)

print(
    f"Universo B3:          {b3['ticker'].nunique():,}"
)

print(
    f"Mapping total:         {len(mapping_preliminar):,}"
)

print(
    f"Mapping validado:      {len(mapping_validado):,}"
)

print(
    f"Necessitam revisão:    {len(mapping_revisar):,}"
)

print(
    f"CNPJs únicos mapeados: "
    f"{mapping_validado['CNPJ'].nunique():,}"
)

======================================================================
UNIVERSO B3
======================================================================
Linhas: 822
Tickers: 822
ISINs: 822

======================================================================
CADASTRO CVM
======================================================================
Empresas: 1230
CNPJs: 1230

======================================================================
RESULTADO DO FUZZY MATCH
======================================================================
Tickers B3: 822
Score >= 95: 479
Score 85-94: 24
Score 75-84: 83
Score < 75: 236

QUALIDADE:
qualidade
ALTO       479
REVISAR    236
BAIXO       83
MEDIO       24
Name: count, dtype: int64

======================================================================
PRIMEIROS MATCHES
======================================================================
ticker         isin      nome_b3                                 nome_cvm               CNPJ  score qualidade
 ISAE4 BRISAEACNPR9  ISA ENERGIA                       ISA ENERGIA BRASIL 02.998.611/0001-04  100.0      ALTO
 MNDL3 BRMNDLACNOR4      MUNDIAL       MUNDIAL S.A. - PRODUTOS DE CONSUMO 88.610.191/0001-54  100.0      ALTO
 LREN3 BRLRENACNOR1 LOJAS RENNER                        LOJAS RENNER S.A. 92.754.738/0001-62  100.0      ALTO
 LUPA3 BRLUPAACNOR8     LUPATECH                             LUPATECH S.A 89.463.822/0001-12  100.0      ALTO
 LUXM3 BRLUXMACNOR7      TREVISA               TREVISA INVESTIMENTOS S.A. 92.660.570/0001-26  100.0      ALTO
 LUXM4 BRLUXMACNPR4      TREVISA               TREVISA INVESTIMENTOS S.A. 92.660.570/0001-26  100.0      ALTO
 LWSA3 BRLWSAACNOR8         LWSA                                 LWSA S/A 02.351.877/0001-52  100.0      ALTO
 MAGG3 BRMAGGACNOR4 MAGNESITA SA               MAGNESITA REFRATARIOS S.A. 08.684.547/0001-65  100.0      ALTO
 MAGS3 BRMAGSACNOR9    MAGNESITA               MAGNESITA REFRATARIOS S.A. 08.684.547/0001-65  100.0      ALTO
 MAPT3 BRMAPTACNOR8       CEMEPE                CEMEPE INVESTIMENTOS S.A. 93.828.986/0001-73  100.0      ALTO
 MAPT4 BRMAPTACNPR5       CEMEPE                CEMEPE INVESTIMENTOS S.A. 93.828.986/0001-73  100.0      ALTO
 MARI3 BRMARIACNOR7       MARISA                        MARISA LOJAS S.A. 61.189.288/0001-89  100.0      ALTO
 MATD3 BRMATDACNOR4    MATER DEI                  HOSPITAL MATER DEI S.A. 16.676.520/0001-59  100.0      ALTO
 MBRF3 BRMBRFACNOR1      MARFRIG                MARFRIG GLOBAL FOODS S.A. 03.853.896/0001-40  100.0      ALTO
 MDNE3 BRMDNEACNOR9 MOURA DUBEUX              MOURA DUBEUX ENGENHARIA S/A 12.049.631/0001-84  100.0      ALTO
 MELK3 BRMELKACNOR8      MELNICK MELNICK DESENVOLVIMENTO IMOBILIÁRIO S.A. 12.181.987/0001-77  100.0      ALTO
 MILS3 BRMILSACNOR2        MILLS MILLS LOCAÇÃO, SERVIÇOS E LOGÍSTICA S.A. 27.093.558/0001-15  100.0      ALTO
 LOGN3 BRLOGNACNOR3       LOG-IN         LOG-IN LOGISTICA INTERMODAL S.A. 42.278.291/0001-24  100.0      ALTO
 LJQQ3 BRLJQQACNOR5  QUERO-QUERO                   LOJAS QUERO QUERO S.A. 96.418.264/0218-02  100.0      ALTO
 LIXC4 BRLIXCACNPR0 LIX DA CUNHA            CONSTRUTORA LIX DA CUNHA S.A. 46.014.635/0001-49  100.0      ALTO
 LAVV3 BRLAVVACNOR4        LAVVI  LAVVI EMPREENDIMENTOS IMOBILIÁRIOS S.A. 26.462.693/0001-28  100.0      ALTO
 JOPA4 BRJOPAACNPR2      JOSAPAR JOSAPAR-JOAQUIM OLIVEIRA S.A. - PARTICIP 87.456.562/0001-22  100.0      ALTO
 JSLG3 BRJSLGACNOR2          JSL                                 JSL S.A. 52.548.435/0001-79  100.0      ALTO
 KEPL3 BRKEPLACNOR1 KEPLER WEBER                        KEPLER WEBER S.A. 91.983.056/0001-69  100.0      ALTO
 KLBN3 BRKLBNACNOR2   KLABIN S/A                        KLABIN SEGALL S/A 00.187.032/0001-48  100.0      ALTO
 KLBN4 BRKLBNACNPR9   KLABIN S/A                        KLABIN SEGALL S/A 00.187.032/0001-48  100.0      ALTO
 KRSA3 BRKRSAACNOR0   KORA SAUDE            KORA SAÚDE PARTICIPAÇÕES S.A. 13.270.520/0001-66  100.0      ALTO
 LCAM3 BRLCAMACNOR3   LOCAMERICA               LOCAMÉRICA RENT-A-CAR S.A. 04.437.534/0001-30  100.0      ALTO
 LIXC3 BRLIXCACNOR3 LIX DA CUNHA            CONSTRUTORA LIX DA CUNHA S.A. 46.014.635/0001-49  100.0      ALTO
 LEVE3 BRLEVEACNOR2   METAL LEVE                    MAHLE METAL LEVE S.A. 60.476.884/0001-87  100.0      ALTO

======================================================================
MATCHES PARA REVISÃO
======================================================================
ticker         isin      nome_b3                                 nome_cvm               CNPJ     score qualidade
 GLOB3 BRGLOBACNOR8       GLOBEX                             BIONEXO S.A. 04.069.709/0001-02 46.153846   REVISAR
 GLOB4 BRGLOBACNPR5       GLOBEX                             BIONEXO S.A. 04.069.709/0001-02 46.153846   REVISAR
 RJCP3 BRRJCPACNOR4         RJCP                           MARCOPOLO S.A. 88.611.835/0001-29 46.153846   REVISAR
 DMVF3 BRDMVFACNOR9  D1000VFARMA    D1000 VAREJO FARMA PARTICIPAÇÕES S.A. 12.108.897/0001-50 46.511628   REVISAR
 DOMO3 BRDOMOACNOR6 DOMUS POPULI                               HOUSI S.A. 15.675.715/0001-11 47.058824   REVISAR
 SHOW3 BRSHOWACNOR7 TIME FOR FUN                    BRZ INVESTIMENTOS S/A 03.468.802/0001-19 48.275862   REVISAR
 TBLE3 BRTBLEACNOR2    TRACTEBEL                 TEREOS INTERNACIONAL S/A 11.566.501/0001-56 48.275862   REVISAR
 CCPR3 BRCCPRACNOR9 CYRE COM-CCP                   RET PARTICIPACOES S.A. 02.363.917/0001-86 48.275862   REVISAR
 BOVH3 BRBOVHACNOR5  BOVESPA HLD                           BRADESPAR S.A. 03.847.461/0001-92 50.000000   REVISAR
 TIBR3 BRTIBRACNOR0   MILLENNIUM                              SMILES S.A. 15.912.764/0001-20 50.000000   REVISAR
 ARLA4 BRARLAACNPR3 ARTHUR LANGE                        SAO MARTINHO S.A. 51.466.860/0001-56 50.000000   REVISAR
 ARLA3 BRARLAACNOR6 ARTHUR LANGE                        SAO MARTINHO S.A. 51.466.860/0001-56 50.000000   REVISAR
 MBLY3 BRMBLYACNOR5        MOBLY                               MARISOL SA 84.429.752/0001-62 50.000000   REVISAR
 VCPA3 BRVCPAACNOR5        V C P                             BCO PAN S.A. 59.285.411/0001-13 50.000000   REVISAR
 PDGR3 BRPDGRACNOR8    PDG REALT PDG REALTY S.A. EMPREEND E PARTICIPACOES 02.950.811/0001-89 50.000000   REVISAR
 CCRO3 BRCCROACNOR2       CCR SA                          R/HOLDINGS S.A. 52.475.549/0001-36 50.000000   REVISAR
 CRDE3 BRCRDEACNOR1          CR2                          R/HOLDINGS S.A. 52.475.549/0001-36 50.000000   REVISAR
 DHBI3 BRDHBIACNOR5        D H B                                 JBS N.V. 49.115.815/0001-05 50.000000   REVISAR
 DHBI4 BRDHBIACNPR2        D H B                                 JBS N.V. 49.115.815/0001-05 50.000000   REVISAR
 VCPA4 BRVCPAACNPR2        V C P                             BCO PAN S.A. 59.285.411/0001-13 50.000000   REVISAR
 PTIP3 BRPTIPACNOR4 IPIRANGA PET             UNIÃO PET PARTICIPAÇÕES S.A. 53.153.938/0001-08 51.428571   REVISAR
 PTIP4 BRPTIPACNPR1 IPIRANGA PET             UNIÃO PET PARTICIPAÇÕES S.A. 53.153.938/0001-08 51.428571   REVISAR
 AGEI3 BRAGEIACNOR7 AGRE EMP IMO                           C&A MODAS S.A. 45.242.914/0001-05 52.173913   REVISAR
 CARD3 BRCARDACNOR9 CSU CARDSYST                         CSU DIGITAL S.A. 01.896.779/0001-38 52.173913   REVISAR
 PLPL3 BRPLPLACNOR5  PLANOEPLANO                        PANATLANTICA S.A. 92.693.019/0001-89 52.173913   REVISAR
 WDCN3 BRWDCNACNOR2 WDC NETWORKS                 ANEMUS WIND HOLDING S.A. 38.482.780/0001-26 52.173913   REVISAR
 LVTC3 BRLVTCACNOR4 WDC NETWORKS                 ANEMUS WIND HOLDING S.A. 38.482.780/0001-26 52.173913   REVISAR
 BTTL4 BRBTTLACNPR7  BATTISTELLA                            AES ELPA S.A. 01.917.705/0001-30 52.631579   REVISAR
 BTTL3 BRBTTLACNOR0  BATTISTELLA                            AES ELPA S.A. 01.917.705/0001-30 52.631579   REVISAR
 CRFB3 BRCRFBACNOR2 CARREFOUR BR                             EMBRAER S.A. 07.689.002/0001-89 52.631579   REVISAR
 ECOD3 BRECODACNOR8    ECODIESEL                          CINESYSTEM S.A. 07.437.016/0001-05 52.631579   REVISAR
 VAGV4 BRVAGVACNPR1       SAVARG                       BRAVA ENERGIA S.A. 12.091.809/0001-55 52.631579   REVISAR
 VAGV3 BRVAGVACNOR4       SAVARG                       BRAVA ENERGIA S.A. 12.091.809/0001-55 52.631579   REVISAR
 VTLM3 BRVTLMACNOR3  VITALYZE.ME                                VALE S.A. 33.592.510/0001-54 53.333333   REVISAR
 DURA4 BRDURAACNPR8      DURATEX                            IGUATEMI S.A. 60.543.816/0001-93 53.333333   REVISAR
 CLSC4 BRCLSCACNPR3       CELESC                           TELINVEST S.A. 02.476.710/0001-18 53.333333   REVISAR
 CLSC3 BRCLSCACNOR6       CELESC                           TELINVEST S.A. 02.476.710/0001-18 53.333333   REVISAR
 RIPI3 BRRIPIACNOR3 IPIRANGA REF                  RIO PARANA ENERGIA S.A. 23.096.269/0001-19 53.333333   REVISAR
 RIPI4 BRRIPIACNPR0 IPIRANGA REF                  RIO PARANA ENERGIA S.A. 23.096.269/0001-19 53.333333   REVISAR
 DTEX3 BRDTEXACNOR3      DURATEX                            IGUATEMI S.A. 60.543.816/0001-93 53.333333   REVISAR
 ARCZ3 BRARCZACNOR2      ARACRUZ                            RECRUSUL S.A. 91.333.666/0001-17 53.333333   REVISAR
 DURA3 BRDURAACNOR1      DURATEX                            IGUATEMI S.A. 60.543.816/0001-93 53.333333   REVISAR
 SMFT3 BRSMFTACNOR1    SMART FIT                              GAFISA S.A. 01.545.826/0001-07 53.333333   REVISAR
 LOGG3 BRLOGGACNOR7 LOG COM PROP                        PRÓ METALURGIA SA 56.994.924/0001-05 53.846154   REVISAR
 ALSO3 BRALSOACNOR5 ALIANSCSONAE           ALIANSCE SHOPPING CENTERS S.A. 06.082.980/0001-03 54.054054   REVISAR
 CMGR4 BRCMGRACNPR4        CEMAT                                CREMER SA 82.641.325/0001-18 54.545455   REVISAR
 ALLL4 BRALLLACNPR3 ALL AMER LAT                 SERRA AZUL WATER PARK SA 00.545.378/0001-70 54.545455   REVISAR
 CMGR3 BRCMGRACNOR7        CEMAT                                CREMER SA 82.641.325/0001-18 54.545455   REVISAR
 LAND3 BRLANDACNOR9 TERRASANTAPA                          EPR PARANA S.A. 60.978.495/0001-50 54.545455   REVISAR
 ALLL3 BRALLLACNOR6 ALL AMER LAT                 SERRA AZUL WATER PARK SA 00.545.378/0001-70 54.545455   REVISAR

======================================================================
TOP 3 CANDIDATOS DOS MATCHES DUVIDOSOS
======================================================================
ticker         isin      nome_b3                                         nome_cvm               CNPJ     score
 AALR3 BRAALRACNOR6       ALLIAR                               ALFA HOLDINGS S.A. 17.167.396/0001-69 60.000000
 AALR3 BRAALRACNOR6       ALLIAR                                        RAIA S.A. 60.605.664/0001-06 60.000000
 AALR3 BRAALRACNOR6       ALLIAR                                    ALIPERTI S.A. 61.156.931/0001-78 57.142857
 ABNB3 BRABNBACNOR4       ABNOTE                                     VIANORTE S/A 02.366.097/0001-86 71.428571
 ABNB3 BRABNBACNOR4       ABNOTE                                 BANCO INTER S.A. 00.416.968/0001-01 58.823529
 ABNB3 BRABNBACNOR4       ABNOTE                                       AMBEV S.A. 07.526.557/0001-00 54.545455
 ABRE3 BRABREACNOR9  ABRIL EDUCA                                EDITORA ABRIL S/A 02.183.757/0001-93 75.000000
 ABRE3 BRABREACNOR9  ABRIL EDUCA                              BIOMA EDUCAÇÃO S.A. 45.987.245/0001-92 64.000000
 ABRE3 BRABREACNOR9  ABRIL EDUCA                            TELEFÔNICA BRASIL S.A 02.558.157/0001-62 57.142857
 ABYA3 BRABYAACNOR3       ABYARA                                         BGPAR SA 04.987.555/0001-20 54.545455
 ABYA3 BRABYAACNOR3       ABYARA                                   VULCABRAS S.A. 50.926.955/0001-42 53.333333
 ABYA3 BRABYAACNOR3       ABYARA                               YBYRÁ CAPITAL S.A. 02.217.319/0001-07 52.631579
 ACES3 BRACESACNOR5   AM INOX BR                                     AQUA-RIO S/A 11.197.023/0001-54 55.555556
 ACES3 BRACESACNOR5   AM INOX BR                        AURA ALMAS MINERAÇÃO S.A. 08.213.823/0001-07 53.333333
 ACES3 BRACESACNOR5   AM INOX BR                                EDITORA ABRIL S/A 02.183.757/0001-93 52.173913
 ACES4 BRACESACNPR2   AM INOX BR                                     AQUA-RIO S/A 11.197.023/0001-54 55.555556
 ACES4 BRACESACNPR2   AM INOX BR                        AURA ALMAS MINERAÇÃO S.A. 08.213.823/0001-07 53.333333
 ACES4 BRACESACNPR2   AM INOX BR                                EDITORA ABRIL S/A 02.183.757/0001-93 52.173913
 ACGU3 BRACGUACNOR6      GUARANI                                      PARSAN S.A. 44.854.238/0001-50 61.538462
 ACGU3 BRACGUACNOR6      GUARANI                          GUARARAPES PAINÉIS S.A. 08.810.422/0001-34 56.000000
 ACGU3 BRACGUACNOR6      GUARANI                                        RAIA S.A. 60.605.664/0001-06 54.545455
 ADHM3 BRADHMACNOR9  ADVANCED-DH ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A. 10.345.009/0001-98 84.210526
 ADHM3 BRADHMACNOR9  ADVANCED-DH                                   C&A MODAS S.A. 45.242.914/0001-05 45.454545
 ADHM3 BRADHMACNOR9  ADVANCED-DH                                 BANCO MODAL S.A. 30.723.886/0001-62 45.454545
 ADMF3 BRADMFACNOR3     CIABRASF                                   VULCABRAS S.A. 50.926.955/0001-42 70.588235
 ADMF3 BRADMFACNOR3     CIABRASF                                    COBRASMA S.A. 61.080.313/0001-91 62.500000
 ADMF3 BRADMFACNOR3     CIABRASF                                    INBRANDS S.A. 09.054.385/0001-44 62.500000
 AESB3 BRAESBACNOR7   AES BRASIL                                  EBX BRASIL S.A. 10.847.761/0001-37 80.000000
 AESB3 BRAESBACNOR7   AES BRASIL                                  BCO BRASIL S.A. 00.000.000/0001-91 75.000000
 AESB3 BRAESBACNOR7   AES BRASIL                        ENGIE BRASIL ENERGIA S.A. 02.474.103/0001-19 75.000000
 AGEI3 BRAGEIACNOR7 AGRE EMP IMO                                   C&A MODAS S.A. 45.242.914/0001-05 52.173913
 AGEI3 BRAGEIACNOR7 AGRE EMP IMO                                  AGRENCO LIMITED 08.943.312/0001-40 51.851852
 AGEI3 BRAGEIACNOR7 AGRE EMP IMO                          TEMPO PARTICIPAÇOES S/A 06.977.739/0001-34 51.612903
 AGIN3 BRAGINACNOR8  AGRA INCORP                                     INNCORP S.A. 02.604.860/0001-60 66.666667
 AGIN3 BRAGINACNOR8  AGRA INCORP                                  RANDONCORP S.A. 89.086.144/0001-16 66.666667
 AGIN3 BRAGINACNOR8  AGRA INCORP                           FGR INCORPORAÇÕES S.A. 02.171.304/0001-47 64.285714
 AHEB3 BRAHEBACNOR0      SPTURIS                                      TRISUL S.A. 08.811.643/0001-27 61.538462
 AHEB3 BRAHEBACNOR0      SPTURIS                                     ARTERIS S.A. 02.919.555/0001-67 57.142857
 AHEB3 BRAHEBACNOR0      SPTURIS                               SLOT URBANISMO S/A 31.910.308/0001-06 57.142857
 ALLL3 BRALLLACNOR6 ALL AMER LAT                         SERRA AZUL WATER PARK SA 00.545.378/0001-70 54.545455
 ALLL3 BRALLLACNOR6 ALL AMER LAT                                  ALPARGATAS S.A. 61.079.117/0001-05 54.545455
 ALLL3 BRALLLACNOR6 ALL AMER LAT                                 SUL AMERICA S.A. 29.978.814/0001-87 52.173913
 ALLL4 BRALLLACNPR3 ALL AMER LAT                         SERRA AZUL WATER PARK SA 00.545.378/0001-70 54.545455
 ALLL4 BRALLLACNPR3 ALL AMER LAT                                  ALPARGATAS S.A. 61.079.117/0001-05 54.545455
 ALLL4 BRALLLACNPR3 ALL AMER LAT                                 SUL AMERICA S.A. 29.978.814/0001-87 52.173913
 ALPK3 BRALPKACNOR9      ESTAPAR                                      BELAPART SA 01.608.571/0001-76 66.666667
 ALPK3 BRALPKACNOR9      ESTAPAR                                   BRADESPAR S.A. 03.847.461/0001-92 62.500000
 ALPK3 BRALPKACNOR9      ESTAPAR                                      SIMPAR S.A. 07.415.333/0001-20 61.538462
 ALSO3 BRALSOACNOR5 ALIANSCSONAE                   ALIANSCE SHOPPING CENTERS S.A. 06.082.980/0001-03 54.054054
 ALSO3 BRALSOACNOR5 ALIANSCSONAE                        SOLA SA INDS ALIMENTICIAS 32.286.411/0001-81 52.941176
 ALSO3 BRALSOACNOR5 ALIANSCSONAE                                 BANCO INTER S.A. 00.416.968/0001-01 52.173913
 AMPI3 BRAMPIACNOR1 AMPLA INVEST                    SANTA CATARINA PART INVEST SA 00.897.864/0001-58 66.666667
 AMPI3 BRAMPIACNOR1 AMPLA INVEST                                   TELINVEST S.A. 02.476.710/0001-18 66.666667
 AMPI3 BRAMPIACNOR1 AMPLA INVEST           TPI - TRIUNFO PARTICIP. E INVEST. S.A. 03.014.553/0001-91 66.666667
 AORE3 BRAOREACNOR2      ALL ORE                                       ALLOS S.A. 05.878.397/0001-32 66.666667
 AORE3 BRAOREACNOR2      ALL ORE                           ORE  SECURITIZADORA SA 12.320.349/0001-90 60.000000
 AORE3 BRAOREACNOR2      ALL ORE                                 CANTU STORE S.A. 41.096.674/0001-19 55.555556
 ARCZ3 BRARCZACNOR2      ARACRUZ                                    RECRUSUL S.A. 91.333.666/0001-17 53.333333
 ARCZ3 BRARCZACNOR2      ARACRUZ                                TAURUS ARMAS S.A. 92.781.335/0001-02 52.631579
 ARCZ3 BRARCZACNOR2      ARACRUZ                                    SOUZA CRUZ SA 33.009.911/0001-39 47.058824
 ARLA3 BRARLAACNOR6 ARTHUR LANGE                                SAO MARTINHO S.A. 51.466.860/0001-56 50.000000
 ARLA3 BRARLAACNOR6 ARTHUR LANGE                               AURA MINERALS INC. 07.857.093/0001-14 48.000000
 ARLA3 BRARLAACNOR6 ARTHUR LANGE                               AUREN ENERGIA S.A. 28.594.234/0001-23 48.000000
 ARLA4 BRARLAACNPR3 ARTHUR LANGE                                SAO MARTINHO S.A. 51.466.860/0001-56 50.000000
 ARLA4 BRARLAACNPR3 ARTHUR LANGE                               AURA MINERALS INC. 07.857.093/0001-14 48.000000
 ARLA4 BRARLAACNPR3 ARTHUR LANGE                               AUREN ENERGIA S.A. 28.594.234/0001-23 48.000000
 ARZZ3 BRARZZACNOR3    AREZZO CO                                BCO AMAZONIA S.A. 04.902.979/0001-44 57.142857
 ARZZ3 BRARZZACNOR3    AREZZO CO                          NATURA &CO HOLDING S.A. 32.785.497/0001-97 50.000000
 ARZZ3 BRARZZACNOR3    AREZZO CO                             AUREN OPERAÇÕES S.A. 00.194.724/0001-13 50.000000
 ASAI3 BRASAIACNOR0        ASSAI                                        SAUIPE SA 00.866.577/0001-80 54.545455
 ASAI3 BRASAIACNOR0        ASSAI                                      GAFISA S.A. 01.545.826/0001-07 54.545455
 ASAI3 BRASAIACNOR0        ASSAI                                      ITAÚSA S.A. 61.532.644/0001-15 54.545455
 ATED3 BRATEDACNOR1    ATOM EDUC                     ATOM EDUCAÇÃO E EDITORA S.A. 23.994.857/0001-70 61.538462
 ATED3 BRATEDACNOR1    ATOM EDUC                              BIOMA EDUCAÇÃO S.A. 45.987.245/0001-92 60.869565
 ATED3 BRATEDACNOR1    ATOM EDUC                                   AUTOMETAL S.A. 59.104.513/0001-95 55.555556
 ATOM3 BRATOMACNOR1      ATOMPAR                                   AUTOMETAL S.A. 59.104.513/0001-95 62.500000
 ATOM3 BRATOMACNOR1      ATOMPAR                                      POLPAR S.A. 59.789.545/0001-71 61.538462
 ATOM3 BRATOMACNOR1      ATOMPAR                                      SIMPAR S.A. 07.415.333/0001-20 61.538462
 AUAU3 BRAUAUACNOR1   PETZCOBASI                                  BCO BRASIL S.A. 00.000.000/0001-91 60.000000
 AUAU3 BRAUAUACNOR1   PETZCOBASI                                    COBRASMA S.A. 61.080.313/0001-91 55.555556
 AUAU3 BRAUAUACNOR1   PETZCOBASI                              BCO ABC BRASIL S.A. 28.195.667/0001-06 50.000000
 AVIL3 BRAVILACNOR1    ACOS VILL                                 AÇOS VILLARES SA 60.664.810/0001-74 81.818182
 AVIL3 BRAVILACNOR1    ACOS VILL                             BORRACHAS VIPAL S.A. 87.870.952/0001-44 58.333333
 AVIL3 BRAVILACNOR1    ACOS VILL                                  BCO BRASIL S.A. 00.000.000/0001-91 52.631579
 AZTE3 BRAZTEACNOR4  AZT ENERGIA                              RAIZEN ENERGIA S.A. 08.070.508/0001-78 80.000000

In [71]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.6-cp311-cp311-macosx_10_9_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.6-cp311-cp311-macosx_10_9_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 15.6 MB/s eta 0:00:0000:0100:01
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.6

In [73]:
# ============================================================
# MATCHING B3 -> CVM MELHORADO
# ============================================================

import pandas as pd
import numpy as np
import re
import unicodedata

from rapidfuzz import process, fuzz


# ============================================================
# 1. NORMALIZAÇÃO
# ============================================================

def normalizar_nome(nome):

    if pd.isna(nome):
        return ""

    nome = str(nome).upper().strip()

    # Acentos
    nome = unicodedata.normalize("NFKD", nome)
    nome = "".join(
        c for c in nome
        if not unicodedata.combining(c)
    )

    # Padronização
    nome = nome.replace("&", " E ")

    # Pontuação
    nome = re.sub(r"[^A-Z0-9\s]", " ", nome)

    # Tipos societários
    nome = re.sub(
        r"\b(?:SA|S A|S/A|SAA|LTDA|LTD|PLC|INC|CORP|"
        r"CORPORATION|HOLDING|HOLDINGS)\b",
        " ",
        nome
    )

    # Espaços
    nome = re.sub(r"\s+", " ", nome).strip()

    return nome


# ============================================================
# 2. PREPARAR B3
# ============================================================

b3 = df_instrumentos_acoes.copy()

b3["ticker"] = (
    b3["ticker"]
    .astype(str)
    .str.strip()
    .str.upper()
)

b3["isin"] = (
    b3["isin"]
    .astype(str)
    .str.strip()
    .str.upper()
)

b3["nome_norm"] = (
    b3["nome_empresa"]
    .apply(normalizar_nome)
)

# Somente tickers padrão
b3 = b3[
    b3["ticker"].str.fullmatch(
        r"[A-Z]{4}[3-8]",
        na=False
    )
].copy()

# Somente ON / PN
b3 = b3[
    b3["especificacao"]
    .astype(str)
    .str.upper()
    .str.split()
    .str[0]
    .isin(["ON", "PN"])
].copy()

# Um registro por ticker
b3 = (
    b3
    .sort_values("data")
    .drop_duplicates("ticker")
    .reset_index(drop=True)
)


# ============================================================
# 3. PREPARAR CVM
# ============================================================

cvm = df_capital_social.copy()

cvm["CNPJ_Companhia"] = (
    cvm["CNPJ_Companhia"]
    .astype(str)
    .str.strip()
)

cvm["nome_norm"] = (
    cvm["Nome_Companhia"]
    .apply(normalizar_nome)
)

cvm_empresas = (
    cvm[
        [
            "CNPJ_Companhia",
            "Nome_Companhia",
            "nome_norm"
        ]
    ]
    .drop_duplicates("CNPJ_Companhia")
    .reset_index(drop=True)
)


# ============================================================
# 4. DICIONÁRIO DE NOMES CVM
# ============================================================

nomes_cvm = cvm_empresas["nome_norm"].tolist()


# ============================================================
# 5. MATCHING COM VÁRIOS ALGORITMOS
# ============================================================

resultados = []

for _, row in b3.iterrows():

    nome_b3 = row["nome_norm"]

    # Candidatos usando vários métodos
    candidatos = set()

    for scorer in [
        fuzz.ratio,
        fuzz.partial_ratio,
        fuzz.token_sort_ratio,
        fuzz.token_set_ratio,
        fuzz.WRatio
    ]:

        matches = process.extract(
            nome_b3,
            nomes_cvm,
            scorer=scorer,
            limit=5
        )

        for _, _, idx in matches:
            candidatos.add(idx)

    # Avaliar todos os candidatos
    for idx in candidatos:

        nome_cvm = cvm_empresas.iloc[idx]["nome_norm"]

        score_ratio = fuzz.ratio(
            nome_b3,
            nome_cvm
        )

        score_partial = fuzz.partial_ratio(
            nome_b3,
            nome_cvm
        )

        score_token_sort = fuzz.token_sort_ratio(
            nome_b3,
            nome_cvm
        )

        score_token_set = fuzz.token_set_ratio(
            nome_b3,
            nome_cvm
        )

        score_wratio = fuzz.WRatio(
            nome_b3,
            nome_cvm
        )

        # Score combinado
        score_final = (
            0.15 * score_ratio
            + 0.30 * score_partial
            + 0.15 * score_token_sort
            + 0.20 * score_token_set
            + 0.20 * score_wratio
        )

        resultados.append({
            "ticker": row["ticker"],
            "isin": row["isin"],
            "nome_b3": row["nome_empresa"],
            "nome_cvm": cvm_empresas.iloc[idx]["Nome_Companhia"],
            "CNPJ": cvm_empresas.iloc[idx]["CNPJ_Companhia"],
            "score_ratio": score_ratio,
            "score_partial": score_partial,
            "score_token_sort": score_token_sort,
            "score_token_set": score_token_set,
            "score_wratio": score_wratio,
            "score_final": score_final
        })


df_matches_melhorado = pd.DataFrame(resultados)


# ============================================================
# 6. MELHOR MATCH POR TICKER
# ============================================================

mapping_preliminar = (
    df_matches_melhorado
    .sort_values(
        ["ticker", "score_final"],
        ascending=[True, False]
    )
    .drop_duplicates("ticker")
    .reset_index(drop=True)
)


# ============================================================
# 7. DIFERENÇA ENTRE PRIMEIRO E SEGUNDO CANDIDATO
# ============================================================

ranking = (
    df_matches_melhorado
    .sort_values(
        ["ticker", "score_final"],
        ascending=[True, False]
    )
    .copy()
)

ranking["rank"] = (
    ranking
    .groupby("ticker")
    .cumcount() + 1
)

melhor = (
    ranking[ranking["rank"] == 1]
    [["ticker", "score_final"]]
    .rename(columns={
        "score_final": "score_1"
    })
)

segundo = (
    ranking[ranking["rank"] == 2]
    [["ticker", "score_final"]]
    .rename(columns={
        "score_final": "score_2"
    })
)

mapping_preliminar = mapping_preliminar.merge(
    melhor,
    on="ticker",
    how="left"
)

mapping_preliminar = mapping_preliminar.merge(
    segundo,
    on="ticker",
    how="left"
)

mapping_preliminar["diferenca_score"] = (
    mapping_preliminar["score_1"]
    - mapping_preliminar["score_2"]
)


# ============================================================
# 8. CLASSIFICAÇÃO
# ============================================================

mapping_preliminar["qualidade"] = np.select(
    [
        (
            (mapping_preliminar["score_1"] >= 90)
            &
            (mapping_preliminar["diferenca_score"] >= 10)
        ),

        (
            (mapping_preliminar["score_1"] >= 85)
            &
            (mapping_preliminar["diferenca_score"] >= 7)
        ),

        (
            (mapping_preliminar["score_1"] >= 80)
            &
            (mapping_preliminar["diferenca_score"] >= 5)
        )
    ],
    [
        "ALTO",
        "MEDIO",
        "BAIXO"
    ],
    default="REVISAR"
)


# ============================================================
# 9. SEPARAR RESULTADOS
# ============================================================

mapping_validado = (
    mapping_preliminar[
        mapping_preliminar["qualidade"].isin(
            ["ALTO", "MEDIO"]
        )
    ]
    .copy()
    .reset_index(drop=True)
)

mapping_revisar = (
    mapping_preliminar[
        mapping_preliminar["qualidade"] == "REVISAR"
    ]
    .copy()
    .reset_index(drop=True)
)


# ============================================================
# 10. RESULTADOS
# ============================================================

print("=" * 70)
print("MATCHING MELHORADO")
print("=" * 70)

print(
    "Total de tickers:",
    len(mapping_preliminar)
)

print(
    "ALTO:",
    (mapping_preliminar["qualidade"] == "ALTO").sum()
)

print(
    "MEDIO:",
    (mapping_preliminar["qualidade"] == "MEDIO").sum()
)

print(
    "BAIXO:",
    (mapping_preliminar["qualidade"] == "BAIXO").sum()
)

print(
    "REVISAR:",
    (mapping_preliminar["qualidade"] == "REVISAR").sum()
)


# ============================================================
# 11. MELHORES MATCHES
# ============================================================

print()
print("=" * 70)
print("MELHORES MATCHES")
print("=" * 70)

print(
    mapping_preliminar[
        [
            "ticker",
            "isin",
            "nome_b3",
            "nome_cvm",
            "CNPJ",
            "score_1",
            "score_2",
            "diferenca_score",
            "qualidade"
        ]
    ]
    .sort_values(
        "score_1",
        ascending=False
    )
    .head(30)
    .to_string(index=False)
)


# ============================================================
# 12. MATCHES QUE PRECISAM DE REVISÃO
# ============================================================

print()
print("=" * 70)
print("MATCHES PARA REVISÃO")
print("=" * 70)

print(
    mapping_revisar[
        [
            "ticker",
            "isin",
            "nome_b3",
            "nome_cvm",
            "CNPJ",
            "score_1",
            "score_2",
            "diferenca_score"
        ]
    ]
    .sort_values(
        "score_1",
        ascending=True
    )
    .head(50)
    .to_string(index=False)
)


# ============================================================
# 13. SALVAR RESULTADOS
# ============================================================

mapping_preliminar.to_csv(
    "mapping_b3_cvm_completo.csv",
    index=False
)

mapping_validado.to_csv(
    "mapping_b3_cvm_validado.csv",
    index=False
)

mapping_revisar.to_csv(
    "mapping_b3_cvm_revisar.csv",
    index=False
)

print()
print("=" * 70)
print("ARQUIVOS GERADOS")
print("=" * 70)
print("mapping_b3_cvm_completo.csv")
print("mapping_b3_cvm_validado.csv")
print("mapping_b3_cvm_revisar.csv")

======================================================================
MATCHING MELHORADO
======================================================================
Total de tickers: 822
ALTO: 187
MEDIO: 63
BAIXO: 122
REVISAR: 450

======================================================================
MELHORES MATCHES
======================================================================
ticker         isin      nome_b3           nome_cvm               CNPJ  score_1   score_2  diferenca_score qualidade
 ZAMP3 BRZAMPACNOR5    ZAMP S.A.            ZAMP SA 13.574.594/0001-96    100.0 60.000000        40.000000      ALTO
 LINX3 BRLINXACNOR0         LINX          LINX S.A. 06.948.969/0001-75    100.0 62.000000        38.000000      ALTO
 BOBR3 BRBOBRACNOR6      BOMBRIL BOMBRIL HOLDING SA 00.257.846/0001-01    100.0 79.052632        20.947368      ALTO
 BOBR4 BRBOBRACNPR3      BOMBRIL BOMBRIL HOLDING SA 00.257.846/0001-01    100.0 79.052632        20.947368      ALTO
 KLBN4 BRKLBNACNPR9   KLABIN S/A        KLABIN S.A. 89.637.490/0001-45    100.0 86.947368        13.052632      ALTO
 KLBN3 BRKLBNACNOR2   KLABIN S/A        KLABIN S.A. 89.637.490/0001-45    100.0 86.947368        13.052632      ALTO
 KEPL3 BRKEPLACNOR1 KEPLER WEBER  KEPLER WEBER S.A. 91.983.056/0001-69    100.0 56.700000        43.300000      ALTO
 JSLG3 BRJSLGACNOR2          JSL           JSL S.A. 52.548.435/0001-79    100.0 70.666667        29.333333      ALTO
 JBSS3 BRJBSSACNOR8          JBS           JBS S.A. 02.916.265/0001-60    100.0 86.000000        14.000000      ALTO
 BRAP3 BRBRAPACNOR5    BRADESPAR     BRADESPAR S.A. 03.847.461/0001-92    100.0 65.066667        34.933333      ALTO
 BRAP4 BRBRAPACNPR2    BRADESPAR     BRADESPAR S.A. 03.847.461/0001-92    100.0 65.066667        34.933333      ALTO
 BRFS3 BRBRFSACNOR8       BRF SA           BRF S.A. 01.838.723/0001-27    100.0 73.000000        27.000000      ALTO
 ITSA4 BRITSAACNPR7       ITAUSA        ITAÚSA S.A. 61.532.644/0001-15    100.0 65.858586        34.141414      ALTO
 ITSA3 BRITSAACNOR0       ITAUSA        ITAÚSA S.A. 61.532.644/0001-15    100.0 65.858586        34.141414      ALTO
 BRKM3 BRBRKMACNOR1      BRASKEM       BRASKEM S.A. 42.150.391/0001-70    100.0 69.743590        30.256410      ALTO
 IGTI4 BRIGTIACNPR5 IGUATEMI S.A      IGUATEMI S.A. 60.543.816/0001-93    100.0 78.909091        21.090909      ALTO
 IGTI3 BRIGTIACNOR8 IGUATEMI S.A      IGUATEMI S.A. 60.543.816/0001-93    100.0 78.909091        21.090909      ALTO
 IGTA3 BRIGTAACNOR5     IGUATEMI      IGUATEMI S.A. 60.543.816/0001-93    100.0 78.909091        21.090909      ALTO
 HYPE3 BRHYPEACNOR0       HYPERA        HYPERA S.A. 02.932.074/0001-91    100.0 62.285714        37.714286      ALTO
 LHER4 BRLHERACNPR0 LOJAS HERING  LOJAS HERING S.A. 82.640.632/0001-84    100.0 73.899522        26.100478      ALTO
 BMTO4 BRBMTOACNPR6    BRASMOTOR       BRASMOTOR SA 61.084.984/0001-20    100.0 68.750000        31.250000      ALTO
 HGTX3 BRHGTXACNOR9   CIA HERING         CIA HERING 78.876.950/0001-71    100.0 73.899522        26.100478      ALTO
 BMTO3 BRBMTOACNOR9    BRASMOTOR       BRASMOTOR SA 61.084.984/0001-20    100.0 68.750000        31.250000      ALTO
 PATI4 BRPATIACNPR3 PANATLANTICA  PANATLANTICA S.A. 92.693.019/0001-89    100.0 67.088803        32.911197      ALTO
 PATI3 BRPATIACNOR6 PANATLANTICA  PANATLANTICA S.A. 92.693.019/0001-89    100.0 67.088803        32.911197      ALTO
 OFSA3 BROFSAACNOR7 OUROFINO S/A      OUROFINO S.A. 20.258.278/0001-70    100.0 61.000000        39.000000      ALTO
 NEOE3 BRNEOEACNOR3   NEOENERGIA    NEOENERGIA S.A. 01.083.200/0001-18    100.0 82.444444        17.555556      ALTO
 BIDI3 BRBIDIACNOR3  BANCO INTER   BANCO INTER S.A. 00.416.968/0001-01    100.0 76.703297        23.296703      ALTO
 BIDI4 BRBIDIACNPR0  BANCO INTER   BANCO INTER S.A. 00.416.968/0001-01    100.0 76.703297        23.296703      ALTO
 BIOM4 BRBIOMACNPR9        BIOMM         BIOMM S.A. 04.752.991/0001-10    100.0 63.719298        36.280702      ALTO

======================================================================
MATCHES PARA REVISÃO
======================================================================
ticker         isin      nome_b3                                               nome_cvm               CNPJ   score_1   score_2  diferenca_score
 ARLA3 BRARLAACNOR6 ARTHUR LANGE                                             DUFRY A.G. 11.423.623/0001-93 50.980392 50.742857         0.237535
 ARLA4 BRARLAACNPR3 ARTHUR LANGE                                             DUFRY A.G. 11.423.623/0001-93 50.980392 50.742857         0.237535
 DHBI3 BRDHBIACNOR5        D H B                               HIDROVIAS DO BRASIL S.A. 12.648.327/0001-53 51.263333 49.592754         1.670580
 DHBI4 BRDHBIACNPR2        D H B                               HIDROVIAS DO BRASIL S.A. 12.648.327/0001-53 51.263333 49.592754         1.670580
 LVTC3 BRLVTCACNOR4 WDC NETWORKS                                       MCM CIMENTOS S/A 11.858.621/0001-27 51.363636 49.692308         1.671329
 WDCN3 BRWDCNACNOR2 WDC NETWORKS                                       MCM CIMENTOS S/A 11.858.621/0001-27 51.363636 49.692308         1.671329
 GLOB3 BRGLOBACNOR8       GLOBEX                                               TGLT S/A 14.212.464/0001-76 52.000000 48.671329         3.328671
 TBLE3 BRTBLEACNOR2    TRACTEBEL                                        R/HOLDINGS S.A. 52.475.549/0001-36 52.000000 50.181818         1.818182
 GLOB4 BRGLOBACNPR5       GLOBEX                                               TGLT S/A 14.212.464/0001-76 52.000000 48.671329         3.328671
 CCPR3 BRCCPRACNOR9 CYRE COM-CCP           COMERCIAL QUINTELLA COM EXP SA EM LIQUIDAÇÃO 00.994.533/0001-36 52.222642 52.220743         0.001898
 DOMO3 BRDOMOACNOR6 DOMUS POPULI                                             HOUSI S.A. 15.675.715/0001-11 52.329412 50.166667         2.162745
 CARD3 BRCARDACNOR9 CSU CARDSYST                                        COPERSUCAR S.A. 10.265.949/0001-77 52.994652 50.255754         2.738898
 VCPA4 BRVCPAACNPR2        V C P                                           BCO PAN S.A. 59.285.411/0001-13 53.000000 51.876923         1.123077
 VCPA3 BRVCPAACNOR5        V C P                                           BCO PAN S.A. 59.285.411/0001-13 53.000000 51.876923         1.123077
 LLIS3 BRLLISACNOR4 LE LIS BLANC                        B3 S.A. - BRASIL, BOLSA, BALCÃO 09.346.601/0001-25 53.470588 52.994652         0.475936
 BOVH3 BRBOVHACNOR5  BOVESPA HLD                                         BRADESPAR S.A. 03.847.461/0001-92 53.750000 52.685714         1.064286
 NINJ3 BRNINJACNOR5    GETNINJAS                                           ETERNIT S.A. 61.092.037/0001-81 55.000000 53.739130         1.260870
 AGEI3 BRAGEIACNOR7 AGRE EMP IMO                                          AES ELPA S.A. 01.917.705/0001-30 55.000000 54.557166         0.442834
 ARZZ3 BRARZZACNOR3    AREZZO CO                                       CBO HOLDING S.A. 14.882.295/0001-81 55.066667 55.000000         0.066667
 BTTL4 BRBTTLACNPR7  BATTISTELLA                                            TRISUL S.A. 08.811.643/0001-27 55.529412 53.984962         1.544449
 BTTL3 BRBTTLACNOR0  BATTISTELLA                                            TRISUL S.A. 08.811.643/0001-27 55.529412 53.984962         1.544449
 ELUM3 BRELUMACNOR7        ELUMA                                            MÉLIUZ S.A. 14.110.585/0001-07 56.181818 55.076923         1.104895
 ELUM4 BRELUMACNPR4        ELUMA                                            MÉLIUZ S.A. 14.110.585/0001-07 56.181818 55.076923         1.104895
 PTIP3 BRPTIPACNOR4 IPIRANGA PET                                RIO PARANA ENERGIA S.A. 23.096.269/0001-19 56.333333 55.671429         0.661905
 PTIP4 BRPTIPACNPR1 IPIRANGA PET                                RIO PARANA ENERGIA S.A. 23.096.269/0001-19 56.333333 55.671429         0.661905
 CRFB3 BRCRFBACNOR2 CARREFOUR BR                                               BRF S.A. 01.838.723/0001-27 56.400000 51.355599         5.044401
 VPTA4 BRVPTAACNPR6 VARIG TRANSP                        ARGO TRANSMISSÃO DE ENERGIA S/A 24.624.490/0001-65 56.965035 55.608696         1.356339
 VPTA3 BRVPTAACNOR9 VARIG TRANSP                        ARGO TRANSMISSÃO DE ENERGIA S/A 24.624.490/0001-65 56.965035 55.608696         1.356339
 DPPI4 BRDPPIACNPR5 IPIRANGA DIS                                        PARANA BCO S.A. 14.388.334/0001-99 57.129187 55.030303         2.098884
 ACES3 BRACESACNOR5   AM INOX BR                                              LINX S.A. 06.948.969/0001-75 57.428571 53.947368         3.481203
 ECOD3 BRECODACNOR8    ECODIESEL                                             DEXCO S.A. 97.837.181/0001-47 57.428571 53.984962         3.443609
 ACES4 BRACESACNPR2   AM INOX BR                                              LINX S.A. 06.948.969/0001-75 57.428571 53.947368         3.481203
 JPSA4 BRJPSAACNPR3   JEREISSATI                                          ENERGISA S.A. 00.864.214/0001-06 57.638889 53.784615         3.854274
 JPSA3 BRJPSAACNOR6   JEREISSATI                                          ENERGISA S.A. 00.864.214/0001-06 57.638889 53.784615         3.854274
 MLFT4 BRMLFTACNPR3   JEREISSATI                                          ENERGISA S.A. 00.864.214/0001-06 57.638889 53.784615         3.854274
 MLFT3 BRMLFTACNOR6   JEREISSATI                                          ENERGISA S.A. 00.864.214/0001-06 57.638889 53.784615         3.854274
 IDNT3 BRIDNTACNOR5    IDEIASNET                                 SMILES FIDELIDADE S.A. 05.730.375/0001-20 57.769231 57.638889         0.130342
 CMGR3 BRCMGRACNOR7        CEMAT                                              CREMER SA 82.641.325/0001-18 58.181818 53.800000         4.381818
 ASAI3 BRASAIACNOR0        ASSAI                                              SAUIPE SA 00.866.577/0001-80 58.181818 58.181818         0.000000
 CMGR4 BRCMGRACNPR4        CEMAT                                              CREMER SA 82.641.325/0001-18 58.181818 53.800000         4.381818
 SJOS4 BRSJOSACNPR8 TECEL S JOSE FIACAO E TECELAGEM SAO JOSE SA EM RECUPERACAO JUDICIAL 17.159.005/0001-64 58.528571 52.348387         6.180184
 SJOS3 BRSJOSACNOR1 TECEL S JOSE FIACAO E TECELAGEM SAO JOSE SA EM RECUPERACAO JUDICIAL 17.159.005/0001-64 58.528571 52.348387         6.180184
 VPSC3 BRVPSCACNOR7   VARIG SERV                                BOA VISTA SERVIÇOS S.A. 11.725.176/0001-27 58.600000 53.750000         4.850000
 VPSC4 BRVPSCACNPR4   VARIG SERV                                BOA VISTA SERVIÇOS S.A. 11.725.176/0001-27 58.600000 53.750000         4.850000
 CLSC3 BRCLSCACNOR6       CELESC                                          ELETROSOM S/A 22.164.990/0001-36 58.666667 57.983333         0.683333
 RIPI4 BRRIPIACNPR0 IPIRANGA REF                                RIO PARANA ENERGIA S.A. 23.096.269/0001-19 58.666667 54.222222         4.444444
 RIPI3 BRRIPIACNOR3 IPIRANGA REF                                RIO PARANA ENERGIA S.A. 23.096.269/0001-19 58.666667 54.222222         4.444444
 CLSC4 BRCLSCACNPR3       CELESC                                          ELETROSOM S/A 22.164.990/0001-36 58.666667 57.983333         0.683333
 FGUI3 BRFGUIACNOR2  F GUIMARAES                             GUARARAPES CONFECCOES S.A. 08.402.943/0001-52 58.686364 56.137931         2.548433
 FGUI4 BRFGUIACNPR9  F GUIMARAES                             GUARARAPES CONFECCOES S.A. 08.402.943/0001-52 58.686364 56.137931         2.548433

======================================================================
ARQUIVOS GERADOS
======================================================================
mapping_b3_cvm_completo.csv
mapping_b3_cvm_validado.csv
mapping_b3_cvm_revisar.csv

In [74]:
# ============================================================
# DIAGNÓSTICO DO ISIN E DOS MATCHES
# ============================================================

print("=" * 70)
print("DIAGNÓSTICO DO UNIVERSO")
print("=" * 70)

# ------------------------------------------------------------
# 1. Ticker -> ISIN
# ------------------------------------------------------------

isin_por_ticker = (
    b3
    .groupby("ticker")["isin"]
    .nunique()
)

print("\nISINs por ticker:")
print(isin_por_ticker.value_counts().sort_index())


# ------------------------------------------------------------
# 2. ISIN -> ticker
# ------------------------------------------------------------

ticker_por_isin = (
    b3
    .groupby("isin")["ticker"]
    .nunique()
)

print("\nTickers por ISIN:")
print(ticker_por_isin.value_counts().sort_index())


# ------------------------------------------------------------
# 3. Tickers com mais de um ISIN
# ------------------------------------------------------------

print("\nTickers com mais de um ISIN:")

print(
    isin_por_ticker[
        isin_por_ticker > 1
    ]
    .sort_values(ascending=False)
    .head(30)
)


# ------------------------------------------------------------
# 4. ISINs compartilhados por mais de um ticker
# ------------------------------------------------------------

print("\nISINs compartilhados por mais de um ticker:")

print(
    ticker_por_isin[
        ticker_por_isin > 1
    ]
    .sort_values(ascending=False)
    .head(30)
)


# ------------------------------------------------------------
# 5. Exemplos de ISIN compartilhado
# ------------------------------------------------------------

isins_compartilhados = (
    ticker_por_isin[
        ticker_por_isin > 1
    ]
    .index
)

print("\nExemplos:")

print(
    b3[
        b3["isin"].isin(isins_compartilhados)
    ][
        [
            "ticker",
            "isin",
            "nome_empresa",
            "especificacao"
        ]
    ]
    .sort_values("isin")
    .head(50)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 6. Matches fuzzy com maior incerteza
# ------------------------------------------------------------

print()
print("=" * 70)
print("MATCHES MAIS AMBÍGUOS")
print("=" * 70)

print(
    mapping_preliminar[
        [
            "ticker",
            "isin",
            "nome_b3",
            "nome_cvm",
            "CNPJ",
            "score_1",
            "score_2",
            "diferenca_score",
            "qualidade"
        ]
    ]
    .sort_values(
        ["diferenca_score", "score_1"],
        ascending=[True, False]
    )
    .head(50)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 7. Quantidade de CNPJs encontrados
# ------------------------------------------------------------

print()
print("=" * 70)
print("CNPJs")
print("=" * 70)

print(
    "CNPJs no cadastro CVM:",
    cvm_empresas["CNPJ_Companhia"].nunique()
)

print(
    "CNPJs nos matches:",
    mapping_preliminar["CNPJ"].nunique()
)

print(
    "CNPJs nos matches ALTO/MEDIO:",
    mapping_preliminar[
        mapping_preliminar["qualidade"]
        .isin(["ALTO", "MEDIO"])
    ]["CNPJ"].nunique()
)

======================================================================
DIAGNÓSTICO DO UNIVERSO
======================================================================

ISINs por ticker:
isin
1    822
Name: count, dtype: int64

Tickers por ISIN:
ticker
1    822
Name: count, dtype: int64

Tickers com mais de um ISIN:
Series([], Name: isin, dtype: int64)

ISINs compartilhados por mais de um ticker:
Series([], Name: ticker, dtype: int64)

Exemplos:
Empty DataFrame
Columns: [ticker, isin, nome_empresa, especificacao]
Index: []

======================================================================
MATCHES MAIS AMBÍGUOS
======================================================================
ticker         isin      nome_b3                                       nome_cvm               CNPJ    score_1    score_2  diferenca_score qualidade
 PORT3 BRPORTACNOR8  WILSON SONS                               WILSON SONS LTD. 05.721.735/0001-28 100.000000 100.000000         0.000000   REVISAR
 SUZB3 BRSUZBACNOR0  SUZANO S.A.                                    SUZANO S.A. 16.404.287/0001-55 100.000000 100.000000         0.000000   REVISAR
 BBAS3 BRBBASACNOR3       BRASIL                                BCO BRASIL S.A. 00.000.000/0001-91  90.500000  90.500000         0.000000   REVISAR
 PRBC4 BRPRBCACNPR8       PARANA                                EPR PARANA S.A. 60.978.495/0001-50  90.500000  90.500000         0.000000   REVISAR
 NEMO4 BRNEMOACNPR3  SUZANO HOLD                                    SUZANO S.A. 16.404.287/0001-55  89.176471  89.176471         0.000000   REVISAR
 BNBR3 BRBNBRACNOR8  NORD BRASIL                    BCO NORDESTE DO BRASIL S.A. 07.237.373/0001-20  76.480805  76.480805         0.000000   REVISAR
 BNBR4 BRBNBRACNPR5  NORD BRASIL                    BCO NORDESTE DO BRASIL S.A. 07.237.373/0001-20  76.480805  76.480805         0.000000   REVISAR
 DASA3 BRDASAACNOR1         DASA                                    PARSAN S.A. 44.854.238/0001-50  66.000000  66.000000         0.000000   REVISAR
 FASA3 BRFASAACNOR6         FASA                                    GAFISA S.A. 01.545.826/0001-07  66.000000  66.000000         0.000000   REVISAR
 FICT3 BRFICTACNOR3         FASA                                    GAFISA S.A. 01.545.826/0001-07  66.000000  66.000000         0.000000   REVISAR
 ASAI3 BRASAIACNOR0        ASSAI                                      SAUIPE SA 00.866.577/0001-80  58.181818  58.181818         0.000000   REVISAR
 CCPR3 BRCCPRACNOR9 CYRE COM-CCP   COMERCIAL QUINTELLA COM EXP SA EM LIQUIDAÇÃO 00.994.533/0001-36  52.222642  52.220743         0.001898   REVISAR
 MODL3 BRMODLACNOR2    MODALMAIS                             ALFA HOLDINGS S.A. 17.167.396/0001-69  59.076923  59.068323         0.008600   REVISAR
 MODL4 BRMODLACNPR9    MODALMAIS                             ALFA HOLDINGS S.A. 17.167.396/0001-69  59.076923  59.068323         0.008600   REVISAR
 MMXM3 BRMMXMACNOR2    MMX MINER MASSA FALIDA DA MMX MINERACAO E METALICOS S.A. 02.762.115/0001-49  68.800000  68.750000         0.050000   REVISAR
 ARZZ3 BRARZZACNOR3    AREZZO CO                               CBO HOLDING S.A. 14.882.295/0001-81  55.066667  55.000000         0.066667   REVISAR
 TCNO3 BRTCNOACNOR5    TECNOSOLO     TECNOSOLO ENGENHARIA S.A. - EMPRESA FALIDA 33.111.246/0001-90  80.272727  80.192308         0.080420   REVISAR
 TCNO4 BRTCNOACNPR2    TECNOSOLO     TECNOSOLO ENGENHARIA S.A. - EMPRESA FALIDA 33.111.246/0001-90  80.272727  80.192308         0.080420   REVISAR
 EZTC3 BREZTCACNOR0        EZTEC                            PADTEC HOLDING S.A. 02.365.069/0001-44  60.681818  60.571429         0.110390   REVISAR
 AALR3 BRAALRACNOR6       ALLIAR                       ALLIS PARTICIPAÇÕES S.A. 08.648.295/0001-19  62.400000  62.285714         0.114286   REVISAR
 IDNT3 BRIDNTACNOR5    IDEIASNET                         SMILES FIDELIDADE S.A. 05.730.375/0001-20  57.769231  57.638889         0.130342   REVISAR
 OHLB3 BROHLBACNOR6   OHL BRASIL                                BCO BRASIL S.A. 00.000.000/0001-91  79.666667  79.535897         0.130769   REVISAR
 CZRS4 BRCZRSACNPR1 CRUZEIRO SUL                       BANCO CRUZEIRO DO SUL SA 62.136.254/0001-99  81.418182  81.275824         0.142358   REVISAR
 CNTO3 BRCNTOACNOR5     CENTAURO                        NATURA &CO HOLDING S.A. 32.785.497/0001-97  60.461538  60.317460         0.144078   REVISAR
 AESB3 BRAESBACNOR7   AES BRASIL                         ATHENA SAÚDE BRASIL SA 31.701.408/0001-14  78.421839  78.263158         0.158681   REVISAR
 LCSA3 BRLCSAACNOR0     PARMALAT                              PANATLANTICA S.A. 92.693.019/0001-89  62.000000  61.818182         0.181818   REVISAR
 LCSA4 BRLCSAACNPR7     PARMALAT                              PANATLANTICA S.A. 92.693.019/0001-89  62.000000  61.818182         0.181818   REVISAR
 CRPG3 BRCRPGACNOR0      CRISTAL                                      CIMS S.A. 00.272.185/0001-93  63.272727  63.076923         0.195804   REVISAR
 BRIN3 BRBRINACNOR3 BR INSURANCE                    BRISANET PARTICIPAÇÕES S.A. 19.796.586/0001-70  58.897833  58.666667         0.231166   REVISAR
 MDIA3 BRMDIAACNOR7 M.DIASBRANCO                        ASA BRANCA HOLDING S.A. 09.359.927/0001-97  67.878788  67.643478         0.235310   REVISAR
 ARLA3 BRARLAACNOR6 ARTHUR LANGE                                     DUFRY A.G. 11.423.623/0001-93  50.980392  50.742857         0.237535   REVISAR
 ARLA4 BRARLAACNPR3 ARTHUR LANGE                                     DUFRY A.G. 11.423.623/0001-93  50.980392  50.742857         0.237535   REVISAR
 FNCN3 BRFNCNACNOR6   FINANSINOS                             MINASMAQUINAS S.A. 17.161.241/0001-15  60.608696  60.317460         0.291235   REVISAR
 GPCP3 BRGPCPACNOR4     GPC PART                          JP PARTICIPAÇÕES S.A. 15.463.423/0001-15  63.400000  63.076923         0.323077   REVISAR
 GPCP4 BRGPCPACNPR1     GPC PART                          JP PARTICIPAÇÕES S.A. 15.463.423/0001-15  63.400000  63.076923         0.323077   REVISAR
 RRRP3 BRRRRPACNOR5 3R PETROLEUM                 PETRO RIO JAGUAR PETRÓLEO S.A. 02.031.413/0001-69  63.597052  63.272727         0.324324   REVISAR
 FCAP3 BRFCAPACNOR8  SAM INDUSTR                        MANGELS INDUSTRIAL S.A. 61.065.298/0001-02  70.307210  69.952153         0.355057   REVISAR
 FCAP4 BRFCAPACNPR5  SAM INDUSTR                        MANGELS INDUSTRIAL S.A. 61.065.298/0001-02  70.307210  69.952153         0.355057   REVISAR
 TNCP3 BRTNCPACNOR2 TELE NORT CL                         TELEMAR NORTE LESTE SA 33.000.118/0001-79  72.233871  71.872727         0.361144   REVISAR
 TNCP4 BRTNCPACNPR9 TELE NORT CL                         TELEMAR NORTE LESTE SA 33.000.118/0001-79  72.233871  71.872727         0.361144   REVISAR
 ARCZ3 BRARCZACNOR2      ARACRUZ                                R/HOLDINGS S.A. 52.475.549/0001-36  60.500000  60.135747         0.364253   REVISAR
 LIPR3 BRLIPRACNOR7    ELETROPAR      ELETROBRÁS PARTICIPAÇÕES S.A. - ELETROPAR 01.104.937/0001-70  80.558140  80.192308         0.365832   REVISAR
 TROR3 BRTRORACNOR4      TRORION                                      PRIO S.A. 10.629.105/0001-68  63.272727  62.857143         0.415584   REVISAR
 TROR4 BRTRORACNPR1      TRORION                                      PRIO S.A. 10.629.105/0001-68  63.272727  62.857143         0.415584   REVISAR
 OGXP3 BROGXPACNOR3 OGX PETROLEO                       KAROON PETRÓLEO & GÁS SA 09.347.916/0001-97  76.281818  75.841313         0.440505   REVISAR
 AGEI3 BRAGEIACNOR7 AGRE EMP IMO                                  AES ELPA S.A. 01.917.705/0001-30  55.000000  54.557166         0.442834   REVISAR
 LLIS3 BRLLISACNOR4 LE LIS BLANC                B3 S.A. - BRASIL, BOLSA, BALCÃO 09.346.601/0001-25  53.470588  52.994652         0.475936   REVISAR
 AZTE3 BRAZTEACNOR4  AZT ENERGIA                             BRAVA ENERGIA S.A. 12.091.809/0001-55  80.055556  79.578947         0.476608   REVISAR
 SSBR3 BRSSBRACNOR1 SIERRABRASIL             COMPANHIA AURIFERA BRASILEIRA S.A. 12.078.880/0001-06  64.390244  63.863636         0.526608   REVISAR
 STLB3 BRSTLBACNOR2 STEEL BRASIL                                EBX BRASIL S.A. 10.847.761/0001-37  76.626794  76.086957         0.539838   REVISAR

======================================================================
CNPJs
======================================================================
CNPJs no cadastro CVM: 1230
CNPJs nos matches: 470
CNPJs nos matches ALTO/MEDIO: 180

In [75]:
# ============================================================
# PROCURAR CAMPOS QUE POSSAM LIGAR ISIN / VALOR MOBILIÁRIO
# AO EMISSOR NA CVM
# ============================================================

print("COLUNAS DO df_fca RELACIONADAS A IDENTIFICAÇÃO")
print("=" * 70)

palavras = [
    "ISIN",
    "INSTRUMENT",
    "VALOR",
    "MOBILI",
    "ATIVO",
    "EMISS",
    "TITULO",
    "NEGOC",
    "CODIGO",
    "SIGLA",
    "CLASSE",
    "ACAO"
]

cols_identificacao = [
    c for c in df_fca.columns
    if any(p in c.upper() for p in palavras)
]

for c in cols_identificacao:
    print(c)

COLUNAS DO df_fca RELACIONADAS A IDENTIFICAÇÃO
======================================================================
Orgao_Administracao
Percentual_Participacao_Reunioes
Descricao_Bem_Ativo
Tipo_Ativo
Descricao_Ativo
Duracao
Codigo_CVM_Auditor
Data_Inicio_Contratacao
Data_Fim_Contratacao
Data_Inicio_Prestacao_Servico
Remuneracao_Auditor
Sigla_UF
Data_Autorizacao_Aprovacao
Valor_Capital
Prazo_Integralizacao
Data_Deliberacao
Orgao_Deliberacao_Aumento
Data_Emissao
Valor_Total_Emissao
Fator_Cotacao
Preco_Emissao
Criterio_Determinacao_Preco_Emissao
Forma_Integralizacao
Tipo_Classe_Acao_Preferencial
Data_Aprovacao
Quantidade_Acoes_Ordinarias_Antes_Aprovacao
Quantidade_Acoes_Preferenciais_Antes_Aprovacao
Quantidade_Total_Acoes_Antes_Aprovacao
Quantidade_Acoes_Ordinarias_Depois_Aprovacao
Quantidade_Acoes_Preferenciais_Depois_Aprovacao
Quantidade_Total_Acoes_Depois_Aprovacao
Quantidade_Acoes_Antes_Aprovacao
Quantidade_Acoes_Depois_Aprovacao
Valor_Total_Reducao
Valor_Restituido_Por_Acao
Titulo_Conversivel_Acao
Especie_Acao
Classe_Acao_Preferencial
Restricao_Circulacao
Descricao_Restricao_Circulacao
Condicao_Alteracao_Direitos
Quantidade_Acoes_Ordinarias_Circulacao
Percentual_Acoes_Ordinarias_Circulacao
Quantidade_Acoes_Preferenciais_Circulacao
Percentual_Acoes_Preferenciais_Circulacao
Quantidade_Total_Acoes_Circulacao
Percentual_Total_Acoes_Circulacao
Sigla_Classe_Acoes_Preferenciais
Classe_Acoes_Preferenciais
Taxa_Retorno_Patrimonio_Liquido_Emissor
Data_Aprovacao_Retencao
Classe_Acao
Data_Operacao
Descricao_Operacao
Data_Constituicao_Emissor
Forma_Constituicao_Emissor
Sigla_Pais_Constituicao_Emissor
Pais_Constituicao_Emissor
Prazo_Duracao_Emissor
Data_Registro_Emissor
Requisicao_Registro_Emissor
Codigo_Conta
Valor
Informacao_Financeira
Tipo_Obrigacao
Observacao
Valor_Mobiliario
Identificacao_Valor_Mobiliario
Caracteristicas_Valores_Mobiliarios_Divida
Participacao_Emissor
Codigo_CVM
Data_Valor_Mercado
Data_Valor_Contabil
Valor_Mercado
Valor_Contabil
Variacao_Percentual_Valor_Contabil
Variacao_Percentual_Valor_Mercado
Valor_Montante_Dividendos_Recebidos
Valor_Reserva_Disponivel_Recompra
Escala_Cotacao
Valor_Preco_Medio
Orgao_Aprovacao
Vedacao_Procedimentos_Fiscalizacao
Quantidade_Acao_Ordinaria_Circulacao
Percentual_Acao_Ordinaria_Circulacao
Quantidade_Acao_Preferencial_Circulacao
Percentual_Acao_Preferencial_Circulacao
Data_Ultima_Alteracao
Nome_Emissor
CNPJ_Emissor
Nome_Emissor_Pessoa_Relacionada
CNPJ_Emissor_Pessoa_Relacionada
Tipo_Relacao
Valor_Maior_Remuneracao
Valor_Menor_Remuneracao
Valor_Medio_Remuneracao
Total_Remuneracao
Total_Remuneracao_Orgao
Outros_Valores_Fixos
Participacao_Resultados
Participacao_Reunioes
Outros_Valores_Variaveis
Cessacao_Cargo
Relacao_Emissor
Data_Transacao
Duracao_Transacao
Natureza_Razao_Operacao
Posicao_Contratual_Emissor
Especificacao_Posicao_Contratual_Emissor
Descricao_Valor_Mobiliario
Valor_Total_Inicial
Valor_Preco_Medio_Inicial
Valor_Total_Adquirido
Valor_Preco_Medio_Adquirido
Valor_Total_Alienado
Valor_Preco_Medio_Alienado
Valor_Total_Cancelado
Valor_Preco_Medio_Cancelado
Valor_Total_Final
Valor_Preco_Medio_Final
Percentual_Relacao_Valores_Mobiliarios_Circulacao
Quantidade_Valor_Mobiliario
Percentual_Circulacao
Mercado_Valor_Mobiliario
Descricao_Outro_Valor_Mobiliario
Valor_Volume_Negociado
Valor_Maior_Cotacao
Valor_Menor_Cotacao
Valor_Cotacao_Media

In [76]:
# ============================================================
# PROCURAR ISIN EM TODO O df_fca
# ============================================================

for c in df_fca.columns:
    if df_fca[c].dtype == "object":
        try:
            encontrou = (
                df_fca[c]
                .astype(str)
                .str.upper()
                .str.contains("BR[A-Z0-9]{10}", regex=True, na=False)
                .any()
            )

            if encontrou:
                print("POSSÍVEL COLUNA DE ISIN:", c)

        except Exception:
            pass

POSSÍVEL COLUNA DE ISIN: Outro_Cargo_Funcao
POSSÍVEL COLUNA DE ISIN: Experiencia_Profissional
POSSÍVEL COLUNA DE ISIN: Descricao_Bem_Ativo
POSSÍVEL COLUNA DE ISIN: Descricao_Ativo
POSSÍVEL COLUNA DE ISIN: Consequencia_Perda_Direito
POSSÍVEL COLUNA DE ISIN: Servico_Contratado
POSSÍVEL COLUNA DE ISIN: Criterio_Determinacao_Preco_Emissao
POSSÍVEL COLUNA DE ISIN: Condicoes_Conversao
POSSÍVEL COLUNA DE ISIN: Direito_Dividendo
POSSÍVEL COLUNA DE ISIN: Condicao_Conversibilidade_Efeito_Capital_Social
POSSÍVEL COLUNA DE ISIN: Hipotese_Resgate_Formula_Calculo
POSSÍVEL COLUNA DE ISIN: Condicao_Alteracao_Direitos
POSSÍVEL COLUNA DE ISIN: Outras_Caracteristicas_Relevantes
POSSÍVEL COLUNA DE ISIN: Descricao_Operacao
POSSÍVEL COLUNA DE ISIN: Identificacao_Valor_Mobiliario
POSSÍVEL COLUNA DE ISIN: Caracteristicas_Valores_Mobiliarios_Divida
POSSÍVEL COLUNA DE ISIN: Razao_Social
POSSÍVEL COLUNA DE ISIN: Descricao_Atividades
POSSÍVEL COLUNA DE ISIN: Municipio_Sede
POSSÍVEL COLUNA DE ISIN: Principais_Caracteristicas
POSSÍVEL COLUNA DE ISIN: Nacionalidade
POSSÍVEL COLUNA DE ISIN: Nome_Pessoa_Relacionada
POSSÍVEL COLUNA DE ISIN: Cargo_Pessoa_Relacionada
POSSÍVEL COLUNA DE ISIN: Objeto_Contrato
POSSÍVEL COLUNA DE ISIN: Rescisao

In [77]:
# ============================================================
# RELAÇÃO CÓDIGO CVM x CNPJ
# ============================================================

cvm_cnpj = (
    df_fca[
        ["Codigo_CVM", "CNPJ_CIA", "DENOM_CIA"]
    ]
    .dropna(subset=["Codigo_CVM", "CNPJ_CIA"])
    .drop_duplicates()
)

print(cvm_cnpj.shape)

print(
    cvm_cnpj.head(30).to_string(index=False)
)

print("\nCódigos CVM únicos:")
print(cvm_cnpj["Codigo_CVM"].nunique())

print("\nCNPJs únicos:")
print(cvm_cnpj["CNPJ_CIA"].nunique())

(0, 3)
Empty DataFrame
Columns: [Codigo_CVM, CNPJ_CIA, DENOM_CIA]
Index: []

Códigos CVM únicos:
0

CNPJs únicos:
0

In [78]:
# ============================================================
# ESTRUTURA REAL DO EMISSOR NO FCA
# ============================================================

cols = [
    "Codigo_CVM",
    "CNPJ_Emissor",
    "Nome_Emissor",
    "Razao_Social",
    "Especie_Acao",
    "Classe_Acao",
    "Sigla_Classe_Acoes_Preferenciais",
    "Classe_Acoes_Preferenciais",
]

cols = [c for c in cols if c in df_fca.columns]

fca_emissores = (
    df_fca[cols]
    .dropna(subset=["Codigo_CVM", "CNPJ_Emissor"])
    .drop_duplicates()
)

print("=" * 80)
print("DIMENSÃO")
print("=" * 80)

print("Linhas:", len(fca_emissores))
print("Código CVM:", fca_emissores["Codigo_CVM"].nunique())
print("CNPJ:", fca_emissores["CNPJ_Emissor"].nunique())

print("\n" + "=" * 80)
print("EXEMPLOS")
print("=" * 80)

print(
    fca_emissores
    .head(50)
    .to_string(index=False)
)

print("\n" + "=" * 80)
print("TIPOS DE AÇÃO")
print("=" * 80)

for c in [
    "Especie_Acao",
    "Classe_Acao",
    "Sigla_Classe_Acoes_Preferenciais",
    "Classe_Acoes_Preferenciais"
]:
    
    if c in fca_emissores.columns:
        print(f"\n### {c}")
        print(
            fca_emissores[c]
            .dropna()
            .astype(str)
            .value_counts()
            .head(30)
            .to_string()
        )

print("\n" + "=" * 80)
print("CÓDIGO CVM → CNPJ")
print("=" * 80)

teste = (
    fca_emissores
    .groupby("Codigo_CVM")["CNPJ_Emissor"]
    .nunique()
)

print(
    "Códigos CVM com exatamente 1 CNPJ:",
    (teste == 1).sum()
)

print(
    "Códigos CVM com mais de 1 CNPJ:",
    (teste > 1).sum()
)

print("\n" + "=" * 80)
print("CNPJ → CÓDIGO CVM")
print("=" * 80)

teste2 = (
    fca_emissores
    .groupby("CNPJ_Emissor")["Codigo_CVM"]
    .nunique()
)

print(
    "CNPJs com exatamente 1 Código CVM:",
    (teste2 == 1).sum()
)

print(
    "CNPJs com mais de 1 Código CVM:",
    (teste2 > 1).sum()
)

================================================================================
DIMENSÃO
================================================================================
Linhas: 0
Código CVM: 0
CNPJ: 0

================================================================================
EXEMPLOS
================================================================================
Empty DataFrame
Columns: [Codigo_CVM, CNPJ_Emissor, Nome_Emissor, Razao_Social, Especie_Acao, Classe_Acao, Sigla_Classe_Acoes_Preferenciais, Classe_Acoes_Preferenciais]
Index: []

================================================================================
TIPOS DE AÇÃO
================================================================================

### Especie_Acao
Series([], )

### Classe_Acao
Series([], )

### Sigla_Classe_Acoes_Preferenciais
Series([], )

### Classe_Acoes_Preferenciais
Series([], )

================================================================================
CÓDIGO CVM → CNPJ
================================================================================
Códigos CVM com exatamente 1 CNPJ: 0
Códigos CVM com mais de 1 CNPJ: 0

================================================================================
CNPJ → CÓDIGO CVM
================================================================================
CNPJs com exatamente 1 Código CVM: 0
CNPJs com mais de 1 Código CVM: 0

In [79]:
# ============================================================
# PROCURAR COLUNAS RELACIONADAS A CNPJ / EMISSOR NO B3
# ============================================================

print("=" * 70)
print("COLUNAS DO B3 RELACIONADAS A EMISSOR / CNPJ")
print("=" * 70)

termos = [
    "CNPJ",
    "EMISSOR",
    "EMPRESA",
    "COMPANHIA",
    "ISSUER",
    "CODIGO_CVM",
    "COD_CVM",
    "CVМ"
]

for col in b3.columns:
    if any(
        termo in col.upper()
        for termo in termos
    ):
        print(col)


# ============================================================
# VERIFICAR TODAS AS COLUNAS ATUAIS
# ============================================================

print("\n" + "=" * 70)
print("COLUNAS B3")
print("=" * 70)

for i, col in enumerate(b3.columns):
    print(i, col)

======================================================================
COLUNAS DO B3 RELACIONADAS A EMISSOR / CNPJ
======================================================================
nome_empresa

======================================================================
COLUNAS B3
======================================================================
0 ticker
1 isin
2 nome_empresa
3 especificacao
4 tipo_mercado
5 data
6 nome_norm

In [81]:
import pandas as pd
import glob
import os

pasta = ""

arquivos = glob.glob(
    os.path.join(
        pasta,
        "fre_cia_aberta*_2026.csv"
    )
)

for caminho in arquivos:

    try:

        df_tmp = pd.read_csv(
            caminho,
            sep=";",
            encoding="latin1",
            nrows=5
        )

        print("\n" + "=" * 100)
        print(os.path.basename(caminho))
        print("=" * 100)

        print(df_tmp.columns.tolist())

    except Exception as e:
        print(
            os.path.basename(caminho),
            "->",
            e
        )

In [ ]:
import pandas as pd
import numpy as np
import re
import unicodedata
from difflib import SequenceMatcher


# ============================================================
# CONFIGURAÇÃO
# ============================================================

ARQUIVO_SAIDA = "isin_cnpj_ticker_empresa.csv"

# Se quiser exigir um score mínimo para fuzzy matching
FUZZY_THRESHOLD = 0.85


# ============================================================
# 1. NORMALIZAÇÃO
# ============================================================

def normalizar_texto(x):

    if pd.isna(x):
        return ""

    x = str(x).upper().strip()

    # Remove acentos
    x = unicodedata.normalize("NFKD", x)
    x = "".join(
        c for c in x
        if not unicodedata.combining(c)
    )

    # Substituições
    x = x.replace("&", " E ")

    # Remove pontuação
    x = re.sub(r"[^A-Z0-9\s]", " ", x)

    # Remove termos societários comuns
    termos = [
        " S A ",
        " SA ",
        " S A",
        " CIA ",
        " COMPANHIA ",
        " CORPORATION ",
        " CORP ",
        " HOLDING ",
        " HOLDINGS ",
        " PARTICIPACOES ",
        " PARTICIPACAO ",
        " INVESTIMENTOS ",
        " FINANCEIRA ",
        " BANCO ",
    ]

    for termo in termos:
        x = x.replace(termo, " ")

    # Espaços duplicados
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def normalizar_cnpj(x):

    if pd.isna(x):
        return None

    x = re.sub(r"\D", "", str(x))

    if len(x) == 14:
        return x

    return None


def normalizar_ticker(x):

    if pd.isna(x):
        return ""

    return (
        str(x)
        .upper()
        .strip()
        .replace(" ", "")
    )


def normalizar_isin(x):

    if pd.isna(x):
        return ""

    return (
        str(x)
        .upper()
        .strip()
        .replace(" ", "")
    )


# ============================================================
# 2. PREPARAR df_b3
# ============================================================

b3 = df_b3.copy()

b3.columns = (
    b3.columns
    .str.strip()
    .str.lower()
)


# Verificar colunas esperadas

colunas_necessarias_b3 = [
    "isin",
    "ticker",
    "nome_empresa"
]

faltantes = [
    c for c in colunas_necessarias_b3
    if c not in b3.columns
]

if faltantes:

    raise ValueError(
        f"Colunas ausentes no df_b3: {faltantes}"
    )


# Normalização

b3["isin"] = b3["isin"].apply(normalizar_isin)

b3["ticker_norm"] = (
    b3["ticker"]
    .apply(normalizar_ticker)
)

b3["nome_norm"] = (
    b3["nome_empresa"]
    .apply(normalizar_texto)
)


# ============================================================
# 3. PREPARAR df_fca
# ============================================================

fca = df_fca.copy()

fca.columns = (
    fca.columns
    .str.strip()
)


colunas_necessarias_fca = [
    "CNPJ_Companhia",
    "Nome_Companhia"
]

faltantes = [
    c for c in colunas_necessarias_fca
    if c not in fca.columns
]

if faltantes:

    raise ValueError(
        f"Colunas ausentes no df_fca: {faltantes}"
    )


# CNPJ

fca["cnpj"] = (
    fca["CNPJ_Companhia"]
    .apply(normalizar_cnpj)
)


# Nome

fca["nome_norm"] = (
    fca["Nome_Companhia"]
    .apply(normalizar_texto)
)


# ============================================================
# 4. TENTAR ENCONTRAR TICKER NA CVM
# ============================================================

# Dependendo do seu arquivo FCA, pode não existir ticker.
# Procuramos automaticamente uma coluna que possa conter ticker.

possiveis_tickers = [
    c for c in fca.columns
    if "ticker" in c.lower()
    or "codigo_negociacao" in c.lower()
    or "codigo_negociacao" in c.lower()
]

if possiveis_tickers:

    coluna_ticker_cvm = possiveis_tickers[0]

    fca["ticker_norm"] = (
        fca[coluna_ticker_cvm]
        .apply(normalizar_ticker)
    )

else:

    fca["ticker_norm"] = ""


# ============================================================
# 5. REDUZIR df_fca PARA EMPRESAS ÚNICAS
# ============================================================

empresas = (
    fca[
        [
            "cnpj",
            "Nome_Companhia",
            "nome_norm",
            "ticker_norm"
        ]
    ]
    .dropna(subset=["cnpj"])
    .drop_duplicates()
)


# ============================================================
# 6. MATCH POR CNPJ
# ============================================================

# Se df_b3 tiver CNPJ, usa diretamente.

possiveis_cnpj_b3 = [
    c for c in b3.columns
    if "cnpj" in c.lower()
]

if possiveis_cnpj_b3:

    coluna_cnpj_b3 = possiveis_cnpj_b3[0]

    b3["cnpj"] = (
        b3[coluna_cnpj_b3]
        .apply(normalizar_cnpj)
    )

else:

    b3["cnpj"] = None


# ============================================================
# 7. MAPA CNPJ → EMPRESA
# ============================================================

mapa_cnpj = (
    empresas[
        [
            "cnpj",
            "Nome_Companhia"
        ]
    ]
    .drop_duplicates("cnpj")
)


b3 = b3.merge(
    mapa_cnpj,
    on="cnpj",
    how="left"
)


# ============================================================
# 8. MATCH POR TICKER
# ============================================================

# Criamos mapa ticker → CNPJ

ticker_cnpj = (
    empresas[
        [
            "ticker_norm",
            "cnpj"
        ]
    ]
    .query("ticker_norm != ''")
    .drop_duplicates("ticker_norm")
)


# Só preencher CNPJ ainda vazio

b3 = b3.merge(
    ticker_cnpj.rename(
        columns={
            "cnpj": "cnpj_ticker"
        }
    ),
    on="ticker_norm",
    how="left"
)


b3["cnpj"] = (
    b3["cnpj"]
    .fillna(b3["cnpj_ticker"])
)


b3.drop(
    columns=["cnpj_ticker"],
    inplace=True
)


# ============================================================
# 9. MATCH POR NOME EXATO
# ============================================================

nome_cnpj = (
    empresas[
        [
            "nome_norm",
            "cnpj"
        ]
    ]
    .query("nome_norm != ''")
    .drop_duplicates("nome_norm")
)


b3 = b3.merge(
    nome_cnpj.rename(
        columns={
            "cnpj": "cnpj_nome"
        }
    ),
    on="nome_norm",
    how="left"
)


b3["cnpj"] = (
    b3["cnpj"]
    .fillna(b3["cnpj_nome"])
)


b3.drop(
    columns=["cnpj_nome"],
    inplace=True
)


# ============================================================
# 10. IDENTIFICAR MÉTODO DO MATCH
# ============================================================

b3["match_method"] = "SEM_MATCH"


# CNPJ
b3.loc[
    b3["cnpj"].notna(),
    "match_method"
] = "CNPJ"


# Ticker
b3.loc[
    (
        b3["cnpj"].notna()
        &
        (b3["match_method"] == "SEM_MATCH")
    ),
    "match_method"
] = "TICKER"


# Nome
b3.loc[
    (
        b3["cnpj"].notna()
        &
        (b3["match_method"] == "SEM_MATCH")
    ),
    "match_method"
] = "NOME"


# ============================================================
# 11. FUZZY MATCH DE NOMES
# ============================================================

# Empresas únicas da CVM

nomes_cvm = (
    empresas[
        [
            "cnpj",
            "Nome_Companhia",
            "nome_norm"
        ]
    ]
    .drop_duplicates("cnpj")
)


# Apenas registros ainda sem CNPJ

sem_match = (
    b3["cnpj"].isna()
)


for idx in b3.index[sem_match]:

    nome_b3 = b3.at[idx, "nome_norm"]

    if not nome_b3:
        continue

    melhor_score = 0
    melhor_cnpj = None
    melhor_nome = None

    for _, empresa in nomes_cvm.iterrows():

        nome_cvm = empresa["nome_norm"]

        if not nome_cvm:
            continue

        score = SequenceMatcher(
            None,
            nome_b3,
            nome_cvm
        ).ratio()

        if score > melhor_score:

            melhor_score = score
            melhor_cnpj = empresa["cnpj"]
            melhor_nome = empresa["Nome_Companhia"]

    if melhor_score >= FUZZY_THRESHOLD:

        b3.at[idx, "cnpj"] = melhor_cnpj

        b3.at[idx, "match_method"] = (
            "FUZZY_NOME"
        )

        b3.at[idx, "match_score"] = (
            melhor_score
        )

        b3.at[idx, "Nome_Companhia_CVM"] = (
            melhor_nome
        )


# ============================================================
# 12. PREENCHER SCORE DOS MATCHES EXATOS
# ============================================================

b3["match_score"] = (
    b3["match_score"]
    if "match_score" in b3.columns
    else np.nan
)

b3.loc[
    b3["match_method"] == "CNPJ",
    "match_score"
] = 1.0

b3.loc[
    b3["match_method"] == "TICKER",
    "match_score"
] = 0.95

b3.loc[
    b3["match_method"] == "NOME",
    "match_score"
] = 0.90


# ============================================================
# 13. CONSTRUIR TABELA FINAL
# ============================================================

resultado = b3[
    [
        "isin",
        "cnpj",
        "ticker",
        "nome_empresa",
        "match_method",
        "match_score"
    ]
].copy()


# ============================================================
# 14. REMOVER ISIN VAZIO
# ============================================================

resultado = resultado[
    resultado["isin"] != ""
]


# ============================================================
# 15. REMOVER DUPLICATAS
# ============================================================

resultado = (
    resultado
    .drop_duplicates(
        subset=[
            "isin",
            "cnpj",
            "ticker"
        ]
    )
)


# ============================================================
# 16. ORDENAR
# ============================================================

resultado = (
    resultado
    .sort_values(
        [
            "ticker",
            "isin"
        ]
    )
    .reset_index(drop=True)
)


# ============================================================
# 17. SALVAR
# ============================================================

resultado.to_csv(
    ARQUIVO_SAIDA,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 18. RELATÓRIO
# ============================================================

print("\n")
print("=" * 80)
print("RESULTADO DO MATCH")
print("=" * 80)

print(
    f"Total de ISINs: "
    f"{resultado['isin'].nunique():,}"
)

print(
    f"Com CNPJ: "
    f"{resultado['cnpj'].notna().sum():,}"
)

print(
    f"Sem CNPJ: "
    f"{resultado['cnpj'].isna().sum():,}"
)

print("\nMétodo de matching:")

print(
    resultado["match_method"]
    .value_counts(dropna=False)
)

print("\nTaxa de cobertura:")

cobertura = (
    resultado["cnpj"].notna().mean()
)

print(
    f"{cobertura:.2%}"
)

print("\nArquivo gerado:")

print(ARQUIVO_SAIDA)


# ============================================================
# 19. MOSTRAR CASOS SEM MATCH
# ============================================================

sem_match_final = resultado[
    resultado["cnpj"].isna()
].copy()


print("\n")
print("=" * 80)
print("ISINs SEM CNPJ")
print("=" * 80)

print(
    sem_match_final.head(50)
)

In [ ]:
# ============================================================
# EXPORTAR LIQUIDEZ, VOLUME E MARKET CAP PARA O MODELO
# ============================================================
# Gera liquidez_mercado.csv no formato lido por
# momentum_etf/src/market_data.py:
#     date, ticker, volume_financeiro, market_cap
#
# - volume_financeiro: R$ negociados no dia (COTAHIST, mercado à vista).
# - market_cap: preço de fechamento da classe x quantidade de ações da
#   classe (ON para final 3, PN para finais 4-8), usando o capital social
#   mais recente informado à CVM ATÉ aquela data (merge_asof para trás,
#   sem look-ahead). Units (final 11) ficam sem market cap.
# - Só entram tickers de acoes_retornos.csv (df_wide), então units e
#   papéis como B3SA3 não são perdidos pelo regex [A-Z]{4}[3-8].
# - O mapeamento ticker -> CNPJ usa só os matches ALTO/MEDIO da célula
#   de matching (mapping_validado). Tickers sem match ficam com
#   market_cap vazio e o modelo, por padrão, não os filtra por tamanho.
#
# Copie o arquivo gerado para momentum_etf/data/.

ARQUIVO_LIQUIDEZ = "liquidez_mercado.csv"

tickers_modelo = set(df_wide.columns.astype(str).str.strip().str.upper())

# ------------------------------------------------------------
# 1. Volume e preço diários (mercado à vista, tickers do modelo)
# ------------------------------------------------------------

diario = df_b3[["data", "ticker", "tipo_mercado", "preco_ultimo", "volume_financeiro"]].copy()
diario["ticker"] = diario["ticker"].astype(str).str.strip().str.upper()
diario["tipo_mercado"] = diario["tipo_mercado"].astype(str).str.strip()
diario = diario[
    (diario["tipo_mercado"] == "010")
    & diario["ticker"].isin(tickers_modelo)
    & diario["data"].notna()
]

diario = (
    diario
    .sort_values(["ticker", "data"])
    .groupby(["data", "ticker"], as_index=False)
    .agg(
        volume_financeiro=("volume_financeiro", "sum"),
        preco_ultimo=("preco_ultimo", "last"),
    )
)

# ------------------------------------------------------------
# 2. Quantidade de ações por ticker ao longo do tempo
# ------------------------------------------------------------

cap = df_capital_social[
    [
        "CNPJ_Companhia",
        "Data_Referencia",
        "Quantidade_Acoes_Ordinarias",
        "Quantidade_Acoes_Preferenciais",
    ]
].copy()
cap["CNPJ"] = cap["CNPJ_Companhia"].astype(str).str.replace(r"\D", "", regex=True).str.zfill(14)
cap["Data_Referencia"] = pd.to_datetime(cap["Data_Referencia"], errors="coerce")
for col in ["Quantidade_Acoes_Ordinarias", "Quantidade_Acoes_Preferenciais"]:
    cap[col] = pd.to_numeric(cap[col], errors="coerce")
cap = cap.dropna(subset=["Data_Referencia"])

mapa = mapping_validado[["ticker", "CNPJ"]].copy()
mapa["ticker"] = mapa["ticker"].astype(str).str.strip().str.upper()
mapa["CNPJ"] = mapa["CNPJ"].astype(str).str.replace(r"\D", "", regex=True).str.zfill(14)
mapa = mapa.drop_duplicates("ticker")

acoes = mapa.merge(cap, on="CNPJ", how="inner")
acoes["quantidade_acoes"] = np.select(
    [acoes["ticker"].str.fullmatch(r"[A-Z0-9]{4}3"), acoes["ticker"].str.fullmatch(r"[A-Z0-9]{4}[4-8]")],
    [acoes["Quantidade_Acoes_Ordinarias"], acoes["Quantidade_Acoes_Preferenciais"]],
    default=np.nan,
)
acoes = (
    acoes[acoes["quantidade_acoes"] > 0]
    .sort_values(["ticker", "Data_Referencia"])
    .drop_duplicates(["ticker", "Data_Referencia"], keep="last")
    [["ticker", "Data_Referencia", "quantidade_acoes"]]
)

# ------------------------------------------------------------
# 3. Market cap diário = preço x última quantidade conhecida
# ------------------------------------------------------------

diario = pd.merge_asof(
    diario.sort_values("data"),
    acoes.sort_values("Data_Referencia"),
    left_on="data",
    right_on="Data_Referencia",
    by="ticker",
    direction="backward",
)
diario["market_cap"] = diario["preco_ultimo"] * diario["quantidade_acoes"]

liquidez_mercado = (
    diario
    .rename(columns={"data": "date"})
    [["date", "ticker", "volume_financeiro", "market_cap"]]
    .sort_values(["date", "ticker"])
    .reset_index(drop=True)
)

liquidez_mercado.to_csv(ARQUIVO_LIQUIDEZ, index=False)

# ------------------------------------------------------------
# 4. Diagnóstico de cobertura
# ------------------------------------------------------------

print("Arquivo salvo:", ARQUIVO_LIQUIDEZ, liquidez_mercado.shape)
print("Período:", liquidez_mercado["date"].min(), "até", liquidez_mercado["date"].max())
print(f"Tickers do modelo: {len(tickers_modelo):,}")
print(f"  com volume:     {liquidez_mercado['ticker'].nunique():,}")
print(f"  com market cap: {liquidez_mercado.dropna(subset=['market_cap'])['ticker'].nunique():,}")
print("\nTickers do modelo sem nenhum volume na B3:")
print(sorted(tickers_modelo - set(liquidez_mercado["ticker"]))[:50])